import { defineCourse } from "./builder";

export const addressingTroubleshooting = defineCourse({
  id: "ip-troubleshooting",
  title: "IP Addressing & Network Troubleshooting",
  description:
    "Master IPv4 addressing, core network services, diagnostic tools, and symptom-driven troubleshooting.",
  icon: "🩺",
  modules: [
    {
      id: "ip-addressing",
      title: "IPv4 Addressing & Subnets",
      description: "IPv4 structure, public/private ranges, subnet masks, gateways, and basic subnetting.",
      topics: ["IPv4", "Public & Private IPs", "Subnet Masks", "Subnetting", "Default Gateway"],
      questions: [
        {
          id: "ip-add-1", topic: "IPv4", type: "definition", difficulty: "foundation",
          question: "An IPv4 address has two logical parts. What are they?",
          accepted: ["the network portion and the host portion", "network part and host part"],
          required: ["network", "host"],
          explanation: "Every IPv4 address splits into a network portion (which network) and host portion (which device on it); the subnet mask marks the boundary.",
          improved: "The network portion, identifying which network the address belongs to, and the host portion, identifying the specific device within that network.",
        },
        {
          id: "ip-add-2", topic: "Public & Private IPs", type: "definition", difficulty: "foundation",
          question: "Name any one of the three private IPv4 address ranges.",
          accepted: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "10.x.x.x", "192.168", "172.16 to 172.31"],
          required: [], optional: ["10.", "172.16", "192.168"],
          explanation: "RFC 1918 reserves 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16 for private networks — not routable on the internet.",
          improved: "The three private ranges are 10.0.0.0/8, 172.16.0.0–172.31.255.255, and 192.168.0.0/16 — usable inside any organisation but never routed on the public internet.",
        },
        {
          id: "ip-add-3", topic: "Public & Private IPs", type: "comparison", difficulty: "applied",
          question: "Your PC shows 192.168.1.50 but a 'what is my IP' website shows 84.23.101.7. Why are they different?",
          accepted: ["the pc has a private address and nat on the router translates it to the public address", "192.168 is private, the router's public ip is what the internet sees via nat"],
          required: ["private", "nat"], optional: ["public", "router", "translation"],
          explanation: "The PC uses a private RFC 1918 address internally; the router's NAT rewrites outgoing traffic to its single public IP — which is all external sites ever see.",
          improved: "192.168.1.50 is the PC's private internal address. The router performs NAT, translating internal traffic to its public address 84.23.101.7 — the only address visible to the internet.",
        },
        {
          id: "ip-add-4", topic: "Subnet Masks", type: "definition", difficulty: "foundation",
          question: "What does the subnet mask 255.255.255.0 tell a device?",
          accepted: ["the first three octets are the network and the last octet is the host", "addresses matching the first three octets are local, others need the gateway"],
          required: ["network", "host"], optional: ["first three octets", "local"],
          explanation: "The mask marks the network/host boundary: with /24, anything sharing the first three octets is on the local network; everything else routes via the gateway.",
          improved: "That the first three octets identify the network and the last identifies the host — so the device treats addresses matching its first three octets as local and sends everything else to the default gateway.",
        },
        {
          id: "ip-add-5", topic: "Subnetting", type: "configuration_reasoning", difficulty: "applied",
          question: "How many usable host addresses exist in a /24, and why is it not 256?",
          accepted: ["254, because the network address and broadcast address can't be assigned", "254 usable, two are reserved for network and broadcast"],
          required: ["254"], optional: ["network address", "broadcast"],
          explanation: "A /24 has 256 addresses, but the all-zeros host (network ID) and all-ones host (broadcast) are reserved, leaving 254.",
          improved: "254 — a /24 contains 256 addresses, but the first (the network address) and the last (the broadcast address) cannot be assigned to hosts.",
        },
        {
          id: "ip-add-6", topic: "Subnetting", type: "configuration_reasoning", difficulty: "applied",
          question: "A team needs 4 subnets from 192.168.10.0/24. What new prefix length gives exactly 4 subnets, and how many hosts does each hold?",
          accepted: ["/26 giving four subnets of 62 hosts each", "26, each with 62 usable hosts"],
          required: ["26", "62"],
          explanation: "Borrowing 2 bits (/24→/26) creates 2²=4 subnets of 64 addresses each; minus network and broadcast leaves 62 usable hosts apiece.",
          improved: "/26 — borrowing two bits creates exactly four subnets (.0, .64, .128, .192), each with 64 addresses of which 62 are usable hosts.",
        },
        {
          id: "ip-add-7", topic: "Subnetting", type: "troubleshooting", difficulty: "scenario",
          question: "Host A is 192.168.1.10/25 and Host B is 192.168.1.200/25. They can't ping each other despite the same switch. Why?",
          accepted: ["a /25 splits the range in half so they are on different subnets and need a router", "with mask 255.255.255.128 host a is in the lower subnet and host b in the upper, different networks"],
          required: ["different subnet"], optional: ["/25 splits", "router needed", "128"],
          explanation: "/25 divides .0–.127 and .128–.255 into separate networks. A (.10) and B (.200) are on different subnets, so they need routing even though they share a switch.",
          improved: "A /25 mask splits the /24 into two subnets: .0–.127 and .128–.255. Host A is in the first, Host B in the second — different networks, so traffic between them needs a router, not just a shared switch.",
        },
        {
          id: "ip-add-8", topic: "Default Gateway", type: "packet_journey", difficulty: "applied",
          question: "How does a host decide whether to send a packet directly to the destination or to its default gateway?",
          accepted: ["it compares the destination with its own network using the subnet mask, local goes direct, remote goes to the gateway", "it ands the destination ip with its mask, if the network matches its own it's local, otherwise gateway"],
          required: ["mask"], optional: ["compare", "local", "gateway", "network match"],
          explanation: "The host masks the destination IP and compares it to its own network. Match = deliver locally (ARP for the host); no match = forward to gateway.",
          improved: "It applies its subnet mask to the destination address and compares the network portion with its own. If they match the destination is local and it sends directly; if not, it forwards the packet to the default gateway.",
        },
        {
          id: "ip-add-9", topic: "IPv4", type: "definition", difficulty: "foundation",
          question: "What special address does a device use to send a message to every host on its local network?",
          accepted: ["the broadcast address", "broadcast, the last address in the subnet like 192.168.1.255"],
          required: ["broadcast"],
          explanation: "The subnet's broadcast address (host bits all ones, e.g. 192.168.1.255 on a /24) reaches every local host.",
          improved: "The broadcast address — the subnet's last address (all host bits set to 1), such as 192.168.1.255 on a /24 network.",
        },
        {
          id: "ip-add-10", topic: "Default Gateway", type: "troubleshooting", difficulty: "applied",
          question: "A PC's gateway is set to 192.168.2.1 but the PC's own address is 192.168.1.20/24. What is wrong?",
          accepted: ["the gateway is not on the pc's subnet so it can never be reached", "a gateway must be in the same local network as the host"],
          required: ["same subnet"], optional: ["unreachable", "local network"],
          explanation: "A gateway must be locally reachable — inside the host's own subnet. 192.168.2.1 isn't in 192.168.1.0/24, so the PC can't even reach its gateway.",
          improved: "The default gateway must live on the PC's own subnet. 192.168.2.1 is outside 192.168.1.0/24, so the PC has no way to reach it — all off-network traffic fails immediately.",
        },
        {
          id: "ip-add-11", topic: "Public & Private IPs", type: "configuration_reasoning", difficulty: "applied",
          question: "Why do organisations use private addressing internally instead of requesting public IPs for every device?",
          accepted: ["public ipv4 addresses are scarce and cost money, private ranges are free and reused everywhere with nat providing internet access", "conserves scarce public address space and adds separation, nat handles the translation"],
          required: ["scarce"], optional: ["nat", "free", "conserve", "reused"],
          explanation: "IPv4 exhaustion makes public addresses scarce/costly. Private ranges are freely reusable in every organisation, with NAT sharing few public IPs.",
          improved: "Public IPv4 addresses are scarce and expensive; private ranges are free and infinitely reusable across organisations. NAT then lets thousands of private devices share a handful of public addresses.",
        },
        {
          id: "ip-add-12", topic: "IPv4", type: "definition", difficulty: "applied",
          question: "What does 127.0.0.1 refer to, and what is it used for?",
          accepted: ["the loopback address, used to test the device's own network stack", "localhost, traffic to it never leaves the machine"],
          required: ["loopback"], optional: ["localhost", "test", "own machine"],
          explanation: "127.0.0.1 (localhost) loops traffic back inside the host — pinging it verifies the local TCP/IP stack works without touching the network.",
          improved: "It's the loopback (localhost) address: traffic sent there never leaves the machine. Pinging 127.0.0.1 tests that the device's own TCP/IP stack functions, independent of any network hardware.",
        },
        {
          id: "ip-add-13", topic: "Subnet Masks", type: "troubleshooting", difficulty: "scenario",
          question: "A server was configured as 10.1.1.50 mask 255.255.0.0 but the network is actually 10.1.1.0/24. It reaches some devices but not others. Why the strange partial behaviour?",
          accepted: ["the wrong mask makes it think all of 10.1 is local so it arps instead of routing for remote 10.1.x hosts and fails", "with /16 it treats other 10.1 subnets as local and never uses the gateway for them"],
          required: ["mask", "local"], optional: ["arp", "gateway", "never routes"],
          explanation: "With /16 the server believes every 10.1.x.x host is local, ARPing directly instead of routing. On-subnet peers work; hosts on other 10.1.x subnets silently fail.",
          improved: "The /16 mask makes the server treat all of 10.1.0.0/16 as local, so for hosts on other 10.1.x subnets it ARPs directly instead of sending to the gateway — those ARPs get no answer and connections fail, while true /24 neighbours work fine.",
        },
        {
          id: "ip-add-14", topic: "Subnetting", type: "configuration_reasoning", difficulty: "applied",
          question: "What is CIDR notation, e.g. the '/24' in 192.168.1.0/24?",
          accepted: ["the number of bits in the network portion of the mask", "a shorthand where the number counts the mask's leading one bits"],
          required: ["bits", "network"], optional: ["mask", "prefix length"],
          explanation: "CIDR expresses the mask as a prefix length: /24 = 24 network bits = 255.255.255.0.",
          improved: "CIDR notation expresses the subnet mask as a prefix length — the count of network bits. /24 means the first 24 bits are network, equivalent to mask 255.255.255.0.",
        },
      ],
    },
    {
      id: "ip-services",
      title: "Core Network Services",
      description: "DHCP, DNS, NAT, ARP, and ICMP — what they do and how they fail.",
      topics: ["DHCP", "DNS", "NAT", "ARP", "ICMP"],
      questions: [
        {
          id: "ip-svc-1", topic: "DHCP", type: "packet_journey", difficulty: "applied",
          question: "Walk through the four DHCP messages exchanged when a laptop joins a network.",
          accepted: ["discover, offer, request, acknowledge", "the client discovers, server offers, client requests, server acknowledges", "dora"],
          required: ["discover", "offer", "request", "acknowledge"],
          explanation: "DORA: the client broadcasts Discover, servers Offer a lease, the client Requests one offer, and the server Acknowledges — configuration complete.",
          improved: "Discover (client broadcasts 'any DHCP servers?'), Offer (server proposes an address), Request (client formally asks for that offer), Acknowledge (server confirms the lease) — the DORA sequence.",
        },
        {
          id: "ip-svc-2", topic: "ARP", type: "definition", difficulty: "applied",
          question: "A host knows the destination's IP but needs its MAC address to build the frame. What protocol solves this and how?",
          accepted: ["arp broadcasts asking who has this ip and the owner replies with its mac", "address resolution protocol maps ip to mac via a broadcast request and unicast reply"],
          required: ["arp"], optional: ["broadcast", "mac", "reply"],
          explanation: "ARP broadcasts 'who has 192.168.1.20?'; the owner unicasts back its MAC, which the sender caches in its ARP table.",
          improved: "ARP — the host broadcasts 'who has this IP?', the device owning it replies with its MAC address, and the mapping is cached in the ARP table for future frames.",
        },
        {
          id: "ip-svc-3", topic: "DNS", type: "packet_journey", difficulty: "applied",
          question: "In what order does a computer typically look up a hostname before asking a DNS server?",
          accepted: ["local cache first, then the hosts file, then the configured dns server", "dns cache, hosts file, then dns query"],
          required: ["cache"], optional: ["hosts file", "then dns server"],
          explanation: "Resolution checks the local DNS cache, then the hosts file, and only then queries the configured DNS server.",
          improved: "It checks its local DNS cache first, then the hosts file, and only if neither answers does it send a query to its configured DNS server.",
        },
        {
          id: "ip-svc-4", topic: "NAT", type: "definition", difficulty: "applied",
          question: "How does a NAT router know which internal device should receive a reply packet coming back from the internet?",
          accepted: ["it keeps a translation table matching internal address and port to the external port used", "the nat table maps each session's ports back to the private ip"],
          required: ["table"], optional: ["port", "session", "mapping"],
          explanation: "NAT records each outbound session (private IP:port ↔ public port) in its translation table; replies are matched by port and forwarded back.",
          improved: "The router keeps a NAT translation table: each outgoing connection's private IP and port are mapped to a unique public port. When the reply arrives, the port identifies the session and the router forwards it to the right internal device.",
        },
        {
          id: "ip-svc-5", topic: "ICMP", type: "definition", difficulty: "foundation",
          question: "What protocol do ping and traceroute rely on, and what is its general role?",
          accepted: ["icmp, which carries network error and diagnostic messages", "internet control message protocol, for diagnostics and error reporting"],
          required: ["icmp"], optional: ["error", "diagnostic", "control messages"],
          explanation: "ICMP is IP's control channel — echo requests/replies (ping), destination-unreachable and TTL-expired errors (traceroute exploits the latter).",
          improved: "ICMP — the Internet Control Message Protocol. It carries diagnostic and error messages: ping uses ICMP echo request/reply, and traceroute uses ICMP time-exceeded responses.",
        },
        {
          id: "ip-svc-6", topic: "DHCP", type: "troubleshooting", difficulty: "scenario",
          question: "Every device in one office wing gets a 169.254.x.x address after a switch replacement, while other wings are fine. What is the most likely cause?",
          accepted: ["that wing lost its path to the dhcp server, likely a vlan or uplink misconfiguration on the new switch", "the new switch isn't passing dhcp broadcasts, wrong vlan or missing uplink"],
          required: ["dhcp"], optional: ["vlan", "uplink", "new switch", "broadcast"],
          explanation: "APIPA everywhere in one wing = DHCP unreachable from there. The new switch is the change: wrong VLAN, missing uplink, or missing DHCP relay.",
          improved: "The new switch cut that wing off from the DHCP server — most likely its ports are in the wrong VLAN or its uplink isn't configured, so DHCP broadcasts can't reach the server and clients fall back to APIPA.",
        },
        {
          id: "ip-svc-7", topic: "DNS", type: "troubleshooting", difficulty: "scenario",
          question: "Users can reach internal servers by name, but every external website fails to resolve. Internal DNS is running. What should you check on the DNS server?",
          accepted: ["its forwarders or upstream dns, since it resolves internal zones but can't resolve external names", "the forwarder configuration or the server's own internet access"],
          required: ["forward"], optional: ["upstream", "external", "recursion", "internet access"],
          explanation: "Internal zones answer locally; external names need forwarding/recursion to upstream DNS. Broken forwarders (or the server's own internet path) match this exact split.",
          improved: "Check its forwarders: internal names come from local zones, but external lookups are forwarded upstream. If the forwarder is misconfigured or unreachable (or the server itself has no internet path), exactly this internal-works/external-fails split appears.",
        },
        {
          id: "ip-svc-8", topic: "NAT", type: "troubleshooting", difficulty: "scenario",
          question: "A company hosts a web server internally but customers on the internet can't reach it, though outbound browsing works. What NAT feature is missing?",
          accepted: ["port forwarding or a static nat mapping for inbound traffic to the server", "inbound nat, a destination nat rule publishing the server"],
          required: ["port forwarding"], optional: ["static nat", "inbound", "destination nat"],
          explanation: "NAT is outbound by default — unsolicited inbound connections have no mapping. Publishing a server requires a static/port-forward rule sending port 443/80 to it.",
          improved: "A port-forwarding (static NAT) rule: NAT only builds mappings for outbound sessions, so unsolicited inbound requests are dropped. The router needs a rule forwarding inbound web ports to the server's private address.",
        },
        {
          id: "ip-svc-9", topic: "ARP", type: "troubleshooting", difficulty: "scenario",
          question: "After swapping a server's NIC, other machines can't reach it for a few minutes, then it recovers on its own. What cached data explains this?",
          accepted: ["stale arp entries mapping the ip to the old mac until they expire", "neighbors cached the old mac in their arp tables"],
          required: ["arp"], optional: ["stale", "old mac", "cache", "expire"],
          explanation: "Peers had the old NIC's MAC cached in ARP tables; frames went to a dead address until entries timed out and re-resolved to the new MAC.",
          improved: "Neighbouring devices still had ARP cache entries mapping the server's IP to the old NIC's MAC address. Their frames went nowhere until the stale entries expired and ARP re-learned the new MAC.",
        },
        {
          id: "ip-svc-10", topic: "DHCP", type: "configuration_reasoning", difficulty: "applied",
          question: "Why are servers and printers usually given fixed addresses (static or DHCP reservation) instead of ordinary DHCP leases?",
          accepted: ["their address must never change because other systems connect to them by address or via records pointing at it", "clients and dns records depend on a stable address"],
          required: ["change"], optional: ["stable", "depend", "dns records", "reservation"],
          explanation: "Things people connect TO need stable addresses — mappings, DNS records, and firewall rules all reference them. Reservations keep DHCP's convenience with a fixed outcome.",
          improved: "Because other systems depend on finding them at a stable address — DNS records, printer mappings, and firewall rules all point at it. A changed lease would silently break those, so servers get static IPs or DHCP reservations.",
        },
        {
          id: "ip-svc-11", topic: "DNS", type: "definition", difficulty: "applied",
          question: "What is DNS caching, and what is one downside when a server's IP changes?",
          accepted: ["resolvers remember answers for their ttl, so changed records take time to propagate and old ips are used meanwhile", "answers are stored temporarily which speeds lookups but delays updates"],
          required: ["cache"], optional: ["ttl", "stale", "propagat", "delay"],
          explanation: "Caching stores answers for their TTL, cutting lookups drastically — but after an IP change, cached (stale) answers keep sending users to the old address until TTLs expire.",
          improved: "Resolvers cache answers for the record's TTL to make lookups fast. The downside: after an IP change, cached entries keep pointing users at the old address until every cache's TTL expires.",
        },
        {
          id: "ip-svc-12", topic: "ICMP", type: "configuration_reasoning", difficulty: "applied",
          question: "A firewall admin blocks all ICMP 'for security'. Name a diagnostic ability the business just lost.",
          accepted: ["ping and traceroute stop working so reachability testing and path diagnosis break", "no echo replies means monitoring and troubleshooting tools lose visibility"],
          required: ["ping"], optional: ["traceroute", "monitoring", "path mtu", "diagnostics"],
          explanation: "Blanket-blocking ICMP kills ping/traceroute (and can break path-MTU discovery). Monitoring and troubleshooting go blind; selective ICMP filtering is wiser.",
          improved: "Ping and traceroute stop working — reachability tests, latency measurement, path tracing, and most network monitoring lose visibility. (Blanket ICMP blocks can also break path-MTU discovery, causing weird transfer failures.)",
        },
      ],
    },
    {
      id: "ip-tools",
      title: "Diagnostic Tools & Command Outputs",
      description: "ping, traceroute, ipconfig and friends — running them and reading their output.",
      topics: ["Ping", "Traceroute", "Command Outputs"],
      questions: [
        {
          id: "ip-tool-1", topic: "Ping", type: "troubleshooting", difficulty: "applied",
          question: "Ping shows 'Reply from 192.168.1.1: time=2ms' four times. What two facts have you established?",
          accepted: ["the destination is reachable and responds quickly with no loss", "connectivity to it works and round trip latency is about 2 ms"],
          required: ["reachable"], optional: ["latency", "2ms", "no loss"],
          explanation: "Replies prove two-way reachability; the time field measures round-trip latency (2 ms = excellent, LAN-typical).",
          improved: "That the destination is reachable in both directions with zero packet loss, and that the round-trip latency is about 2 ms — a healthy local connection.",
        },
        {
          id: "ip-tool-2", topic: "Ping", type: "troubleshooting", difficulty: "applied",
          question: "What is the difference between ping replying 'Request timed out' and 'Destination host unreachable'?",
          accepted: ["timed out means no reply came back, unreachable means a device actively reported there's no route", "timeout is silence, unreachable is an explicit no path answer often from your own gateway"],
          required: ["no reply", "route"], optional: ["silence", "gateway", "explicit"],
          explanation: "Timeout = packets vanished (blocked, dropped, or the host ignores ping). Unreachable = a router (often your own) replied 'I have no path there'.",
          improved: "'Request timed out' means the packet got no answer — dropped, filtered, or ignored. 'Destination host unreachable' means a device (often your own PC or gateway) explicitly reported it has no route to that destination.",
        },
        {
          id: "ip-tool-3", topic: "Traceroute", type: "definition", difficulty: "applied",
          question: "What does traceroute show you that ping cannot?",
          accepted: ["every router hop along the path and the latency to each", "the route packets take, hop by hop, revealing where delay or failure occurs"],
          required: ["hop"], optional: ["path", "each router", "where it fails"],
          explanation: "Ping is end-to-end only; traceroute enumerates each router on the path with per-hop latency, pinpointing where problems begin.",
          improved: "The full path: every router hop between you and the destination with latency to each — so you can see exactly where along the route delay or loss begins, not just that it exists.",
        },
        {
          id: "ip-tool-4", topic: "Traceroute", type: "troubleshooting", difficulty: "scenario",
          question: "A traceroute to a cloud app shows hops 1–5 at ~5 ms, then hops 6 onward jump to 200 ms. Where is the slowdown, roughly?",
          accepted: ["between hop 5 and hop 6, likely entering a congested or distant network segment", "the latency starts at hop 6 so the link into that hop is the problem area"],
          required: ["hop 6"], optional: ["between 5 and 6", "that link", "congestion"],
          explanation: "Latency inherited by all later hops begins at the hop where it first appears — the link into hop 6 is where delay is added (distance or congestion).",
          improved: "The delay is introduced on the link between hops 5 and 6 — everything after inherits it. That segment is either congested or a long-distance leg (e.g., an undersea or intercontinental link).",
        },
        {
          id: "ip-tool-5", topic: "Command Outputs", type: "troubleshooting", difficulty: "applied",
          question: "Which command shows a Windows PC's IP address, mask, gateway, and DNS servers — and what's the macOS/Linux rough equivalent?",
          accepted: ["ipconfig /all on windows, ifconfig or ip addr on linux and mac", "ipconfig, and ip a or ifconfig elsewhere"],
          required: ["ipconfig"], optional: ["ip addr", "ifconfig"],
          explanation: "`ipconfig /all` dumps the full IP configuration on Windows; `ip addr`/`ifconfig` (plus `ip route`, `scutil --dns`) covers Unix-likes.",
          improved: "Windows: `ipconfig /all` shows the complete configuration. macOS/Linux: `ifconfig` or `ip addr` for addresses, `ip route`/`netstat -rn` for the gateway.",
        },
        {
          id: "ip-tool-6", topic: "Command Outputs", type: "troubleshooting", difficulty: "applied",
          question: "What does 'nslookup example.com' test, and what does it mean if it fails while pinging an IP still works?",
          accepted: ["it tests dns resolution, failure with working ip connectivity means a dns problem", "queries the dns server for the name, isolating name resolution from connectivity"],
          required: ["dns"], optional: ["resolution", "isolates", "name lookup"],
          explanation: "nslookup queries DNS directly. If it fails while raw IP works, connectivity is fine and the fault is isolated to name resolution.",
          improved: "nslookup sends a DNS query for the name. If it fails while pinging an IP address works, the network path is fine — the problem is isolated to DNS resolution (server down, unreachable, or misconfigured).",
        },
        {
          id: "ip-tool-7", topic: "Ping", type: "troubleshooting", difficulty: "scenario",
          question: "Describe the classic 'expanding ping' sequence for isolating a connectivity fault from a user's PC.",
          accepted: ["ping loopback, then own ip, then the gateway, then an external ip, then a name, each step isolates a layer", "127.0.0.1 first, then local gateway, then 8.8.8.8, then a domain name"],
          required: ["gateway"], optional: ["loopback", "127.0.0.1", "external ip", "then a name", "in order"],
          explanation: "Loopback (stack) → own IP (NIC) → gateway (LAN) → external IP (routing/ISP) → domain name (DNS). The first failure locates the layer.",
          improved: "Ping 127.0.0.1 (TCP/IP stack), then the PC's own IP (NIC), then the default gateway (LAN path), then an external IP like 8.8.8.8 (routing/ISP), then a domain name (DNS). Wherever it first fails is the layer at fault.",
        },
        {
          id: "ip-tool-8", topic: "Command Outputs", type: "troubleshooting", difficulty: "applied",
          question: "The command 'arp -a' shows two different IP addresses with the SAME MAC address, and users report intermittent outages. What might this indicate?",
          accepted: ["a duplicate ip conflict or arp spoofing", "either an ip conflict or a spoofing attack, both corrupt arp mappings"],
          required: [], optional: ["duplicate ip", "conflict", "spoofing", "attack"],
          explanation: "One MAC answering for two IPs (or two MACs fighting over one IP) signals an address conflict — or deliberate ARP spoofing. Both wreak intermittent havoc.",
          improved: "Either a duplicate-IP conflict (one device wrongly configured with another's address) or ARP spoofing (a device impersonating others to intercept traffic). Both corrupt ARP tables and cause exactly this intermittent chaos — worth investigating urgently.",
        },
        {
          id: "ip-tool-9", topic: "Traceroute", type: "troubleshooting", difficulty: "applied",
          question: "In a traceroute, one middle hop shows '* * *' but later hops respond normally. Is the path broken?",
          accepted: ["no, that router just doesn't answer traceroute probes, traffic still passes through it", "not necessarily, the hop deprioritizes or blocks icmp replies but forwards fine"],
          required: ["no"], optional: ["blocks icmp", "deprioritize", "still forwards"],
          mistakes: ["Declaring the starred hop 'down' — a down hop would break every hop after it."],
          explanation: "Routers often rate-limit or block probe replies while forwarding normally. Since later hops answer, the path is intact.",
          improved: "No — that router simply doesn't reply to traceroute probes (many block or rate-limit ICMP responses) but forwards traffic fine. If it were actually down, every hop after it would fail too.",
        },
        {
          id: "ip-tool-10", topic: "Ping", type: "troubleshooting", difficulty: "scenario",
          question: "Pinging a server every second for a minute shows times of 2ms, 3ms, 250ms, 2ms, 190ms, 3ms... What network quality problem does this variation indicate, and what applications suffer most?",
          accepted: ["jitter, which hurts real time applications like voice and video calls", "high latency variation called jitter, voip and video conferencing degrade"],
          required: ["jitter"], optional: ["voice", "video", "real time", "variation"],
          explanation: "Wild swings in round-trip time = jitter. Bulk transfers barely notice; real-time voice/video — which need steady packet timing — degrade badly.",
          improved: "That's jitter — high variation in latency. Real-time applications suffer most: VoIP calls and video conferences need packets arriving at steady intervals, so jitter causes choppy audio and frozen video even when average latency looks fine.",
        },
      ],
    },
    {
      id: "ts-symptoms",
      title: "Diagnosing Common Failures",
      description: "Duplicate IPs, gateway and DNS/DHCP failures — symptom-driven diagnosis.",
      topics: ["Duplicate IPs", "Gateway Issues", "DNS Failures", "DHCP Failures"],
      questions: [
        {
          id: "ts-sym-1", topic: "Duplicate IPs", type: "troubleshooting", difficulty: "scenario",
          question: "Two users report their PCs randomly lose connection, and one saw an 'IP address conflict' warning. What happened, and what's a common root cause?",
          accepted: ["two devices have the same ip, often a static address inside the dhcp pool", "duplicate ip conflict, commonly caused by manually assigning an address dhcp also hands out"],
          required: ["same ip"], optional: ["static", "dhcp pool", "conflict"],
          explanation: "Both devices claim one address; traffic flip-flops between them. Classic cause: someone statically assigned an IP inside the DHCP range.",
          improved: "Two devices hold the same IP address, so traffic intermittently reaches the wrong one. The classic root cause: a statically-configured device using an address that's also inside the DHCP pool — fix by excluding static addresses from the pool.",
        },
        {
          id: "ts-sym-2", topic: "Gateway Issues", type: "troubleshooting", difficulty: "applied",
          question: "A user can ping every local device including the gateway, but nothing beyond it. Where do you look next?",
          accepted: ["at the router itself, its wan link or the isp, since the lan side is proven", "beyond the gateway, router config, the internet circuit or upstream provider"],
          required: ["router"], optional: ["wan", "isp", "upstream", "circuit"],
          explanation: "LAN and gateway reachability are proven; the fault is past the gateway — router config/NAT, the WAN circuit, or the ISP.",
          improved: "Past the gateway: the router's own WAN interface and routing/NAT config, the physical internet circuit, and the ISP. The LAN side is proven healthy, so the break is on the outside leg.",
        },
        {
          id: "ts-sym-3", topic: "DNS Failures", type: "troubleshooting", difficulty: "scenario",
          question: "At 9am, dozens of users simultaneously report 'the internet is down', yet a technician's ping to 1.1.1.1 works from the same LAN. What's the most likely failing service?",
          accepted: ["dns, connectivity is fine but name resolution is failing for everyone", "the dns server, since raw ip works but websites by name don't"],
          required: ["dns"], optional: ["resolution", "server down"],
          explanation: "Users experience 'internet down' when names stop resolving even though IP transit is perfect — a failed/unreachable DNS server hits everyone at once.",
          improved: "The DNS server: IP connectivity is proven by the successful ping, but if DNS is down every website 'fails' for every user simultaneously — which matches the sudden, universal symptom perfectly.",
        },
        {
          id: "ts-sym-4", topic: "DHCP Failures", type: "troubleshooting", difficulty: "scenario",
          question: "Monday morning: users who reboot their PCs lose connectivity, while machines left on all weekend still work. What service failed, and why the split?",
          accepted: ["dhcp is down, rebooted machines can't get a lease while running ones keep their old lease", "the dhcp server failed, existing leases keep working until they expire"],
          required: ["dhcp"], optional: ["lease", "reboot", "expire"],
          explanation: "Running machines coast on existing leases; rebooted ones must re-request and fail. This lease-based split is DHCP failure's signature.",
          improved: "The DHCP server is down. Machines left running still hold valid leases and work; rebooted machines must request a fresh lease, get no answer, and fall back to APIPA — the tell-tale split symptom of DHCP failure.",
        },
        {
          id: "ts-sym-5", topic: "DNS Failures", type: "troubleshooting", difficulty: "applied",
          question: "One user's browser says 'server not found' for all sites; nslookup on their PC also fails, but works on a neighbour's PC. Both use DHCP. What per-machine setting or state would you inspect?",
          accepted: ["the pc's dns configuration and cache, maybe a manually set dns server or corrupted cache", "its configured dns servers, flush the dns cache, check for overrides like vpn or proxy"],
          required: ["dns"], optional: ["cache", "flush", "manual", "override", "vpn"],
          explanation: "Neighbour works ⇒ infrastructure fine. Inspect this PC's effective DNS servers (manual override? VPN/proxy hijack?) and flush its resolver cache.",
          improved: "Check the PC's own DNS settings — a manual override, stale VPN adapter, or proxy could bypass the DHCP-provided servers — and flush its DNS cache (`ipconfig /flushdns`). The working neighbour proves the shared infrastructure is fine.",
        },
        {
          id: "ts-sym-6", topic: "Gateway Issues", type: "troubleshooting", difficulty: "scenario",
          question: "After an IT change over the weekend, every PC has internet except the finance VLAN. Finance PCs have correct-looking IPs. What routing element deserves first suspicion?",
          accepted: ["the gateway or inter vlan routing config for that vlan, likely changed or missing", "the router or l3 switch interface for the finance vlan"],
          required: ["vlan"], optional: ["gateway", "inter vlan routing", "interface", "acl"],
          explanation: "One VLAN broken while others work points to its specific gateway interface/SVI, its routing entry, or a new ACL — all likely touched by the weekend change.",
          improved: "The finance VLAN's gateway: its SVI/router interface, route, or a new ACL. When exactly one VLAN loses external access after a change, its specific inter-VLAN routing configuration is almost always what changed.",
        },
        {
          id: "ts-sym-7", topic: "Duplicate IPs", type: "configuration_reasoning", difficulty: "applied",
          question: "What practice prevents duplicate-IP conflicts on a network that mixes DHCP clients and statically-addressed printers?",
          accepted: ["exclude the static addresses from the dhcp pool or use reservations instead", "keep static addresses outside the dhcp range, document them, or convert to dhcp reservations"],
          required: ["exclude"], optional: ["reservation", "outside the pool", "document"],
          explanation: "Conflicts vanish when static devices live outside the DHCP scope (or become reservations) and the plan is documented.",
          improved: "Keep static addresses outside the DHCP pool — either exclude a documented range for them, or better, convert the printers to DHCP reservations so the server guarantees each MAC its fixed address.",
        },
        {
          id: "ts-sym-8", topic: "DHCP Failures", type: "troubleshooting", difficulty: "applied",
          question: "The DHCP server is healthy, but clients on a remote subnet across a router can't get leases. Local-subnet clients can. What's missing?",
          accepted: ["a dhcp relay or ip helper on the router, since dhcp broadcasts don't cross routers", "ip helper address forwarding the discover broadcasts to the server"],
          required: ["relay"], optional: ["ip helper", "broadcasts don't cross routers"],
          explanation: "DHCP Discover is a broadcast; routers don't forward broadcasts. Remote subnets need a relay (IP helper) converting them to unicast toward the server.",
          improved: "A DHCP relay (IP helper address) on the router: DHCP Discover messages are broadcasts, which routers don't forward. The relay converts them to unicast aimed at the DHCP server, letting remote subnets get leases.",
        },
        {
          id: "ts-sym-9", topic: "Gateway Issues", type: "troubleshooting", difficulty: "applied",
          question: "A tablet works fine on Wi-Fi at the office but shows 'connected, no internet' at a café. Which side almost certainly has the problem?",
          accepted: ["the café's network, since the tablet works elsewhere", "the cafe side, its internet uplink or captive portal, not the tablet"],
          required: ["café"], optional: ["captive portal", "their uplink", "not the tablet"],
          explanation: "Working elsewhere clears the tablet. 'Connected, no internet' at one venue = that venue's uplink or an unaccepted captive portal.",
          improved: "The café's network — the tablet is proven good at the office. Likely the café's internet uplink is down or a captive portal needs accepting before traffic is allowed through.",
        },
        {
          id: "ts-sym-10", topic: "DNS Failures", type: "troubleshooting", difficulty: "scenario",
          question: "A company migrated its website to a new host yesterday. Some customers see the new site; others still get the old one. Nothing is 'down'. Explain.",
          accepted: ["dns caching, resolvers with the old record cached keep serving the old ip until ttl expires", "propagation delay, cached dns answers point some users at the old server"],
          required: ["cache"], optional: ["ttl", "propagation", "old record"],
          explanation: "Resolvers worldwide cached the old A record; each serves it until its TTL expires. Users split between old/new until caches age out.",
          improved: "DNS caching: resolvers around the internet cached the old address and keep answering with it until the record's TTL expires. Customers behind those caches reach the old server; others get the new one. Lowering TTL before a migration shortens this window.",
        },
        {
          id: "ts-sym-11", topic: "Duplicate IPs", type: "troubleshooting", difficulty: "scenario",
          question: "Immediately after cloning a VM, both the original and the clone misbehave on the network. What did the clone duplicate, and what must be changed?",
          accepted: ["it kept the same ip and possibly mac, give the clone a new address and regenerate its identity", "the clone has a duplicate ip and mac, change them"],
          required: ["duplicate"], optional: ["ip", "mac", "change the clone"],
          explanation: "Clones inherit network identity — static IP and sometimes MAC. Both duplicated identities must be made unique before the clone joins the network.",
          improved: "The clone inherited the original's network identity — its static IP and possibly its MAC address. Give the clone a unique IP (and regenerate its MAC/machine identity) before connecting it to the same network.",
        },
        {
          id: "ts-sym-12", topic: "DHCP Failures", type: "troubleshooting", difficulty: "scenario",
          question: "Devices join the office Wi-Fi and get valid IPs, but a new batch of 50 IoT sensors mostly fails to get addresses. The DHCP scope is 192.168.1.100–150. What's wrong?",
          accepted: ["the pool has only about 50 addresses and is exhausted", "dhcp scope exhaustion, not enough addresses in the range for all the devices"],
          required: ["exhaust"], optional: ["pool too small", "51 addresses", "enlarge the scope"],
          explanation: "The scope holds ~51 addresses; existing clients plus 50 sensors oversubscribe it. Exhausted pools silently strand late arrivals — enlarge the scope or subnet.",
          improved: "DHCP scope exhaustion: the pool only spans ~51 addresses, already partly consumed by existing devices. The sensors that arrive after the pool empties get nothing. Enlarge the scope (or move IoT to its own subnet/VLAN with adequate space).",
        },
      ],
    },
    {
      id: "ts-performance",
      title: "Performance Problems",
      description: "Packet loss, latency, jitter, cabling and Wi-Fi signal issues.",
      topics: ["Packet Loss", "Latency", "Jitter", "Cabling Problems", "Wi-Fi Signal"],
      questions: [
        {
          id: "ts-perf-1", topic: "Packet Loss", type: "comparison", difficulty: "applied",
          question: "How does 2% packet loss affect a file download versus a video call, and why the difference?",
          accepted: ["the download slows because tcp retransmits, the call gets choppy because lost packets are gone forever in real time", "tcp recovers losses so downloads just slow, udp media can't wait so quality drops"],
          required: ["retransmit"], optional: ["choppy", "real time", "tcp", "udp"],
          explanation: "TCP retransmits losses — downloads complete, just slower. Real-time UDP media can't wait for retransmission: lost audio/video is simply missing.",
          improved: "The download completes but slower — TCP detects and retransmits every lost segment. The video call degrades visibly: it runs on UDP in real time, so lost packets can't be retransmitted in time and become glitches, artifacts, and dropped audio.",
        },
        {
          id: "ts-perf-2", topic: "Latency", type: "comparison", difficulty: "applied",
          question: "A user says 'our internet is slow'. Distinguish the two different problems this could mean: low bandwidth versus high latency.",
          accepted: ["bandwidth is capacity, transfers are slow, latency is delay, interactions feel laggy", "low bandwidth limits throughput of big transfers, high latency delays every round trip making things feel sluggish"],
          required: ["bandwidth", "latency"], optional: ["capacity", "delay", "throughput", "lag"],
          explanation: "Bandwidth = how much per second (downloads crawl). Latency = how long each round trip takes (clicks feel laggy, calls delayed). Different causes, different fixes.",
          improved: "Low bandwidth means limited capacity — big downloads and streams crawl. High latency means every round trip is delayed — pages feel laggy, video calls echo, remote sessions lag even though downloads may be fast. Diagnosing which one it is changes the fix entirely.",
        },
        {
          id: "ts-perf-3", topic: "Jitter", type: "definition", difficulty: "applied",
          question: "What is jitter, and what buffer-based mechanism do VoIP systems use to fight it?",
          accepted: ["variation in packet arrival timing, smoothed by a jitter buffer that briefly delays playback", "inconsistent latency, voip uses jitter buffers"],
          required: ["variation"], optional: ["jitter buffer", "playback delay", "smooth"],
          explanation: "Jitter is inconsistent packet spacing. A jitter buffer holds packets briefly, releasing them at steady intervals — trading a little latency for smoothness.",
          improved: "Jitter is variation in packet arrival timing. VoIP endpoints use a jitter buffer: they hold incoming packets for a few milliseconds and release them at a steady rate, trading a small added delay for smooth audio.",
        },
        {
          id: "ts-perf-4", topic: "Cabling Problems", type: "troubleshooting", difficulty: "scenario",
          question: "A desk connection drops whenever the user rolls their chair over the cable run. What is failing physically, and what's the professional fix?",
          accepted: ["the cable's conductors are damaged by crushing, run it through protective containment or reroute it properly", "intermittent break in a crushed cable, replace it and route it safely"],
          required: ["cable"], optional: ["damaged", "crushed", "replace", "containment", "reroute"],
          explanation: "Crushing breaks conductors intermittently — connection drops under flex. Replace the cable and route it via containment (trunking/under-floor), never across the floor.",
          improved: "The cable's conductors are intermittently breaking where the chair crushes them. Replace the damaged cable and route the run properly — through floor boxes, trunking, or wall points — so it can't be rolled over again.",
        },
        {
          id: "ts-perf-5", topic: "Wi-Fi Signal", type: "troubleshooting", difficulty: "scenario",
          question: "Office Wi-Fi degrades every day around lunchtime near the kitchen. What classic interference source should you suspect, and which band does it hit?",
          accepted: ["the microwave oven interfering with the 2.4 ghz band", "microwave, it disrupts 2.4 ghz wifi"],
          required: ["microwave"], optional: ["2.4"],
          explanation: "Microwave ovens radiate in the 2.4 GHz band. Lunchtime degradation near a kitchen is the textbook signature; 5 GHz clients are unaffected.",
          improved: "The kitchen microwave — it leaks radio energy across the 2.4 GHz band while running. Moving nearby users/APs to 5 GHz (or relocating the AP) eliminates the lunchtime slump.",
        },
        {
          id: "ts-perf-6", topic: "Packet Loss", type: "troubleshooting", difficulty: "scenario",
          question: "A switch port shows rapidly climbing CRC errors on its counters. What layer is the problem at, and name two likely culprits.",
          accepted: ["physical layer, a bad cable or connector, emi, or a failing port or nic", "layer 1, damaged cabling, dodgy termination, interference or duplex mismatch"],
          required: ["cable"], optional: ["physical", "layer 1", "emi", "connector", "duplex mismatch", "nic"],
          explanation: "CRC errors mean corrupted frames — physical-layer trouble: damaged cable/termination, EMI, failing NIC/port, or a duplex mismatch.",
          improved: "CRC errors are corrupted frames — a physical-layer (Layer 1) problem. Prime suspects: a damaged cable or poor termination, electromagnetic interference along the run, a failing NIC or switch port, or a duplex mismatch on the link.",
        },
        {
          id: "ts-perf-7", topic: "Wi-Fi Signal", type: "troubleshooting", difficulty: "applied",
          question: "A user's laptop shows full Wi-Fi bars but browsing is miserably slow. Give two reasons signal strength alone doesn't guarantee performance.",
          accepted: ["the channel may be congested with many users or interference, and the ap's uplink or internet may be the bottleneck", "strong signal but a crowded channel, co channel interference, or an overloaded ap"],
          required: [], optional: ["congestion", "interference", "channel", "overloaded ap", "uplink", "many users"],
          explanation: "Bars measure signal to the AP, not airtime availability (congested/interfered channel) nor what's behind the AP (overloaded uplink, saturated internet).",
          improved: "Bars only measure signal strength to the AP. The channel may be congested — dozens of clients or neighbouring networks sharing the same airtime — or the AP itself may be overloaded or have a saturated uplink. Strong signal, no available capacity.",
        },
        {
          id: "ts-perf-8", topic: "Latency", type: "troubleshooting", difficulty: "applied",
          question: "Why does a satellite internet connection have high latency even when its bandwidth is decent?",
          accepted: ["the signal must travel to a satellite and back, a huge distance that adds hundreds of milliseconds", "physical distance to orbit, propagation delay dominates"],
          required: ["distance"], optional: ["satellite", "propagation", "orbit", "speed of light"],
          explanation: "Geostationary satellites orbit ~36,000 km up — the radio round trip alone costs ~500 ms, regardless of bandwidth. Physics, not capacity.",
          improved: "Because every packet physically travels to the satellite and back — for geostationary satellites that's ~36,000 km each way, adding roughly half a second of round-trip delay. Bandwidth can be high, but the speed of light sets a latency floor.",
        },
      ],
    },
    {
      id: "ts-method",
      title: "Troubleshooting Method",
      description: "The layered troubleshooting model and a systematic diagnostic approach.",
      topics: ["OSI Troubleshooting", "Methodology"],
      questions: [
        {
          id: "ts-met-1", topic: "OSI Troubleshooting", type: "troubleshooting", difficulty: "applied",
          question: "What does 'bottom-up troubleshooting' mean, and why start at the bottom?",
          accepted: ["start at the physical layer, cables and links, and work upward, because higher layers can't work if lower ones are broken", "check layer 1 first since everything depends on it, then move up through ip and applications"],
          required: ["physical"], optional: ["layer 1", "work up", "depends on"],
          explanation: "Each layer depends on those below. Verifying cables/links first (cheap, fast) prevents wasted hours debugging applications on top of a dead cable.",
          improved: "Start at Layer 1 — cables, link lights, Wi-Fi association — and work upward through IP, transport, and application. Higher layers can't function if lower ones are broken, and physical checks are the fastest to perform.",
        },
        {
          id: "ts-met-2", topic: "Methodology", type: "troubleshooting", difficulty: "scenario",
          question: "Why should a technician ask 'what changed recently?' near the start of any troubleshooting session?",
          accepted: ["most sudden failures are caused by a recent change, finding it shortcuts the diagnosis", "correlating the failure with a change often reveals the cause immediately"],
          required: ["change"], optional: ["recent", "cause", "correlate"],
          explanation: "Networks that worked yesterday rarely break spontaneously — updates, new rules, new hardware. Identifying the change often IS the diagnosis.",
          improved: "Because things that worked yesterday rarely break by themselves — a config change, update, new device, or new firewall rule usually triggered it. Identifying the change first can collapse hours of layer-by-layer diagnosis into minutes.",
        },
        {
          id: "ts-met-3", topic: "Methodology", type: "troubleshooting", difficulty: "applied",
          question: "What is 'divide and conquer' troubleshooting on a network path, and give a concrete example.",
          accepted: ["test the middle of the path to halve the search, like pinging the gateway to split local from external", "start at a midpoint such as layer 3 connectivity and move up or down based on the result"],
          required: ["middle"], optional: ["halve", "ping the gateway", "split"],
          explanation: "Test a midpoint (e.g., ping the gateway): success clears everything below/before; failure localizes it. Each test halves the search space.",
          improved: "Test the midpoint of the path or stack to halve the problem space each time — for example, ping the default gateway: if it succeeds, the local network is fine and you look outward; if it fails, the problem is local and you look at cable, NIC, and switch.",
        },
        {
          id: "ts-met-4", topic: "Methodology", type: "troubleshooting", difficulty: "scenario",
          question: "After fixing an issue, name two things a good technician does before closing the ticket.",
          accepted: ["verify the fix from the user's perspective and document the cause and solution", "confirm it actually works for the user and write down what was found and changed"],
          required: ["verify", "document"], optional: ["user's perspective", "root cause", "record"],
          explanation: "Verify end-to-end (the user's actual workflow, not just a ping) and document cause/fix — future incidents resolve faster and changes stay traceable.",
          improved: "Verify the fix from the user's perspective — have them run their actual workflow, not just watch a ping succeed — and document the root cause, the fix, and any changes made, so the next occurrence is a lookup instead of an investigation.",
        },
      ],
    },
  ],
});
