import { defineCourse } from "./builder";

/**
 * Original practice questions inspired by the PUBLIC learning objectives of
 * Cisco Networking Academy's "Networking Basics" course. No Cisco lesson
 * text, quizzes, or assessments are copied.
 */
export const ciscoNetworkingBasics = defineCourse({
  id: "cisco-networking-basics", // internal id kept stable for saved progress
  title: "Networking Foundations",
  provider: "Cisco Networking Academy",
  description:
    "Build foundational knowledge of networks, devices, media, protocols and basic connectivity.",
  sourceUrl: "https://www.netacad.com/courses/networking-basics?courseLang=en-US",
  icon: "🌐",
  disclaimer:
    "Supplementary practice inspired by the public learning objectives of Cisco Networking Academy. This is not an official Cisco assessment.",
  modules: [
    {
      id: "nb-networks",
      title: "What Is a Network?",
      description: "Network purpose, common network types, LANs and WANs.",
      topics: ["Networks", "LAN & WAN", "Network Types"],
      questions: [
        {
          id: "nb-net-1", topic: "Networks", type: "definition", difficulty: "foundation",
          question: "In one sentence, what is a computer network?",
          accepted: ["devices connected together to share data and resources", "a group of connected devices that communicate and share resources", "computers linked so they can exchange information"],
          required: ["connected devices"], optional: ["share resources", "communicate"],
          mistakes: ["Describing only the internet — a network can be two devices in one room."],
          explanation: "A network is any set of devices connected so they can communicate and share resources like files, printers, and internet access.",
          improved: "A computer network is a group of connected devices that can communicate with each other to share data and resources.",
        },
        {
          id: "nb-net-2", topic: "LAN & WAN", type: "comparison", difficulty: "foundation",
          question: "What is the key difference between a LAN and a WAN?",
          accepted: ["a lan covers a small local area while a wan connects locations over large distances", "lan is local, wan spans cities or countries"],
          required: ["local", "large distance"], optional: ["office or building", "connects sites"],
          mistakes: ["Thinking WAN just means 'wireless' — that's WLAN."],
          explanation: "A LAN covers a small area such as a home or office; a WAN links networks across large geographic distances, like branch offices in different cities.",
          improved: "A LAN connects devices within a small local area like one building, while a WAN connects networks across large geographic distances, such as between cities.",
        },
        {
          id: "nb-net-3", topic: "Network Types", type: "definition", difficulty: "foundation",
          question: "What kind of network is created when your phone shares its mobile connection with your laptop?",
          accepted: ["a personal hotspot", "a personal area network", "tethering creates a small personal network", "hotspot"],
          required: ["hotspot"], optional: ["personal area network", "tethering"],
          explanation: "A phone hotspot is a tiny wireless network — effectively a personal area network — that shares the phone's mobile data connection.",
          improved: "It creates a personal hotspot: a small wireless network where the phone acts as the access point and router for nearby devices.",
        },
        {
          id: "nb-net-4", topic: "Networks", type: "definition", difficulty: "foundation",
          question: "Give two everyday things that only work because devices are networked.",
          accepted: ["email and video calls", "streaming video and online banking", "printing to a shared printer and browsing websites", "online gaming and messaging"],
          required: [], optional: ["email", "streaming", "video calls", "shared printer", "web browsing", "online gaming", "messaging", "banking"],
          explanation: "Nearly all modern services — email, streaming, shared printers, messaging, cloud storage — depend on networks moving data between devices.",
          improved: "Examples include sending email, streaming video, video calling, online gaming, cloud file storage, and printing to a shared office printer.",
        },
        {
          id: "nb-net-5", topic: "LAN & WAN", type: "device_identification", difficulty: "foundation",
          question: "Your home Wi-Fi with a laptop, TV, and printer connected — is that a LAN or a WAN?",
          accepted: ["a lan", "lan", "it is a local area network"],
          required: ["lan"],
          mistakes: ["Calling it a WAN because it connects to the internet — the internet link goes to a WAN, but the home network itself is a LAN."],
          explanation: "A home network is a classic LAN: a small set of devices in one location. The router's internet connection is the on-ramp to a WAN.",
          improved: "It's a LAN — all devices are in one small local area. The connection from the router out to the ISP is where the WAN begins.",
        },
        {
          id: "nb-net-6", topic: "Network Types", type: "comparison", difficulty: "applied",
          question: "How does a peer-to-peer network differ from a client-server network?",
          accepted: ["in peer to peer every device can act as both client and server while client server uses dedicated servers", "p2p has no dedicated server, client server centralizes services"],
          required: ["peer", "dedicated server"], optional: ["both client and server", "centralized"],
          explanation: "In peer-to-peer, devices share resources directly with each other. In client-server, dedicated servers provide services that clients consume — easier to manage and secure at scale.",
          improved: "In a peer-to-peer network every device can act as both client and server, sharing directly. A client-server network centralizes services on dedicated servers, which scales and secures better.",
        },
        {
          id: "nb-net-7", topic: "Networks", type: "definition", difficulty: "foundation",
          question: "What is the internet, in networking terms?",
          accepted: ["a global network of interconnected networks", "a worldwide network of networks", "many networks connected together globally"],
          required: ["network of networks"], optional: ["global", "interconnected"],
          mistakes: ["Confusing the internet with the web — the web is one service that runs on the internet."],
          explanation: "The internet is a global 'network of networks' — millions of LANs and provider networks interconnected using common protocols.",
          improved: "The internet is a global network of interconnected networks that all communicate using the common TCP/IP protocol suite.",
        },
        {
          id: "nb-net-8", topic: "Network Types", type: "troubleshooting", difficulty: "applied",
          question: "A café owner wants customers to browse the internet but not see the till system. What basic concept should their network use?",
          accepted: ["separate the guest network from the business network", "network segmentation", "a separate guest wifi network"],
          required: ["separate"], optional: ["guest network", "segmentation", "vlan"],
          mistakes: ["Only recommending a stronger Wi-Fi password — guests would still share the till's network."],
          explanation: "Guests and business systems should be on separate (segmented) networks so guest devices can't reach the point-of-sale equipment.",
          improved: "Use segmentation: a dedicated guest network isolated from the business network, so customer devices can reach the internet but never the till system.",
        },
        {
          id: "nb-net-9", topic: "LAN & WAN", type: "definition", difficulty: "foundation",
          question: "What do we call the company that provides your connection from your home LAN to the internet?",
          accepted: ["an internet service provider", "isp", "the isp"],
          required: ["internet service provider"],
          explanation: "An ISP (Internet Service Provider) supplies the WAN link between your local network and the wider internet.",
          improved: "An ISP — Internet Service Provider — which supplies and operates the link connecting your local network to the internet.",
        },
        {
          id: "nb-net-10", topic: "Networks", type: "packet_journey", difficulty: "applied",
          question: "Name the three things every network needs in order to move a message from one device to another.",
          accepted: ["devices, media, and rules or protocols", "end devices, a medium to carry the signal, and protocols", "source and destination devices, media, protocols"],
          required: ["devices", "media", "protocols"],
          explanation: "Communication needs devices (source/destination), media to carry signals (copper, fibre, or radio), and agreed rules — protocols — so both sides understand each other.",
          improved: "Every network needs devices to send and receive, transmission media (copper, fibre, or wireless) to carry the signal, and protocols — shared rules that govern the communication.",
        },
      ],
    },
    {
      id: "nb-components",
      title: "Network Components",
      description: "End devices, intermediary devices, routers, switches, access points, firewalls, and NICs.",
      topics: ["End Devices", "Routers", "Switches", "Access Points", "Firewalls", "NICs"],
      questions: [
        {
          id: "nb-comp-1", topic: "End Devices", type: "definition", difficulty: "foundation",
          question: "What is an 'end device' in a network? Give an example.",
          accepted: ["a device where a message starts or ends, like a laptop", "the source or destination of data, for example a pc or printer", "a user device such as a phone or computer"],
          required: ["source or destination"], optional: ["laptop", "printer", "phone", "user device"],
          explanation: "End devices (hosts) are where data originates or terminates — PCs, phones, printers, servers — as opposed to devices that just forward traffic.",
          improved: "An end device is where a message begins or ends its journey — for example a laptop, phone, printer, or server.",
        },
        {
          id: "nb-comp-2", topic: "End Devices", type: "comparison", difficulty: "foundation",
          question: "What is the difference between an end device and an intermediary device?",
          accepted: ["end devices send and receive data while intermediary devices forward it along the path", "intermediary devices like switches and routers connect and forward, end devices are the source and destination"],
          required: ["forward"], optional: ["source and destination", "switches and routers"],
          explanation: "End devices produce and consume data; intermediary devices (switches, routers, APs, firewalls) sit in the path and move that data toward its destination.",
          improved: "End devices are the source and destination of data. Intermediary devices — switches, routers, access points, firewalls — sit between them and forward traffic along the path.",
        },
        {
          id: "nb-comp-3", topic: "Routers", type: "device_identification", difficulty: "foundation",
          question: "Which device connects different networks together and chooses the best path between them?",
          accepted: ["a router", "router", "the router"],
          required: ["router"],
          mistakes: ["Answering 'switch' — switches connect devices within one network."],
          explanation: "Routers operate between networks, using routing tables to pick the best path for each packet.",
          improved: "A router — it connects separate networks and uses its routing table to forward packets along the best path.",
        },
        {
          id: "nb-comp-4", topic: "Switches", type: "device_identification", difficulty: "foundation",
          question: "Which device connects many wired devices within the same local network and forwards frames using MAC addresses?",
          accepted: ["a switch", "switch", "a network switch"],
          required: ["switch"],
          mistakes: ["Answering 'hub' — hubs blindly repeat to every port; switches forward intelligently."],
          explanation: "A switch builds a MAC address table and forwards each frame only to the port where the destination lives.",
          improved: "A switch — it learns which MAC address is on which port and forwards frames only where they need to go.",
        },
        {
          id: "nb-comp-5", topic: "Access Points", type: "definition", difficulty: "foundation",
          question: "What does a wireless access point do?",
          accepted: ["it connects wireless devices to the wired network", "provides wifi access to the lan", "bridges wireless clients onto the wired network"],
          required: ["wireless", "wired network"], optional: ["wifi", "bridge"],
          explanation: "An AP converts between radio signals and the wired LAN, letting Wi-Fi devices join the network.",
          improved: "A wireless access point bridges wireless devices onto the wired network — it converts Wi-Fi radio signals to Ethernet and back.",
        },
        {
          id: "nb-comp-6", topic: "Firewalls", type: "definition", difficulty: "foundation",
          question: "What is the job of a firewall in a network?",
          accepted: ["to filter traffic and block unauthorized access", "it allows or blocks traffic based on security rules", "controls what traffic can enter or leave the network"],
          required: ["filter traffic"], optional: ["security rules", "block unauthorized"],
          explanation: "A firewall inspects traffic entering and leaving a network and permits or blocks it according to security rules.",
          improved: "A firewall filters traffic between networks, allowing or blocking it based on security rules to keep unauthorized traffic out.",
        },
        {
          id: "nb-comp-7", topic: "NICs", type: "definition", difficulty: "foundation",
          question: "What component gives a computer its physical connection to the network, and what unique address does it carry?",
          accepted: ["the network interface card, which has a mac address", "a nic with its mac address", "network interface card and mac address"],
          required: ["network interface card", "mac address"],
          explanation: "The NIC (wired or wireless) is the hardware interface to the network; each NIC has a burned-in MAC address used at Layer 2.",
          improved: "The network interface card (NIC) connects the computer to the network, and each NIC carries a unique MAC address.",
        },
        {
          id: "nb-comp-8", topic: "Routers", type: "troubleshooting", difficulty: "applied",
          question: "Devices on an office LAN can reach each other but nothing outside the office. Which device's role has most likely failed?",
          accepted: ["the router", "router or default gateway", "the default gateway router"],
          required: ["router"], optional: ["default gateway"],
          mistakes: ["Blaming the switch — local traffic working means switching is fine."],
          explanation: "Local communication uses the switch; anything leaving the network goes through the router (default gateway). Internal-only connectivity points at the router or its WAN link.",
          improved: "The router (default gateway) — local switching clearly works, so the failure is where traffic leaves the network: the router or its internet connection.",
        },
        {
          id: "nb-comp-9", topic: "Switches", type: "comparison", difficulty: "applied",
          question: "Why did switches replace hubs in wired networks?",
          accepted: ["switches forward frames only to the destination port instead of repeating to everyone, so no collisions and better performance", "hubs broadcast to all ports, switches send only where needed"],
          required: ["only to the destination"], optional: ["collisions", "bandwidth", "hubs repeat to all ports"],
          explanation: "Hubs repeat every bit to every port, wasting bandwidth and causing collisions. Switches learn MAC addresses and deliver frames only to the right port.",
          improved: "A hub blindly repeats traffic to every port, causing collisions and wasted bandwidth. A switch learns MAC addresses and forwards each frame only to its destination port, giving every device dedicated bandwidth.",
        },
        {
          id: "nb-comp-10", topic: "Access Points", type: "device_identification", difficulty: "applied",
          question: "A home 'Wi-Fi router' combines several devices in one box. Name at least three functions inside it.",
          accepted: ["router, switch, and wireless access point", "routing, switching, access point, and often a firewall and dhcp server"],
          required: ["router", "switch", "access point"], optional: ["firewall", "dhcp server"],
          explanation: "Home gateways bundle a router, a small Ethernet switch, a wireless AP, and usually a firewall and DHCP/DNS services.",
          improved: "A home Wi-Fi router combines a router, a small Ethernet switch, and a wireless access point — plus usually a firewall and a DHCP server.",
        },
        {
          id: "nb-comp-11", topic: "Firewalls", type: "troubleshooting", difficulty: "applied",
          question: "After a new firewall rule was applied, users can browse websites but can no longer send email. What does this suggest about how firewalls work?",
          accepted: ["firewalls filter by port or protocol, and the email ports were blocked", "rules are per service so the email protocol ports are blocked while web ports are allowed"],
          required: ["port"], optional: ["protocol", "per service", "rules"],
          explanation: "Firewalls commonly allow or deny traffic per port/protocol. Web ports (80/443) being open while mail ports (25/465/587) are blocked produces exactly this symptom.",
          improved: "Firewalls filter per port and protocol. Web traffic (443) is allowed but the email ports were caught by the new rule — the rule needs an exception for the mail protocols.",
        },
        {
          id: "nb-comp-12", topic: "End Devices", type: "device_identification", difficulty: "foundation",
          question: "Is a network printer an end device or an intermediary device — and why?",
          accepted: ["an end device because it is a destination for data", "end device, print jobs terminate there"],
          required: ["end device"], optional: ["destination"],
          explanation: "Print jobs end at the printer — it consumes data rather than forwarding it, so it's an end device (host).",
          improved: "An end device: it's the destination where print-job data terminates, not a device that forwards traffic onward.",
        },
      ],
    },
    {
      id: "nb-media",
      title: "Network Media",
      description: "Copper, fibre-optic, Ethernet, and wireless transmission.",
      topics: ["Copper Cabling", "Fibre Optics", "Ethernet", "Wireless"],
      questions: [
        {
          id: "nb-med-1", topic: "Copper Cabling", type: "definition", difficulty: "foundation",
          question: "What do copper network cables use to carry data?",
          accepted: ["electrical signals", "electrical pulses", "electricity"],
          required: ["electrical"],
          explanation: "Copper cabling (like twisted-pair Ethernet cable) encodes data as electrical signals.",
          improved: "Copper cables carry data as electrical signals — voltage changes represent the bits.",
        },
        {
          id: "nb-med-2", topic: "Fibre Optics", type: "definition", difficulty: "foundation",
          question: "What do fibre-optic cables use to carry data, and what is one advantage over copper?",
          accepted: ["light, and it travels farther with no electrical interference", "pulses of light; higher bandwidth and immune to emi", "light signals, longer distances"],
          required: ["light"], optional: ["longer distance", "immune to interference", "higher bandwidth"],
          explanation: "Fibre carries data as light pulses through glass, giving far longer reach, huge bandwidth, and immunity to electrical interference.",
          improved: "Fibre uses pulses of light through glass strands. Compared with copper it reaches much longer distances, supports higher bandwidth, and is immune to electrical interference.",
        },
        {
          id: "nb-med-3", topic: "Ethernet", type: "definition", difficulty: "foundation",
          question: "What is Ethernet?",
          accepted: ["the standard technology for wired local area networks", "the dominant lan standard defining how frames are sent over cables", "a family of wired networking standards"],
          required: ["wired", "lan"], optional: ["standard", "frames"],
          explanation: "Ethernet is the family of standards (IEEE 802.3) that defines wired LAN communication — connectors, cabling, and frame format.",
          improved: "Ethernet is the standard technology for wired LANs — it defines the cabling, connectors, and frame format devices use to communicate locally.",
        },
        {
          id: "nb-med-4", topic: "Wireless", type: "comparison", difficulty: "foundation",
          question: "Name one advantage and one disadvantage of wireless compared with wired connections.",
          accepted: ["mobility but more interference", "convenient and mobile, but less reliable and slower than cable", "no cables needed but signal can be weak or interfered with"],
          required: ["mobility"], optional: ["interference", "less reliable", "security", "slower"],
          explanation: "Wireless gives mobility and easy installation, but is more exposed to interference, distance limits, congestion, and eavesdropping than cable.",
          improved: "Advantage: mobility — devices connect anywhere in range without cabling. Disadvantage: radio is shared and prone to interference, so it's typically less consistent than a wired link.",
        },
        {
          id: "nb-med-5", topic: "Copper Cabling", type: "device_identification", difficulty: "foundation",
          question: "What connector is on the end of a standard Ethernet twisted-pair cable?",
          accepted: ["rj45", "an rj45 connector", "rj-45"],
          required: ["rj45"],
          explanation: "Twisted-pair Ethernet cables terminate in RJ45 connectors — the familiar clip-in plug.",
          improved: "An RJ45 connector — the 8-pin clip plug used for twisted-pair Ethernet.",
        },
        {
          id: "nb-med-6", topic: "Wireless", type: "troubleshooting", difficulty: "applied",
          question: "Wi-Fi in a meeting room is fine, but two rooms away it constantly drops. What physical factor is the most likely cause?",
          accepted: ["distance and walls weakening the signal", "signal attenuation through walls", "the signal is too weak that far from the access point"],
          required: ["signal"], optional: ["walls", "distance", "attenuation", "interference"],
          explanation: "Radio signals weaken with distance and lose strength passing through walls — coverage, not configuration, is the first suspect.",
          improved: "Signal attenuation: distance plus intervening walls weakens Wi-Fi. The fix is usually another access point or repositioning, not settings changes.",
        },
        {
          id: "nb-med-7", topic: "Fibre Optics", type: "comparison", difficulty: "applied",
          question: "A company must link two buildings 800 metres apart. Why is fibre a better choice than copper Ethernet cable?",
          accepted: ["copper ethernet is limited to about 100 metres while fibre spans kilometres", "fibre supports long distances, copper maxes out around 100m"],
          required: ["100", "distance"], optional: ["fibre spans kilometres", "interference"],
          mistakes: ["Suggesting a longer copper run — standard twisted-pair Ethernet fails past ~100 m."],
          explanation: "Twisted-pair Ethernet is specified to about 100 m per run; fibre easily covers hundreds of metres to kilometres and resists outdoor electrical interference.",
          improved: "Copper Ethernet is limited to roughly 100 metres per run, so 800 m is far out of spec. Fibre covers that distance easily, with immunity to electrical interference between buildings.",
        },
        {
          id: "nb-med-8", topic: "Ethernet", type: "definition", difficulty: "applied",
          question: "Your laptop shows a '1 Gbps' wired connection. What does that number describe?",
          accepted: ["the bandwidth or speed of the link, one gigabit per second", "how many bits per second the link can carry", "the link speed"],
          required: ["bandwidth"], optional: ["bits per second", "link speed"],
          explanation: "Link speed is bandwidth — the maximum data rate of the connection, here one billion bits per second.",
          improved: "It's the link bandwidth: the connection can carry up to one gigabit (one billion bits) per second between the laptop and switch.",
        },
      ],
    },
    {
      id: "nb-protocols",
      title: "Protocols & Addressing",
      description: "Protocols, IP and MAC addresses, TCP/UDP, DNS, DHCP, and default gateways.",
      topics: ["Protocols", "IP Addresses", "MAC Addresses", "TCP & UDP", "DNS", "DHCP", "Default Gateway"],
      questions: [
        {
          id: "nb-pro-1", topic: "Protocols", type: "definition", difficulty: "foundation",
          question: "In networking, what is a protocol?",
          accepted: ["a set of rules that governs how devices communicate", "agreed rules for communication between devices", "rules both sides follow to exchange data"],
          required: ["rules"], optional: ["communication", "agreed"],
          explanation: "Protocols are agreed rules — message formats, order, and error handling — that let different devices understand each other.",
          improved: "A protocol is a set of agreed rules that governs how devices format, send, and receive messages so both sides understand each other.",
        },
        {
          id: "nb-pro-2", topic: "IP Addresses", type: "definition", difficulty: "foundation",
          question: "What is the purpose of an IP address?",
          accepted: ["to uniquely identify a device on a network so data can reach it", "a logical address used to locate and deliver data to a device", "identifies a host on the network"],
          required: ["identify"], optional: ["device", "logical address", "deliver data"],
          explanation: "An IP address is a logical address identifying a device's location on a network so packets can be routed to it.",
          improved: "An IP address uniquely identifies a device on a network so packets can be addressed and routed to it — like a postal address for data.",
        },
        {
          id: "nb-pro-3", topic: "MAC Addresses", type: "comparison", difficulty: "applied",
          question: "A device has both a MAC address and an IP address. What is each one for?",
          accepted: ["mac identifies the hardware on the local network, ip identifies the device logically for routing between networks", "mac is the physical address used locally, ip is the logical address used end to end"],
          required: ["mac", "local", "ip", "routing"], optional: ["physical", "logical", "end to end"],
          mistakes: ["Saying they're interchangeable — MAC never leaves the local segment; IP travels end to end."],
          explanation: "The MAC address delivers frames on the local link (Layer 2); the IP address identifies the device across networks so routers can deliver packets end to end (Layer 3).",
          improved: "The MAC address is the physical hardware address used to deliver frames within the local network; the IP address is the logical address routers use to deliver packets between networks, end to end.",
        },
        {
          id: "nb-pro-4", topic: "TCP & UDP", type: "comparison", difficulty: "foundation",
          question: "Which transport protocol confirms delivery and retransmits lost data — TCP or UDP?",
          accepted: ["tcp", "transmission control protocol"],
          required: ["tcp"],
          explanation: "TCP acknowledges received data and retransmits anything lost; UDP just sends without guarantees.",
          improved: "TCP — it tracks and acknowledges every segment and retransmits anything that gets lost, unlike UDP.",
        },
        {
          id: "nb-pro-5", topic: "TCP & UDP", type: "comparison", difficulty: "applied",
          question: "Why do live video calls typically run over UDP rather than TCP?",
          accepted: ["low latency matters more than retransmitting lost packets", "udp avoids retransmission delays, a lost frame is better than a late one", "udp is faster with less overhead which suits real time media"],
          required: ["latency"], optional: ["retransmission", "real time", "overhead"],
          explanation: "In real-time media a retransmitted packet arrives too late to be useful; UDP's low overhead and no-retransmit behaviour keeps the stream flowing smoothly.",
          improved: "Real-time audio and video care about latency, not perfection: a retransmitted packet would arrive too late to play. UDP skips acknowledgements and retransmission, keeping delay minimal.",
        },
        {
          id: "nb-pro-6", topic: "DNS", type: "definition", difficulty: "foundation",
          question: "What does DNS do when you type a website name into your browser?",
          accepted: ["translates the domain name into an ip address", "looks up the ip address for the name", "resolves the name to an ip"],
          required: ["ip address"], optional: ["translates", "resolves", "domain name"],
          explanation: "DNS resolves human-readable names into the IP addresses computers actually connect to.",
          improved: "DNS looks up the domain name and returns its IP address, so your browser knows which server to connect to.",
        },
        {
          id: "nb-pro-7", topic: "DHCP", type: "definition", difficulty: "foundation",
          question: "What service means you don't have to type an IP address into every new device that joins a network?",
          accepted: ["dhcp", "dynamic host configuration protocol", "dhcp assigns addresses automatically"],
          required: ["dhcp"],
          explanation: "DHCP automatically leases IP addresses (plus subnet mask, gateway, and DNS servers) to devices joining the network.",
          improved: "DHCP — the Dynamic Host Configuration Protocol automatically assigns each joining device an IP address, subnet mask, default gateway, and DNS servers.",
        },
        {
          id: "nb-pro-8", topic: "Default Gateway", type: "definition", difficulty: "foundation",
          question: "What is a default gateway?",
          accepted: ["the router a device sends traffic to when the destination is outside its local network", "the exit point from the local network, usually the router ip", "where traffic goes to leave the lan"],
          required: ["router", "outside"], optional: ["local network", "exit"],
          explanation: "The default gateway is the local router's address — the door a device uses for any destination not on its own network.",
          improved: "The default gateway is the router interface a device sends packets to whenever the destination lies outside its own local network.",
        },
        {
          id: "nb-pro-9", topic: "IP Addresses", type: "definition", difficulty: "applied",
          question: "192.168.1.25 with mask 255.255.255.0 — which part of the address identifies the network?",
          accepted: ["192.168.1 is the network portion", "the first three octets 192.168.1", "192.168.1.0 is the network"],
          required: ["192.168.1"],
          explanation: "A 255.255.255.0 mask marks the first three octets as network bits, so 192.168.1 is the network and .25 is the host.",
          improved: "With mask 255.255.255.0 the first three octets — 192.168.1 — are the network portion, and .25 identifies the host within it.",
        },
        {
          id: "nb-pro-10", topic: "DHCP", type: "troubleshooting", difficulty: "applied",
          question: "A laptop shows the address 169.254.7.100 and can't reach anything. What happened?",
          accepted: ["dhcp failed so the laptop gave itself an apipa address", "it never received a dhcp lease and self assigned a 169.254 address", "no dhcp server responded"],
          required: ["dhcp"], optional: ["apipa", "self assigned", "no lease"],
          mistakes: ["Treating 169.254.x.x as a normal address — it always signals DHCP failure."],
          explanation: "169.254.x.x is APIPA — the address a device invents when no DHCP server answers. It signals a DHCP or connectivity problem, not a working configuration.",
          improved: "The laptop failed to get a DHCP lease and self-assigned an APIPA (169.254.x.x) address. Check the DHCP server and the link between the laptop and the network.",
        },
        {
          id: "nb-pro-11", topic: "DNS", type: "troubleshooting", difficulty: "applied",
          question: "Ping to 8.8.8.8 succeeds but ping to google.com fails with 'unknown host'. What service is broken?",
          accepted: ["dns", "name resolution", "the dns server"],
          required: ["dns"],
          explanation: "IP connectivity works; only the name-to-address lookup is failing — that's DNS.",
          improved: "DNS: raw IP connectivity is fine, so the failure to resolve 'google.com' means the configured DNS server is unreachable or misconfigured.",
        },
        {
          id: "nb-pro-12", topic: "Protocols", type: "definition", difficulty: "applied",
          question: "HTTP, HTTPS, and FTP are all examples of protocols at which conceptual level — moving raw bits, delivering packets, or defining application conversations?",
          accepted: ["application conversations", "they are application layer protocols", "application level"],
          required: ["application"],
          explanation: "These protocols define how specific applications talk — web browsing and file transfer — sitting on top of transport and network layers.",
          improved: "They define application conversations: HTTP/HTTPS for the web and FTP for file transfer are application-layer protocols riding on TCP.",
        },
        {
          id: "nb-pro-13", topic: "Default Gateway", type: "troubleshooting", difficulty: "applied",
          question: "A PC can print to the office printer but cannot reach any website. Its IP and DNS look fine. What single misconfiguration would explain this?",
          accepted: ["a wrong or missing default gateway", "the default gateway is misconfigured", "no default gateway set"],
          required: ["default gateway"],
          explanation: "Local traffic (printer) needs no gateway; anything beyond the LAN does. Working-local/broken-remote strongly implies a gateway misconfiguration.",
          improved: "A wrong or missing default gateway: local LAN traffic to the printer doesn't need it, but every packet leaving the network does.",
        },
        {
          id: "nb-pro-14", topic: "MAC Addresses", type: "definition", difficulty: "foundation",
          question: "Roughly what does a MAC address look like, and where does it come from?",
          accepted: ["twelve hex digits like aa bb cc dd ee ff, burned into the nic by the manufacturer", "a 48 bit hexadecimal address assigned by the hardware manufacturer"],
          required: ["hexadecimal"], optional: ["48 bit", "manufacturer", "nic"],
          explanation: "MAC addresses are 48-bit values written as six pairs of hex digits, assigned to the NIC by its manufacturer.",
          improved: "A MAC address is a 48-bit value written as six hex pairs (e.g. 3C:52:82:1A:B4:07), assigned to the network card by its manufacturer.",
        },
      ],
    },
    {
      id: "nb-dataflow",
      title: "How Data Travels",
      description: "Packets, frames, encapsulation, and the journey of data through a network.",
      topics: ["Packets & Frames", "Encapsulation", "Data Flow"],
      questions: [
        {
          id: "nb-df-1", topic: "Packets & Frames", type: "definition", difficulty: "foundation",
          question: "Why is data broken into packets instead of being sent as one continuous stream?",
          accepted: ["so the network can share capacity and recover from errors by resending small pieces", "packets let many conversations share links and lost pieces can be resent individually", "smaller units are easier to route, share bandwidth, and retransmit"],
          required: ["share"], optional: ["resend", "smaller pieces", "routing"],
          explanation: "Packetizing lets many conversations interleave on shared links, allows different paths, and means only small lost pieces need retransmitting.",
          improved: "Breaking data into packets lets thousands of conversations share the same links fairly, allows each piece to take the best route, and means only a small piece needs resending if something is lost.",
        },
        {
          id: "nb-df-2", topic: "Packets & Frames", type: "comparison", difficulty: "applied",
          question: "What is the difference between a packet and a frame?",
          accepted: ["a packet is the layer 3 unit with ip addresses, a frame is the layer 2 wrapper with mac addresses for the local link", "frames carry packets across one link, packets travel end to end"],
          required: ["packet", "frame", "mac"], optional: ["ip addresses", "local link", "layer 2", "layer 3"],
          explanation: "A packet (IP header + data) travels end to end; at each hop it's wrapped in a fresh frame (with MAC addresses) valid only for that local link.",
          improved: "A packet is the Layer 3 unit carrying IP addresses end to end. A frame is the Layer 2 wrapper with MAC addresses that carries the packet across one local link — it's rebuilt at every hop.",
        },
        {
          id: "nb-df-3", topic: "Encapsulation", type: "definition", difficulty: "applied",
          question: "What does 'encapsulation' mean when a device sends data?",
          accepted: ["each layer wraps the data with its own header before transmission", "data is wrapped in headers layer by layer, like nesting envelopes", "adding protocol headers around the data at each layer"],
          required: ["header"], optional: ["each layer", "wraps"],
          explanation: "As data descends the protocol stack, each layer prepends its header (TCP, then IP, then Ethernet) — like an envelope inside an envelope.",
          improved: "Encapsulation is each protocol layer wrapping the data with its own header — application data gets a TCP header, then an IP header, then an Ethernet frame — like nested envelopes.",
        },
        {
          id: "nb-df-4", topic: "Data Flow", type: "packet_journey", difficulty: "applied",
          question: "You load a webpage from a server in another country. Describe, in order, the main devices your request passes through after leaving your laptop on Wi-Fi.",
          accepted: ["the access point, then the local router, then isp routers across the internet, then the server's network and the server", "wireless ap, home router, many internet routers, destination firewall or router, the web server"],
          required: ["access point", "router", "server"], optional: ["isp", "internet routers", "firewall"],
          explanation: "The frame goes to the AP, onto the LAN, out via your router/gateway, hop-by-hop across ISP and backbone routers, then into the destination network to the server.",
          improved: "Laptop → wireless access point → your router (default gateway) → a chain of ISP and internet backbone routers → the destination network's router/firewall → the web server.",
        },
        {
          id: "nb-df-5", topic: "Data Flow", type: "packet_journey", difficulty: "applied",
          question: "As a packet crosses five routers, which addresses change at each hop and which stay the same?",
          accepted: ["mac addresses change every hop, ip addresses stay the same end to end", "the frame's source and destination macs are rewritten per link while source and destination ip remain"],
          required: ["mac", "change", "ip", "same"],
          mistakes: ["Thinking the IP addresses are rewritten at each router (that only happens with NAT)."],
          explanation: "Each router strips the old frame and builds a new one, so MAC addresses are per-link. The IP header's source/destination normally stay fixed end to end.",
          improved: "The MAC addresses change at every hop — each router builds a new frame for the next link — while the source and destination IP addresses stay the same end to end (unless NAT rewrites them).",
        },
        {
          id: "nb-df-6", topic: "Packets & Frames", type: "definition", difficulty: "foundation",
          question: "What two pieces of addressing does every IP packet header carry?",
          accepted: ["source and destination ip addresses", "the sender's and receiver's ip addresses"],
          required: ["source", "destination"],
          explanation: "Every IP packet carries the sender's IP and the destination IP so routers know where it's going and hosts know who sent it.",
          improved: "Every IP packet header carries the source IP address (sender) and the destination IP address (receiver).",
        },
        {
          id: "nb-df-7", topic: "Encapsulation", type: "packet_journey", difficulty: "applied",
          question: "When a frame arrives at the destination computer, what happens to all the headers that were added?",
          accepted: ["they are stripped off layer by layer, called de-encapsulation", "each layer removes its header until the application data remains", "de-encapsulation unwraps the headers in reverse"],
          required: ["removed"], optional: ["de-encapsulation", "layer by layer", "reverse"],
          explanation: "De-encapsulation reverses the sending process: Ethernet, IP, and TCP headers are removed in turn until the application receives the original data.",
          improved: "The receiver de-encapsulates: each layer strips its own header — frame, then IP, then TCP — in reverse order until only the original application data remains.",
        },
        {
          id: "nb-df-8", topic: "Data Flow", type: "definition", difficulty: "foundation",
          question: "What does 'bandwidth' measure, and what unit is it usually expressed in?",
          accepted: ["the capacity of a link measured in bits per second", "how much data can flow per second, in bps or mbps", "data rate in bits per second"],
          required: ["bits per second"], optional: ["capacity", "mbps"],
          explanation: "Bandwidth is a link's data-carrying capacity, expressed in bits per second (Kbps, Mbps, Gbps).",
          improved: "Bandwidth measures how much data a link can carry per unit time, expressed in bits per second — commonly Mbps or Gbps.",
        },
      ],
    },
    {
      id: "nb-config-security",
      title: "Basic Configuration, Security & Troubleshooting",
      description: "First-time device setup, simple security habits, and a troubleshooting mindset.",
      topics: ["Device Configuration", "Basic Security", "Troubleshooting"],
      questions: [
        {
          id: "nb-cfg-1", topic: "Device Configuration", type: "configuration_reasoning", difficulty: "foundation",
          question: "What is the first security task when setting up a brand-new router or switch?",
          accepted: ["change the default password", "replace default credentials with strong ones", "set a strong admin password instead of the default"],
          required: ["default password"], optional: ["strong password", "credentials"],
          mistakes: ["Leaving default logins 'until later' — attackers scan for them constantly."],
          explanation: "Default credentials are public knowledge. Changing them immediately is the single most important first step.",
          improved: "Change the default administrator credentials to a strong, unique password immediately — default logins are publicly documented and actively scanned for.",
        },
        {
          id: "nb-cfg-2", topic: "Device Configuration", type: "configuration_reasoning", difficulty: "applied",
          question: "Name three settings a PC needs (manually or from DHCP) to communicate beyond its local network.",
          accepted: ["ip address, subnet mask, and default gateway", "an ip address with subnet mask plus the default gateway, and dns for names"],
          required: ["ip address", "subnet mask", "default gateway"], optional: ["dns server"],
          explanation: "The IP identifies the host, the mask defines the local network, and the gateway is the exit. DNS is needed for name lookups too.",
          improved: "An IP address, a subnet mask, and a default gateway — plus a DNS server address if it should reach things by name.",
        },
        {
          id: "nb-cfg-3", topic: "Basic Security", type: "configuration_reasoning", difficulty: "foundation",
          question: "Why should a home Wi-Fi network use WPA2 or WPA3 instead of being open?",
          accepted: ["encryption stops outsiders reading traffic and joining the network", "it encrypts the wireless traffic and requires authentication", "open wifi lets anyone connect and eavesdrop"],
          required: ["encrypt"], optional: ["authentication", "eavesdrop"],
          explanation: "WPA2/WPA3 encrypt radio traffic and require a key to join; open networks let anyone connect and capture what's sent.",
          improved: "WPA2/WPA3 encrypt all wireless traffic and require authentication to join. On an open network, anyone nearby can connect and eavesdrop on what's transmitted.",
        },
        {
          id: "nb-cfg-4", topic: "Basic Security", type: "definition", difficulty: "foundation",
          question: "What is the point of keeping network devices' firmware updated?",
          accepted: ["updates patch security vulnerabilities and bugs", "to fix known security holes", "patching removes exploitable flaws"],
          required: ["security"], optional: ["patch", "vulnerabilities", "bugs"],
          explanation: "Firmware updates close published vulnerabilities that attackers actively exploit, and fix stability bugs.",
          improved: "Firmware updates patch known security vulnerabilities and bugs — unpatched network devices are a common and easy way in for attackers.",
        },
        {
          id: "nb-cfg-5", topic: "Troubleshooting", type: "troubleshooting", difficulty: "applied",
          question: "'The internet is down!' What is the quickest first check to see whether the problem is one device or the whole network?",
          accepted: ["test from a second device", "check whether other devices are also offline", "see if the problem affects everyone or just one machine"],
          required: ["other devices"], optional: ["scope", "isolate"],
          explanation: "Establishing scope first — one device vs everyone — instantly halves the problem space before touching any settings.",
          improved: "Test from another device: if others work, the problem is local to that machine; if everything is down, look at shared infrastructure like the router or ISP link.",
        },
        {
          id: "nb-cfg-6", topic: "Troubleshooting", type: "troubleshooting", difficulty: "applied",
          question: "Why is 'ping' usually the first command a technician runs when testing connectivity?",
          accepted: ["it quickly confirms whether a device is reachable", "it tests basic reachability and shows response time", "a fast yes or no on connectivity plus latency"],
          required: ["reachab"], optional: ["response time", "icmp", "quick test"],
          explanation: "Ping sends a tiny echo request and reports replies and round-trip time — a fast, low-effort reachability test that guides everything after it.",
          improved: "Ping gives an immediate yes/no on whether a destination is reachable, plus round-trip time — a few seconds of testing that instantly narrows where the fault lies.",
        },
        {
          id: "nb-cfg-7", topic: "Troubleshooting", type: "troubleshooting", difficulty: "applied",
          question: "A user's cable is plugged in but the switch port's link light is off. What does that tell you, and what would you try first?",
          accepted: ["no physical link, so try a different cable or port", "layer 1 problem, reseat or replace the cable, test another port", "the physical connection failed, check cable and port"],
          required: ["cable"], optional: ["physical", "port", "layer 1", "replace"],
          explanation: "No link light means no electrical connection — a Layer 1 issue. Reseat/replace the cable and try another port before touching software.",
          improved: "A dark link light means the physical layer isn't working. Reseat the cable, then swap it, then try another switch port — no software setting matters until the light comes on.",
        },
        {
          id: "nb-cfg-8", topic: "Basic Security", type: "definition", difficulty: "applied",
          question: "Why does a business Wi-Fi setup usually have a separate guest network?",
          accepted: ["to keep visitor devices isolated from internal systems", "guests get internet without access to company resources", "it separates untrusted devices from the internal network"],
          required: ["separate"], optional: ["guests", "internal", "isolated"],
          explanation: "Guest devices are untrusted and unmanaged; isolating them protects internal servers and machines while still offering internet access.",
          improved: "A guest network isolates untrusted visitor devices: they get internet access but can't reach internal servers, printers, or employee machines.",
        },
      ],
    },
  ],
});
