import { defineCourse } from "./builder";

/** Vendor-neutral cloud networking concepts, sourced from official AWS,
 *  Azure, and Google Cloud documentation. Provider product names are used
 *  as examples, never as the thing being memorised. */
export const cloudHybridNetworking = defineCourse({
  id: "cloud-hybrid-networking",
  title: "Cloud and Hybrid Networking",
  description:
    "Virtual networks, cloud subnets and routing, security groups, load balancing, hybrid connectivity, and high availability — concepts that transfer across AWS, Azure, and Google Cloud.",
  icon: "☁️",
  disclaimer:
    "Independently created practice based on public AWS, Azure, and Google Cloud documentation. Not endorsed by any provider.",
  modules: [
    {
      id: "cloud-virtual-networks",
      title: "Virtual Networks & Cloud Subnets",
      description: "VPCs/VNets, cloud subnets, route tables, and cloud DNS.",
      topics: ["Virtual Networks", "Cloud Subnets", "Route Tables", "Cloud DNS"],
      questions: [
        {
          id: "cl-vn-1", topic: "Virtual Networks", type: "definition", difficulty: "foundation",
          question: "What is a virtual private cloud (VPC or VNet), in one sentence?",
          accepted: ["a logically isolated virtual network inside a cloud provider where you launch your resources", "your own private network segment in the cloud with your own ip ranges"],
          required: ["isolated", "network"], optional: ["your own ip range", "cloud", "resources"],
          synonyms: ["vnet", "virtual network"],
          explanation: "A VPC (AWS/GCP) or VNet (Azure) is a logically isolated virtual network in the provider's cloud — your own address space, subnets, and routing, resembling a traditional network you'd run yourself.",
          improved: "A virtual private cloud is a logically isolated virtual network within a cloud provider, with its own IP address range, subnets, and routing, where you deploy your cloud resources.",
        },
        {
          id: "cl-vn-2", topic: "Cloud Subnets", type: "comparison", difficulty: "applied",
          question: "In cloud networks, what is the practical difference between a public subnet and a private subnet?",
          accepted: ["a public subnet has a route to an internet gateway so resources can be reached from the internet, a private subnet does not", "public subnets route to the internet, private subnets are internal only"],
          required: ["internet"], optional: ["route", "internet gateway", "internal only"],
          contradicts: ["public means anyone can log in without credentials"],
          explanation: "The difference is routing: a public subnet's route table points to an internet gateway, so resources there can have public reachability. Private subnets have no such route — internal only, often reaching out via NAT.",
          improved: "A public subnet has a route to the internet gateway, so its resources can be internet-reachable; a private subnet has no internet route — its resources are internal-only and typically reach out through a NAT gateway.",
        },
        {
          id: "cl-vn-3", topic: "Route Tables", type: "definition", difficulty: "applied",
          question: "What does a cloud route table control, and what happens to traffic with no matching route?",
          accepted: ["it decides where each subnet's traffic is sent based on destination, unmatched traffic is dropped", "routing decisions per subnet, no route means the traffic goes nowhere"],
          required: ["where traffic"], optional: ["destination", "dropped", "per subnet"],
          explanation: "Route tables map destination ranges to targets (local, internet gateway, VPN, peering). Traffic that matches no route is dropped — the classic cause of 'cloud VM can't reach X'.",
          improved: "A route table decides where traffic from a subnet is forwarded, matching each packet's destination against routes (local, internet gateway, VPN, peering). Traffic with no matching route is simply dropped.",
        },
        {
          id: "cl-vn-4", topic: "Virtual Networks", type: "troubleshooting", difficulty: "scenario",
          question: "A company creates two cloud virtual networks and is surprised the VMs in them can't communicate. Why not, and what are two standard fixes?",
          accepted: ["virtual networks are isolated by default, connect them with peering or a vpn gateway", "no connectivity exists until you create vnet peering or a gateway between them"],
          required: ["isolated", "peering"], optional: ["by default", "vpn gateway", "connect"],
          explanation: "Isolation is the point of a VPC — networks don't see each other until explicitly connected: VPC/VNet peering (simplest) or gateways/transit hubs for larger topologies.",
          improved: "Virtual networks are isolated by default — that's their purpose. To connect them, set up VPC/VNet peering between the two networks, or route between them through a VPN/transit gateway for larger multi-network designs.",
        },
        {
          id: "cl-vn-5", topic: "Cloud DNS", type: "definition", difficulty: "applied",
          question: "Why do cloud providers run internal DNS inside a virtual network, and what does it typically resolve?",
          accepted: ["so resources can find each other by name, resolving internal hostnames to private ips", "automatic name resolution for cloud resources within the network"],
          required: ["name"], optional: ["private ip", "internal", "resources find each other"],
          explanation: "Cloud-internal DNS auto-registers resources so services find each other by stable names rather than ever-changing private IPs — essential when instances are replaced constantly.",
          improved: "Cloud internal DNS lets resources find each other by stable names, resolving internal hostnames to private IPs automatically — vital because cloud instances come and go, and their IPs change.",
        },
        {
          id: "cl-vn-6", topic: "Cloud Subnets", type: "configuration_reasoning", difficulty: "applied",
          question: "Why should you plan a cloud network's IP address ranges carefully BEFORE connecting it to your on-premises network?",
          accepted: ["overlapping ranges with on premises networks break routing and can't easily be changed later", "address overlap prevents hybrid connectivity, ranges are hard to change after deployment"],
          required: ["overlap"], optional: ["on premises", "routing", "hard to change"],
          explanation: "Hybrid routing requires non-overlapping address space. Overlaps make destinations ambiguous, and re-addressing a live cloud network later is painful.",
          improved: "Because hybrid connectivity requires non-overlapping address space: if the cloud network's range overlaps the office's, routers can't tell which side owns an address. Re-addressing a deployed network later is disruptive, so plan ranges up front.",
        },
        {
          id: "cl-vn-7", topic: "Virtual Networks", type: "explain_simply", difficulty: "scenario",
          question: "Explain to a non-technical manager why 'moving to the cloud' still involves network design.",
          accepted: ["the cloud gives you an empty virtual network you must design, addressing, subnets, security and connections still have to be planned", "you rent the building but still design the floor plan, rooms, doors and locks"],
          required: ["design"], optional: ["subnets", "security", "addressing", "floor plan", "still your responsibility"],
          explanation: "Cloud removes the hardware, not the design: address plans, subnet layout, routing, security boundaries, and the connection back to the office all still need deliberate decisions.",
          improved: "The cloud rents you the building, but you still design the floor plan: which sections (subnets) exist, how rooms connect (routing), where the locked doors go (security), and how it links to your office. Skipping that design is how cloud projects become insecure or unreachable.",
        },
        {
          id: "cl-vn-8", topic: "Route Tables", type: "troubleshooting", difficulty: "scenario",
          question: "A cloud VM in a private subnet must download OS updates but has no internet access. What component gives outbound-only internet access without exposing the VM?",
          accepted: ["a nat gateway", "nat gateway or nat instance for outbound only connectivity"],
          required: ["nat"], optional: ["outbound only", "gateway", "not exposed"],
          explanation: "A NAT gateway in a public subnet lets private-subnet resources initiate outbound connections while remaining unreachable from the internet.",
          improved: "A NAT gateway: the private subnet's route table sends internet-bound traffic to it, giving VMs outbound access for updates while they stay unreachable from the internet — no inbound exposure.",
        },
      ],
    },
    {
      id: "cloud-security-delivery",
      title: "Cloud Security & Traffic Delivery",
      description: "Security groups, network security groups, load balancers, and endpoints.",
      topics: ["Security Groups", "Load Balancers", "Endpoints", "Cloud Firewalls"],
      questions: [
        {
          id: "cl-sd-1", topic: "Security Groups", type: "definition", difficulty: "foundation",
          question: "What does a cloud security group (or network security group) do?",
          accepted: ["it acts as a virtual firewall controlling what traffic may reach or leave a resource", "allow rules for inbound and outbound traffic on cloud resources"],
          required: ["firewall"], optional: ["inbound", "outbound", "rules", "virtual"],
          synonyms: ["nsg", "network security group"],
          explanation: "Security groups are per-resource virtual firewalls: rule sets defining allowed inbound/outbound traffic by port, protocol, and source/destination.",
          improved: "A security group is a virtual firewall attached to cloud resources, with rules defining which inbound and outbound traffic is allowed by port, protocol, and source or destination.",
        },
        {
          id: "cl-sd-2", topic: "Security Groups", type: "troubleshooting", difficulty: "scenario",
          question: "A web VM is running, its subnet routing is correct, but browsers can't reach it. As a cloud-side cause, what should you check first?",
          accepted: ["the security group inbound rules, port 443 or 80 probably isn't allowed", "whether the security group allows inbound web traffic"],
          required: ["security group"], optional: ["inbound", "443", "80", "allow rule"],
          explanation: "With compute and routing healthy, the classic culprit is the security group missing an inbound allow for web ports — deny-by-default does its job.",
          improved: "Check the security group's inbound rules: cloud firewalls deny by default, so unless a rule explicitly allows inbound 80/443 from the internet, the VM is unreachable no matter how healthy it is.",
        },
        {
          id: "cl-sd-3", topic: "Load Balancers", type: "definition", difficulty: "applied",
          question: "What two problems does a cloud load balancer solve for a busy application?",
          accepted: ["it spreads traffic across multiple servers and removes failed servers from rotation", "scale by distributing requests, availability by health checking instances"],
          required: ["distribut"], optional: ["health check", "failed", "multiple servers", "availability"],
          explanation: "Load balancers spread requests across instances (scale) and health-check them, routing around failures (availability).",
          improved: "Scale — it distributes incoming requests across multiple servers so no single one is overwhelmed — and availability — it health-checks those servers and stops sending traffic to any that fail.",
        },
        {
          id: "cl-sd-4", topic: "Endpoints", type: "comparison", difficulty: "applied",
          question: "Why would a company use a private endpoint to reach a cloud storage service instead of its public endpoint?",
          accepted: ["traffic stays on the private network instead of crossing the internet, reducing exposure", "private endpoints keep the connection internal, no public internet path to the data"],
          required: ["private"], optional: ["not over the internet", "exposure", "internal"],
          explanation: "Private endpoints put the service on your virtual network's address space, so data-path traffic never touches the public internet — smaller attack surface, simpler compliance.",
          improved: "A private endpoint gives the service an address inside your own virtual network, so traffic to it never crosses the public internet — reducing exposure and satisfying policies requiring internal data paths.",
        },
        {
          id: "cl-sd-5", topic: "Cloud Firewalls", type: "architecture_reasoning", difficulty: "scenario",
          question: "Security groups already filter per-resource. Why do organisations still deploy a managed cloud firewall at the network's edge?",
          accepted: ["centralized inspection and policy across all traffic, features like ids and domain filtering beyond per resource port rules", "a central chokepoint with advanced inspection, uniform egress control and logging"],
          required: ["central"], optional: ["inspection", "egress", "logging", "advanced"],
          explanation: "Security groups are distributed port filters; a managed firewall adds centralized policy, deep inspection, domain/URL filtering, and uniform egress control with full logging.",
          improved: "Security groups filter ports per resource, but a central cloud firewall adds what they can't: organisation-wide policy in one place, deep traffic inspection, domain-based egress filtering, and unified logging of everything entering and leaving the network.",
        },
        {
          id: "cl-sd-6", topic: "Load Balancers", type: "troubleshooting", difficulty: "scenario",
          question: "After deploying behind a load balancer, half of a customer's requests fail. The LB shows one of two backend servers 'unhealthy'. What is the LB doing, and where does the real problem live?",
          accepted: ["the lb is failing health checks on one server and should remove it, the problem is on that backend server", "health checks flag the bad backend, investigate that server not the load balancer"],
          required: ["health"], optional: ["backend", "remove from rotation", "that server"],
          explanation: "Health checks are working as designed — the failing backend is the issue. (If failures still reach users, the LB may be configured to keep routing to unhealthy targets or the check itself is misconfigured.)",
          improved: "The load balancer's health checks have detected the bad backend — that's the system working. The real problem is on that server (crashed app, wrong port, its own firewall). Fix the backend; also confirm the LB is actually removing unhealthy targets from rotation.",
        },
        {
          id: "cl-sd-7", topic: "Security Groups", type: "configuration_reasoning", difficulty: "applied",
          question: "A teammate proposes allowing inbound SSH from 0.0.0.0/0 'temporarily' to debug a cloud VM. What's wrong, and what's the safer pattern?",
          accepted: ["that opens ssh to the whole internet inviting brute force, restrict to specific source ips or use a bastion or identity based access", "never expose ssh globally, allow only your ip or use the provider's session access"],
          required: ["internet"], optional: ["brute force", "specific ip", "bastion", "temporary becomes permanent"],
          explanation: "0.0.0.0/0 on SSH = whole-internet exposure, scanned within minutes; 'temporary' rules calcify. Restrict source to known IPs, or better, use a bastion / provider session access with no open port.",
          improved: "0.0.0.0/0 opens SSH to the entire internet — it will be found and brute-forced within minutes, and temporary rules have a way of becoming permanent. Allow only the specific admin IPs, or skip open ports entirely using a bastion host or the provider's identity-based session access.",
        },
        {
          id: "cl-sd-8", topic: "Endpoints", type: "business_value", difficulty: "scenario",
          question: "Translate 'we implemented private endpoints for the database' into a sentence a compliance officer cares about.",
          accepted: ["customer data now never crosses the public internet between our systems", "the database is reachable only from inside our network, no public exposure to audit"],
          required: ["internet"], optional: ["never crosses", "internal only", "exposure", "audit"],
          explanation: "For compliance, the claim that matters is the data path: no public internet transit, no public attack surface — simpler audits and clear alignment with data-protection requirements.",
          improved: "It means customer data travelling to our database never touches the public internet and the database has no public address at all — a smaller attack surface, and a much simpler answer during audits.",
        },
      ],
    },
    {
      id: "cloud-hybrid-connectivity",
      title: "Hybrid Connectivity & High Availability",
      description: "Site-to-site VPN, dedicated links, regions and availability zones, and resilient design.",
      topics: ["Hybrid Connectivity", "Site-to-Site VPN", "Regions & AZs", "High Availability"],
      questions: [
        {
          id: "cl-hc-1", topic: "Site-to-Site VPN", type: "definition", difficulty: "applied",
          question: "How does a company's on-premises network typically get its first secure connection to its cloud network?",
          accepted: ["a site to site vpn between the office router or firewall and the cloud's vpn gateway", "an encrypted ipsec tunnel from on premises to a cloud vpn gateway"],
          required: ["vpn"], optional: ["site to site", "gateway", "ipsec", "encrypted tunnel"],
          explanation: "The standard entry point is a site-to-site IPsec VPN: office edge device ↔ cloud VPN gateway, tunnelling over the internet.",
          improved: "Through a site-to-site VPN: an encrypted IPsec tunnel between the office's router/firewall and the cloud provider's VPN gateway, carrying private traffic over the public internet.",
        },
        {
          id: "cl-hc-2", topic: "Hybrid Connectivity", type: "comparison", difficulty: "scenario",
          question: "When does a dedicated private connection (like AWS Direct Connect or Azure ExpressRoute) justify its cost over a site-to-site VPN?",
          accepted: ["when the business needs consistent bandwidth and latency or moves large volumes, vpn over internet can't guarantee performance", "for predictable performance, large data transfer, or compliance needs that internet vpn can't meet"],
          required: ["consistent"], optional: ["bandwidth", "latency", "large volumes", "guarantee", "compliance"],
          explanation: "VPNs ride the unpredictable internet. Dedicated links buy guaranteed bandwidth, consistent latency, and a private path — worth it for heavy data movement, latency-sensitive workloads, or strict compliance.",
          improved: "When the internet's unpredictability becomes the problem: heavy ongoing data transfer, latency-sensitive workloads, or compliance requiring private paths. A dedicated link guarantees bandwidth and consistent latency that a VPN over the public internet never can.",
        },
        {
          id: "cl-hc-3", topic: "Regions & AZs", type: "definition", difficulty: "foundation",
          question: "In cloud terms, what is the difference between a region and an availability zone?",
          accepted: ["a region is a geographic area containing multiple availability zones, each zone is one or more independent data centres", "regions are locations like frankfurt, azs are isolated data centres within a region"],
          required: ["region", "zone"], optional: ["geographic", "independent data centres", "isolated", "within"],
          explanation: "A region = geographic location (e.g., Frankfurt); inside it, multiple AZs = physically separate data centre groups with independent power/cooling/networking.",
          improved: "A region is a geographic area (like Frankfurt or Virginia) containing multiple availability zones; each AZ is one or more physically separate data centres with independent power, cooling, and networking, so one zone's failure doesn't take the others.",
        },
        {
          id: "cl-hc-4", topic: "High Availability", type: "architecture_reasoning", difficulty: "scenario",
          question: "A customer runs their entire cloud application in a single availability zone. What risk are they carrying, and what's the standard fix?",
          accepted: ["a zone outage takes everything down, spread the application across multiple azs behind a load balancer", "single zone is a single point of failure, deploy multi az"],
          required: ["zone"], optional: ["outage", "multiple", "load balancer", "single point of failure"],
          explanation: "One AZ = one failure domain; zone outages happen. Multi-AZ deployment behind a load balancer (and multi-AZ data replication) is the baseline HA pattern.",
          improved: "They're one data-centre incident away from total outage — an AZ is a single failure domain. The standard fix: run instances in at least two availability zones behind a load balancer, with the database replicated across zones as well.",
        },
        {
          id: "cl-hc-5", topic: "Hybrid Connectivity", type: "troubleshooting", difficulty: "scenario",
          question: "After a site-to-site VPN comes up, the office can ping cloud VMs but cloud VMs can't reach an on-premises server. The tunnel is healthy. Name two asymmetric causes to check.",
          accepted: ["the on premises firewall blocking inbound from cloud ranges and missing return routes for the cloud network", "office side acls or firewall rules, and routing that doesn't include the cloud address range"],
          required: ["firewall"], optional: ["route", "on premises", "return traffic", "acl", "asymmetric"],
          explanation: "One-way reachability over a healthy tunnel = policy or routing asymmetry: office firewall rules blocking cloud-initiated traffic, or on-prem routers lacking routes for the cloud range.",
          improved: "Check the office firewall — it may allow outbound-initiated traffic but block connections initiated from the cloud ranges — and on-premises routing: internal routers may have no route back for the cloud network's address range, so responses (or inbound connections) never find the tunnel.",
        },
        {
          id: "cl-hc-6", topic: "High Availability", type: "business_value", difficulty: "scenario",
          question: "A CFO asks why running in two availability zones costs more 'for the same app'. Give the business-value answer.",
          accepted: ["the second zone is insurance, a data centre incident becomes a non event instead of an outage costing revenue and reputation", "you're buying survival of a data centre failure, compare the extra cost with the cost of downtime"],
          required: ["outage"], optional: ["insurance", "downtime cost", "revenue", "non event"],
          explanation: "Frame as insurance economics: modest duplicate-capacity cost vs the revenue/reputation cost of a full outage during a zone incident.",
          improved: "The second zone is outage insurance: when a data-centre incident hits — and they do — the app keeps running and customers never notice. Compare that premium with what one multi-hour outage costs in lost revenue and trust; for most businesses the insurance is cheap.",
        },
        {
          id: "cl-hc-7", topic: "Regions & AZs", type: "solution_recommendation", difficulty: "scenario",
          question: "A European customer asks whether to deploy their app in one region or two. What key questions decide it, and what's the honest cost warning?",
          accepted: ["ask about availability requirements, user locations and data residency, multi region roughly doubles cost and adds complexity", "rto and rpo needs, latency to users, compliance, warn that multi region is expensive and complex"],
          required: ["cost"], optional: ["availability", "residency", "latency", "complexity", "requirements"],
          explanation: "Multi-region is for surviving region-scale disasters and serving distant users — but roughly doubles infrastructure and adds real complexity (data replication, failover). Requirements first: RTO/RPO, user geography, residency.",
          improved: "Ask: what downtime can the business tolerate (does a rare region-wide outage justify the spend)? Where are users (latency)? Any data-residency constraints? Then be honest: multi-region roughly doubles infrastructure cost and adds significant complexity in data replication and failover — most businesses are better served going multi-AZ first.",
        },
        {
          id: "cl-hc-8", topic: "Hybrid Connectivity", type: "architecture_reasoning", difficulty: "scenario",
          question: "A company with a VPN to the cloud complains the office loses cloud access whenever their single internet line fails. What resilient design should they consider?",
          accepted: ["redundant internet connections with a second vpn tunnel, or a dedicated link with vpn as backup", "dual wan links and dual tunnels so either path failing keeps cloud connectivity"],
          required: ["redundant"], optional: ["second tunnel", "backup", "dual", "failover"],
          explanation: "One line + one tunnel = one failure domain. Standard: dual internet circuits with dual VPN tunnels (auto-failover), or dedicated link primary with VPN standby.",
          improved: "Redundant paths: a second internet circuit carrying a second VPN tunnel with automatic failover — or, if they've outgrown VPN, a dedicated private link as primary with the VPN as standby. Either way, no single line failure should sever the cloud.",
        },
      ],
    },
  ],
});
