import { defineCourse } from "./builder";

export const hardwareFundamentals = defineCourse({
  id: "hardware-fundamentals",
  title: "Network Devices and Infrastructure",
  description:
    "Recognise the physical building blocks of networks: devices, ports, cabling, power, racks, and where each belongs.",
  icon: "🔌",
  modules: [
    {
      id: "hw-core-devices",
      title: "Core Network Devices",
      description: "Routers, Layer 2/3 switches, wireless access points, and firewalls.",
      topics: ["Routers", "Switches", "Access Points", "Firewalls"],
      questions: [
        {
          id: "hw-dev-1", topic: "Switches", type: "comparison", difficulty: "applied",
          question: "What can a Layer 3 switch do that a Layer 2 switch cannot?",
          accepted: ["route traffic between vlans or subnets", "it can route between networks as well as switch frames", "inter vlan routing"],
          required: ["route"], optional: ["between vlans", "subnets"],
          mistakes: ["Saying L3 switches are just 'faster' — the difference is routing capability."],
          explanation: "A Layer 3 switch adds routing: it can forward packets between VLANs/subnets at hardware speed, not just switch frames within one network.",
          improved: "A Layer 3 switch can route packets between VLANs and subnets (like a router) in addition to Layer 2 frame switching — commonly used for fast inter-VLAN routing in a campus core.",
        },
        {
          id: "hw-dev-2", topic: "Routers", type: "device_identification", difficulty: "foundation",
          question: "Which device typically sits at the edge of an office network, connecting the LAN to the ISP?",
          accepted: ["a router", "the edge router", "router"],
          required: ["router"], optional: ["edge"],
          explanation: "The router is the boundary device: LAN on one side, WAN/ISP link on the other.",
          improved: "A router — often called the edge or gateway router — terminates the ISP connection and routes traffic between the office LAN and the internet.",
        },
        {
          id: "hw-dev-3", topic: "Firewalls", type: "device_identification", difficulty: "applied",
          question: "In a typical small-business design, where does the firewall sit relative to the router and the internal switch?",
          accepted: ["between the router and the internal network", "behind the internet router and in front of the lan switch", "between internet edge and internal switch"],
          required: ["between"], optional: ["router", "switch", "edge"],
          explanation: "The firewall sits inline at the edge — traffic flows internet → router → firewall → internal switch — so every inbound/outbound packet is inspected.",
          improved: "Between the internet router and the internal switch, so all traffic entering or leaving the LAN passes through it and can be filtered.",
        },
        {
          id: "hw-dev-4", topic: "Access Points", type: "troubleshooting", difficulty: "applied",
          question: "If a ceiling-mounted access point fails in an office, what exactly stops working, and what keeps working?",
          accepted: ["wireless clients in that area lose connectivity but wired devices keep working", "wifi coverage in that zone drops, the wired lan is unaffected"],
          required: ["wireless", "wired"], optional: ["coverage area", "unaffected"],
          explanation: "An AP only bridges Wi-Fi clients to the LAN. Its failure kills wireless in its coverage zone; wired devices and other APs are untouched.",
          improved: "Wireless devices in that AP's coverage area lose their connection (or roam to weaker neighbouring APs). All wired devices — and Wi-Fi served by other APs — continue working normally.",
        },
        {
          id: "hw-dev-5", topic: "Switches", type: "device_identification", difficulty: "foundation",
          question: "An office needs to connect 30 wired desktops to the network. What device do they plug into?",
          accepted: ["a switch", "an access switch", "network switch"],
          required: ["switch"], optional: ["access"],
          explanation: "Desktops connect to access-layer switch ports — one cable per desk into the switch.",
          improved: "An access switch — typically a 48-port Layer 2 switch in the wiring closet, with one cable run to each desk.",
        },
        {
          id: "hw-dev-6", topic: "Routers", type: "troubleshooting", difficulty: "scenario",
          question: "The office router has failed. Users report they can still share files with each other but nothing else works. Why does file sharing survive?",
          accepted: ["local traffic goes through the switch and never touches the router", "the lan switch handles internal traffic, only external traffic needs the router"],
          required: ["switch", "local"], optional: ["internal traffic", "external"],
          explanation: "Internal LAN traffic is switched locally; the router is only in the path for traffic leaving the network. Its failure severs external connectivity only.",
          improved: "Internal file sharing rides the LAN switch and never touches the router. The router is only needed for traffic leaving the network — so internet, email, and cloud apps die while local sharing survives.",
        },
        {
          id: "hw-dev-7", topic: "Firewalls", type: "comparison", difficulty: "applied",
          question: "A customer asks why they need a firewall when their router 'already has NAT'. What protection does a real firewall add?",
          accepted: ["stateful inspection, security rules, and often intrusion prevention and content filtering beyond simple nat hiding", "nat is not a security feature, a firewall enforces policy and inspects traffic"],
          required: ["inspect"], optional: ["policy", "stateful", "intrusion prevention", "nat is not security"],
          explanation: "NAT hides addresses as a side effect but enforces no policy. A firewall applies explicit rules, tracks connection state, and modern ones inspect content for threats.",
          improved: "NAT only hides internal addresses — it isn't a security control. A firewall enforces explicit allow/deny policy, tracks connection state, and modern ones add intrusion prevention, malware inspection, and application awareness.",
        },
        {
          id: "hw-dev-8", topic: "Access Points", type: "configuration_reasoning", difficulty: "applied",
          question: "Why are business access points usually powered through their network cable rather than a wall plug?",
          accepted: ["poe delivers power over ethernet so ceiling aps need no outlet nearby", "power over ethernet, one cable carries both data and power"],
          required: ["power over ethernet"], optional: ["poe", "ceiling", "one cable"],
          explanation: "PoE lets the switch inject DC power into the Ethernet run, so APs mount wherever coverage is best — not wherever an outlet happens to be.",
          improved: "They use Power over Ethernet (PoE): the switch supplies power through the data cable, so APs can be ceiling-mounted for best coverage without needing electrical outlets installed.",
        },
        {
          id: "hw-dev-9", topic: "Switches", type: "comparison", difficulty: "applied",
          question: "What is the difference between a managed and an unmanaged switch, and when does managed matter?",
          accepted: ["managed switches can be configured with vlans, monitoring and security, unmanaged are plug and play with no control", "managed offers configuration like vlans and port control, needed in business networks"],
          required: ["configur"], optional: ["vlans", "monitoring", "plug and play"],
          explanation: "Unmanaged switches just forward. Managed switches add VLANs, port security, monitoring, and QoS — essential once you need segmentation or visibility.",
          improved: "An unmanaged switch is plug-and-play with zero configuration. A managed switch supports VLANs, port security, monitoring, and QoS — necessary in any business network that needs segmentation, control, or troubleshooting visibility.",
        },
        {
          id: "hw-dev-10", topic: "Firewalls", type: "troubleshooting", difficulty: "scenario",
          question: "If a company's only firewall loses power and there's no bypass, what happens to internet connectivity, and what does that teach about firewall deployment?",
          accepted: ["all traffic through it stops, so critical firewalls need redundancy or high availability pairs", "internet access dies because the firewall is inline, which is why ha pairs exist"],
          required: ["stops"], optional: ["inline", "redundancy", "high availability"],
          explanation: "An inline firewall is a single point of failure — its outage severs everything through it. Critical edges deploy HA pairs or redundant power.",
          improved: "All traffic through it stops — the firewall is inline, so its failure cuts the site off. That's why critical firewalls are deployed as high-availability pairs with redundant power.",
        },
        {
          id: "hw-dev-11", topic: "Routers", type: "device_identification", difficulty: "applied",
          question: "What device would connect three office subnets (staff, servers, guests) so they can reach each other under policy control?",
          accepted: ["a router or layer 3 switch", "an internal router, often a layer 3 switch, with acls between the subnets"],
          required: ["router"], optional: ["layer 3 switch", "acl"],
          explanation: "Routing between subnets needs a Layer 3 device — a router or L3 switch — where ACLs/policies control which subnets may talk.",
          improved: "A router or Layer 3 switch: it routes between the three subnets, and access control lists on it enforce which networks are allowed to reach which.",
        },
        {
          id: "hw-dev-12", topic: "Access Points", type: "device_identification", difficulty: "applied",
          question: "A warehouse needs Wi-Fi across a large area. Beyond buying several APs, what central component makes many APs manageable as one system?",
          accepted: ["a wireless lan controller or cloud management platform", "a wlc, or controller based or cloud managed wifi"],
          required: ["controller"], optional: ["wireless lan controller", "cloud managed"],
          explanation: "A WLC (hardware or cloud) centrally manages SSIDs, channels, power, and roaming across the AP fleet instead of per-AP configuration.",
          improved: "A wireless LAN controller (or a cloud management platform): it centrally configures SSIDs, radio channels, and power, and coordinates roaming across all the APs.",
        },
      ],
    },
    {
      id: "hw-servers-endpoints",
      title: "Servers, Endpoints & NICs",
      description: "Servers vs endpoints, network interface cards, virtual vs physical machines.",
      topics: ["Servers", "Endpoints", "NICs", "Virtualisation"],
      questions: [
        {
          id: "hw-srv-1", topic: "Servers", type: "comparison", difficulty: "foundation",
          question: "What makes a server different from an ordinary desktop PC?",
          accepted: ["a server provides services to many users and is built for reliability and continuous operation", "servers run services for clients with redundant hardware, desktops serve one user"],
          required: ["provides services"], optional: ["many users", "reliability", "redundant"],
          explanation: "Servers exist to serve others — files, apps, websites — and are engineered for 24/7 operation with redundant power, storage, and cooling.",
          improved: "A server provides services (files, email, applications) to many users simultaneously and is built for continuous operation with redundant power supplies, storage, and remote management — unlike a desktop serving one person.",
        },
        {
          id: "hw-srv-2", topic: "NICs", type: "device_identification", difficulty: "foundation",
          question: "A desktop needs both a wired and a wireless connection option. What two pieces of hardware provide these?",
          accepted: ["an ethernet nic and a wireless nic", "a wired network card and a wifi adapter"],
          required: ["nic"], optional: ["ethernet", "wireless adapter"],
          explanation: "Each connection type needs its own interface: an Ethernet NIC for cable, a wireless NIC/adapter for Wi-Fi.",
          improved: "An Ethernet NIC for the wired connection and a wireless NIC (Wi-Fi adapter) for wireless — each is a separate network interface with its own MAC address.",
        },
        {
          id: "hw-srv-3", topic: "Virtualisation", type: "comparison", difficulty: "applied",
          question: "One physical server runs six virtual machines. Explain what that means and one benefit plus one risk.",
          accepted: ["a hypervisor shares the hardware among six independent virtual servers, saving cost but the host is a single point of failure", "virtualization runs several isolated servers on one box, efficient but hardware failure affects all vms"],
          required: ["virtual", "one physical"], optional: ["hypervisor", "single point of failure", "cost", "isolated"],
          explanation: "A hypervisor divides one machine's CPU/RAM/storage among isolated VMs. It's efficient and flexible — but a host hardware failure takes down every VM on it.",
          improved: "A hypervisor shares the physical server's resources among six isolated virtual servers. Benefit: far better hardware utilisation and easy provisioning. Risk: the host is a single point of failure — if it dies, all six VMs go down together.",
        },
        {
          id: "hw-srv-4", topic: "Endpoints", type: "definition", difficulty: "foundation",
          question: "In IT conversations, what counts as an 'endpoint'? Name three examples.",
          accepted: ["user facing devices like laptops, desktops, phones and tablets", "any end user device such as a pc, smartphone, or printer"],
          required: ["device"], optional: ["laptop", "desktop", "phone", "tablet", "printer", "user"],
          explanation: "Endpoints are the devices where users (or things) meet the network: laptops, desktops, phones, tablets, printers, IoT devices.",
          improved: "Endpoints are the devices at the edge of the network that users and things work on — laptops, desktops, smartphones, tablets, printers, and IoT devices.",
        },
        {
          id: "hw-srv-5", topic: "NICs", type: "troubleshooting", difficulty: "applied",
          question: "A server has two NICs connected to two different switches. What is this design called and what is it for?",
          accepted: ["nic teaming or redundancy, so a nic or switch failure doesn't disconnect the server", "redundant network connections for failover and sometimes extra bandwidth"],
          required: ["redundan"], optional: ["teaming", "failover", "bandwidth"],
          explanation: "NIC teaming/bonding across two switches removes single points of failure — either NIC, cable, or switch can die without dropping the server.",
          improved: "That's NIC teaming (redundant uplinks): if either NIC, cable, or switch fails, the server stays connected through the other path — and teaming can also aggregate bandwidth.",
        },
        {
          id: "hw-srv-6", topic: "Servers", type: "device_identification", difficulty: "applied",
          question: "Name three common roles a server might play on a business network.",
          accepted: ["file server, web server, and email server", "domain controller, database server, dns or dhcp server", "file storage, application hosting, authentication"],
          required: [], optional: ["file server", "web server", "email", "database", "dns", "dhcp", "authentication", "domain controller", "application"],
          explanation: "Typical roles: file/print, web, email, database, DNS/DHCP, authentication (domain controller), and application hosting.",
          improved: "Common roles include file server, web server, email server, database server, DNS/DHCP server, and domain controller for authentication.",
        },
        {
          id: "hw-srv-7", topic: "Virtualisation", type: "comparison", difficulty: "scenario",
          question: "A customer must choose between one powerful physical server per application, or virtualising everything onto two hosts. What trade-offs would you raise?",
          accepted: ["virtualization improves utilization, cost and flexibility but concentrates risk, needing failover between the hosts", "dedicated hardware isolates workloads but wastes capacity, vms are efficient but need redundancy planning"],
          required: ["utilization", "risk"], optional: ["cost", "failover", "flexibility", "isolation"],
          explanation: "Virtualisation wins on cost, utilisation, and agility, but concentrates failure domains — mitigated by clustering the two hosts so VMs fail over.",
          improved: "Virtualisation cuts hardware cost and improves utilisation and provisioning speed, but concentrates many workloads onto few failure points — so the two hosts should be clustered with failover. Dedicated servers isolate workloads but waste capacity and money.",
        },
        {
          id: "hw-srv-8", topic: "Endpoints", type: "troubleshooting", difficulty: "applied",
          question: "One user's desktop lost network connectivity; the wall port works with a test laptop. What hardware on the desktop do you now suspect?",
          accepted: ["the desktop's nic or its patch cable", "the network card or the cable to the wall"],
          required: ["nic"], optional: ["network card", "cable", "driver"],
          explanation: "With the wall port proven good, the fault narrows to the desktop side: its patch cable, NIC hardware, or NIC driver.",
          improved: "The desktop's own patch cable or its NIC (hardware or driver). Swap the patch cable first — it's the cheapest test — then check the NIC and its driver.",
        },
        {
          id: "hw-srv-9", topic: "Servers", type: "device_identification", difficulty: "applied",
          question: "Why do rack servers offer a separate small 'management' network port (like iLO or iDRAC)?",
          accepted: ["out of band management lets admins reach the server even when the os is down", "remote management port works independently of the operating system for console access and power control"],
          required: ["management"], optional: ["out of band", "remote", "even when down"],
          explanation: "Out-of-band management gives console, power, and health access independent of the main OS/NICs — vital when the server hangs or the OS won't boot.",
          improved: "It's an out-of-band management interface: admins can reach the console, power-cycle the machine, and check health remotely even if the operating system has crashed or the main NICs are down.",
        },
        {
          id: "hw-srv-10", topic: "Virtualisation", type: "definition", difficulty: "foundation",
          question: "What is a hypervisor?",
          accepted: ["software that runs and manages virtual machines on physical hardware", "the layer that lets multiple vms share one physical server"],
          required: ["virtual machines"], optional: ["shares hardware", "software layer"],
          explanation: "The hypervisor allocates a physical machine's CPU, memory, and storage among multiple isolated virtual machines.",
          improved: "A hypervisor is the software layer that creates and runs virtual machines, dividing one physical server's CPU, memory, and storage among them while keeping them isolated.",
        },
      ],
    },
    {
      id: "hw-ports",
      title: "Ports & Transceivers",
      description: "Ethernet ports, console ports, and SFP/SFP+ modules.",
      topics: ["Ethernet Ports", "Console Ports", "SFP Transceivers"],
      questions: [
        {
          id: "hw-prt-1", topic: "Console Ports", type: "comparison", difficulty: "applied",
          question: "What is a console port on a switch for, and how is it different from the Ethernet ports?",
          accepted: ["direct management access with a cable even when the network is down, it carries no network traffic", "a serial management port for configuration, not for data like ethernet ports"],
          required: ["management"], optional: ["serial", "no network traffic", "even when the network is down", "configuration"],
          explanation: "The console port gives direct serial management access — configuration and recovery — independent of network state. Ethernet ports carry actual network traffic.",
          improved: "The console port is for direct management: you connect a console cable and configure the switch even when it has no working network config. Ethernet ports carry user data; the console port never does.",
        },
        {
          id: "hw-prt-2", topic: "SFP Transceivers", type: "definition", difficulty: "applied",
          question: "What is an SFP port on a switch, and why is it a socket rather than a fixed connector?",
          accepted: ["a modular slot that accepts different transceivers so you choose fibre or copper, short or long range", "small form factor pluggable, flexibility to pick the media type per uplink"],
          required: ["transceiver"], optional: ["modular", "fibre or copper", "flexibility", "pluggable"],
          explanation: "SFP slots accept pluggable transceiver modules, letting the same switch support copper, multimode, or single-mode fibre at various distances per port.",
          improved: "An SFP port accepts pluggable transceiver modules, so each uplink can be fitted with the right module — copper, short-range multimode fibre, or long-range single-mode — without changing the switch.",
        },
        {
          id: "hw-prt-3", topic: "SFP Transceivers", type: "comparison", difficulty: "applied",
          question: "What is the practical difference between SFP and SFP+ modules?",
          accepted: ["sfp handles 1 gigabit, sfp+ handles 10 gigabit", "sfp+ is the 10g version of the sfp form factor"],
          required: ["10"], optional: ["1 gigabit", "speed"],
          explanation: "Same form factor, different speed class: SFP tops out at 1 Gbps; SFP+ carries 10 Gbps.",
          improved: "SFP modules run at up to 1 Gbps, while SFP+ uses the same physical form factor but carries 10 Gbps — commonly used for switch uplinks.",
        },
        {
          id: "hw-prt-4", topic: "Ethernet Ports", type: "troubleshooting", difficulty: "applied",
          question: "A gigabit-capable PC connects at only 100 Mbps. Name two physical causes worth checking.",
          accepted: ["a damaged or older cable and a faulty port or connector", "cat5 or damaged cabling, bad rj45 termination, or a failing port"],
          required: ["cable"], optional: ["cat5", "damaged", "port", "termination", "pairs"],
          explanation: "Gigabit needs all four wire pairs intact; a damaged pair or old Cat5 cable silently downgrades the link to 100 Mbps. Bad ports/terminations do the same.",
          improved: "Check the cable (old Cat5 or a damaged wire pair forces a 100 Mbps fallback, since gigabit needs all four pairs) and the port/connector (worn RJ45 or a failing switch port).",
        },
        {
          id: "hw-prt-5", topic: "Console Ports", type: "troubleshooting", difficulty: "scenario",
          question: "A switch was misconfigured and is now unreachable over the network. How do you get in to fix it?",
          accepted: ["connect to its console port with a console cable and a terminal", "use the console port for direct serial access"],
          required: ["console"], optional: ["serial", "terminal", "direct"],
          explanation: "Console access doesn't depend on the network config — plug in a console cable, open a terminal session, and repair the configuration.",
          improved: "Connect a laptop to the switch's console port with a console cable and open a terminal session — console access works regardless of the network configuration, so you can fix it directly.",
        },
        {
          id: "hw-prt-6", topic: "Ethernet Ports", type: "device_identification", difficulty: "foundation",
          question: "On a 48-port access switch, what typically plugs into the numbered ports versus the SFP uplink ports?",
          accepted: ["end devices in the numbered ports, uplinks to other switches or routers in the sfp ports", "desktops and aps in the copper ports, fibre uplinks in the sfps"],
          required: ["uplink"], optional: ["end devices", "desktops", "other switches", "fibre"],
          explanation: "Copper access ports serve endpoints (PCs, phones, APs); the SFP ports carry higher-speed uplinks toward distribution switches or the router.",
          improved: "The 48 copper ports connect end devices — desktops, phones, APs, printers. The SFP/SFP+ ports carry uplinks: faster (often fibre) connections to distribution switches or the router.",
        },
        {
          id: "hw-prt-7", topic: "SFP Transceivers", type: "troubleshooting", difficulty: "scenario",
          question: "A new fibre uplink won't come up. The fibre is good. What two transceiver-related mismatches should you check?",
          accepted: ["mismatched transceiver types on each end and wrong module for the fibre type", "both ends must match speed and wavelength, and the module must suit single mode or multimode"],
          required: ["match"], optional: ["single mode", "multimode", "wavelength", "speed", "compatibility"],
          explanation: "Both ends must use compatible transceivers (speed/wavelength), and each module must match the fibre type (single-mode vs multimode). Vendor lock-in compatibility is a third gotcha.",
          improved: "Check that both ends use compatible transceivers (same speed and wavelength) and that the modules match the fibre type — a multimode module on single-mode fibre (or vice versa) won't link.",
        },
        {
          id: "hw-prt-8", topic: "Ethernet Ports", type: "definition", difficulty: "foundation",
          question: "What does the blinking LED above an active switch port indicate?",
          accepted: ["link and traffic activity on the port", "the port has a live connection and data is flowing"],
          required: ["activity"], optional: ["link", "traffic", "data flowing"],
          explanation: "Solid usually means link established; blinking indicates frames actively passing through the port.",
          improved: "It shows link and activity: a lit LED means a device is connected and negotiating, and blinking indicates traffic actively flowing through the port.",
        },
      ],
    },
    {
      id: "hw-cabling",
      title: "Cabling & Physical Infrastructure",
      description: "Copper and fibre cabling, single-mode vs multimode, patch panels, and racks.",
      topics: ["Copper Cabling", "Fibre Cabling", "Patch Panels", "Racks"],
      questions: [
        {
          id: "hw-cab-1", topic: "Fibre Cabling", type: "comparison", difficulty: "applied",
          question: "When would you choose single-mode fibre over multimode fibre?",
          accepted: ["for long distances such as between buildings or across a city", "single mode carries light farther, use it for long runs, multimode is cheaper for short in building runs"],
          required: ["long distance"], optional: ["between buildings", "multimode short", "laser"],
          explanation: "Single-mode's narrow core carries a laser signal kilometres; multimode is cheaper for short in-building runs (hundreds of metres).",
          improved: "Choose single-mode for long runs — between buildings, across campuses, kilometres if needed. Multimode is cheaper and fine for short in-building runs up to a few hundred metres.",
        },
        {
          id: "hw-cab-2", topic: "Copper Cabling", type: "definition", difficulty: "foundation",
          question: "Why are the wire pairs inside an Ethernet cable twisted around each other?",
          accepted: ["twisting cancels electromagnetic interference between the pairs", "to reduce crosstalk and interference"],
          required: ["interference"], optional: ["crosstalk", "twisting cancels"],
          explanation: "Twisting makes interference affect both wires of a pair equally so it cancels out — reducing crosstalk between pairs and noise from outside.",
          improved: "The twists cancel electromagnetic interference: noise hits both wires of a pair equally and cancels out, reducing crosstalk between pairs and interference from outside sources.",
        },
        {
          id: "hw-cab-3", topic: "Patch Panels", type: "definition", difficulty: "applied",
          question: "What is a patch panel and why not just run wall cables straight into the switch?",
          accepted: ["a fixed termination point for building cabling, letting you patch to switch ports flexibly without disturbing permanent runs", "it protects permanent cabling and makes moves and changes easy with short patch leads"],
          required: ["termination"], optional: ["patch leads", "flexibility", "permanent cabling", "organized"],
          explanation: "Building runs terminate permanently on the panel; short patch leads connect panel to switch. Changes and re-patching never stress the in-wall cabling.",
          improved: "A patch panel is the fixed termination point for permanent in-wall cabling. Short patch leads then connect panel ports to switch ports — so moves, adds, and changes never disturb or damage the permanent runs.",
        },
        {
          id: "hw-cab-4", topic: "Racks", type: "definition", difficulty: "foundation",
          question: "What does '2U' mean when describing a server or switch?",
          accepted: ["it occupies two rack units of vertical space", "two units of height in a standard 19 inch rack, about 3.5 inches"],
          required: ["rack unit"], optional: ["height", "1.75", "19 inch"],
          explanation: "Rack space is measured in U (1U = 1.75\"/44.45 mm of height); a 2U device takes two of those slots in a standard 19-inch rack.",
          improved: "It's the device's height in rack units: 1U is 1.75 inches, so a 2U device occupies two slots (3.5 inches) of vertical space in a standard 19-inch rack.",
        },
        {
          id: "hw-cab-5", topic: "Copper Cabling", type: "troubleshooting", difficulty: "applied",
          question: "Users near the factory floor get network errors; office users on the same switch don't. The cable route passes heavy machinery. What's the likely cause and a hardware fix?",
          accepted: ["electromagnetic interference from the machinery, use shielded cable or fibre for that run", "emi corrupting the copper signal, reroute or switch to shielded twisted pair or fibre"],
          required: ["interference"], optional: ["emi", "shielded", "fibre", "machinery"],
          explanation: "Motors and machinery radiate EMI that corrupts signals on unshielded copper. Shielded cable, rerouting, or fibre (immune to EMI) fixes it.",
          improved: "Electromagnetic interference from the machinery is corrupting the copper run. Fix with shielded twisted-pair, rerouting away from the machines, or fibre — which is completely immune to EMI.",
        },
        {
          id: "hw-cab-6", topic: "Fibre Cabling", type: "troubleshooting", difficulty: "applied",
          question: "Why must you never look into the end of an active fibre cable, and how do technicians test fibre instead?",
          accepted: ["invisible laser light can damage eyes, use a power meter or visual fault locator", "the laser is invisible and harmful, test with optical tools"],
          required: ["laser"], optional: ["eye damage", "invisible", "power meter", "optical"],
          explanation: "Fibre lasers are infrared — invisible but capable of retinal damage. Optical power meters and fault locators test safely.",
          improved: "Active fibre carries invisible infrared laser light that can permanently damage your retina. Technicians test with optical power meters and visual fault locators instead of looking at the fibre.",
        },
        {
          id: "hw-cab-7", topic: "Racks", type: "configuration_reasoning", difficulty: "applied",
          question: "Give two reasons tidy cable management in a rack is more than cosmetic.",
          accepted: ["it maintains airflow for cooling and makes faults faster to trace", "airflow and troubleshooting, plus strain relief on connectors"],
          required: ["airflow"], optional: ["troubleshooting", "trace", "strain", "cooling"],
          explanation: "Cable rat's nests block airflow (overheating) and make tracing a single cable during an outage painfully slow; dressed cables also relieve connector strain.",
          improved: "Tidy cabling preserves airflow so equipment doesn't overheat, and makes any cable traceable in seconds during an outage. It also prevents strain damage to ports and connectors.",
        },
        {
          id: "hw-cab-8", topic: "Copper Cabling", type: "comparison", difficulty: "applied",
          question: "What do the category ratings (Cat5e, Cat6, Cat6a) of Ethernet cable indicate?",
          accepted: ["supported bandwidth and speed, higher categories handle faster links over distance", "the performance rating, cat5e does gigabit, cat6a does 10 gigabit at 100m"],
          required: ["speed"], optional: ["bandwidth", "cat6a 10 gigabit", "frequency"],
          explanation: "Categories certify signalling performance: Cat5e handles 1 Gbps, Cat6 gives headroom (10 Gbps short runs), Cat6a sustains 10 Gbps at the full 100 m.",
          improved: "The category rates the cable's certified performance: Cat5e supports 1 Gbps, Cat6 supports 10 Gbps over short runs, and Cat6a sustains 10 Gbps over the full 100-metre distance.",
        },
        {
          id: "hw-cab-9", topic: "Patch Panels", type: "troubleshooting", difficulty: "scenario",
          question: "After an office move, desk 14 has no network. The switch port works and the desktop works elsewhere. Where in the cabling chain do you look next?",
          accepted: ["the patch panel connection and the permanent run to the wall outlet", "check the patch lead at the panel, the panel termination, and the wall jack wiring"],
          required: ["patch"], optional: ["wall outlet", "termination", "permanent run", "jack"],
          explanation: "With both ends proven, the middle remains: patch lead to panel, panel termination, the in-wall run, and the wall jack — test with a cable tester.",
          improved: "Check the middle of the chain: the patch lead between switch and panel, the panel termination for desk 14, the permanent in-wall run, and the wall jack — a cable tester across the run will find the break.",
        },
        {
          id: "hw-cab-10", topic: "Fibre Cabling", type: "device_identification", difficulty: "foundation",
          question: "Fibre cables in a rack are often yellow or aqua/orange. What does the colour conventionally tell you?",
          accepted: ["yellow is single mode, aqua or orange is multimode", "the fibre type, yellow for single mode and orange or aqua for multimode"],
          required: ["single mode", "multimode"], optional: ["yellow", "aqua", "orange"],
          explanation: "Jacket colour signals fibre type at a glance: yellow = single-mode; orange (OM1/2) and aqua (OM3/4) = multimode.",
          improved: "The jacket colour indicates fibre type: yellow means single-mode, while orange and aqua mean multimode (aqua typically the newer OM3/OM4 grades).",
        },
      ],
    },
    {
      id: "hw-power",
      title: "Power, Cooling & Resilience",
      description: "Power supplies, redundancy, PoE, UPS units, and cooling.",
      topics: ["Power Supplies", "PoE", "UPS", "Cooling"],
      questions: [
        {
          id: "hw-pow-1", topic: "Power Supplies", type: "definition", difficulty: "applied",
          question: "Why do critical switches and servers ship with two power supplies?",
          accepted: ["redundancy, one psu failing or one power feed dying doesn't take the device down", "dual power supplies allow hot swap and connection to independent feeds"],
          required: ["redundan"], optional: ["failure", "hot swap", "independent feeds"],
          explanation: "Dual PSUs (ideally on separate circuits) mean a PSU failure or single feed outage doesn't drop the device — and dead units hot-swap without downtime.",
          improved: "For redundancy: with two PSUs fed from independent circuits, a power-supply failure or a single feed outage doesn't take the device down, and the failed unit can be hot-swapped in place.",
        },
        {
          id: "hw-pow-2", topic: "PoE", type: "definition", difficulty: "foundation",
          question: "What is Power over Ethernet and name two devices commonly powered by it.",
          accepted: ["delivering electrical power through the network cable, used by access points and ip phones", "poe powers devices like cameras, aps, and phones over the data cable"],
          required: ["power", "cable"], optional: ["access points", "ip phones", "cameras"],
          explanation: "PoE injects DC power onto the Ethernet cable from the switch, powering APs, IP phones, and security cameras with a single cable run.",
          improved: "PoE delivers DC power through the same Ethernet cable that carries data. Wireless access points, IP phones, and security cameras are the classic PoE-powered devices.",
        },
        {
          id: "hw-pow-3", topic: "UPS", type: "definition", difficulty: "applied",
          question: "What does a UPS actually do during a power cut, and what is it NOT designed for?",
          accepted: ["it provides battery power for minutes so equipment rides out short outages or shuts down cleanly, not long term power", "bridges brief outages and allows graceful shutdown, a generator handles extended outages"],
          required: ["battery"], optional: ["short", "graceful shutdown", "not long term", "generator"],
          explanation: "A UPS bridges seconds-to-minutes outages and conditions power; extended outages need a generator. It buys time for clean shutdown or generator start.",
          improved: "A UPS instantly supplies battery power so equipment rides through short outages or shuts down cleanly. It's not for extended outages — batteries last minutes; long outages need a generator the UPS bridges to.",
        },
        {
          id: "hw-pow-4", topic: "PoE", type: "troubleshooting", difficulty: "scenario",
          question: "After adding ten PoE cameras to a switch, some cameras randomly reboot. What switch limitation should you investigate?",
          accepted: ["the switch's total poe power budget is exceeded", "poe budget, the switch can't supply enough watts for every port"],
          required: ["budget"], optional: ["watts", "power capacity", "exceeded"],
          explanation: "Every PoE switch has a total wattage budget. Oversubscribe it and the switch drops or brownouts ports — random device reboots are the classic symptom.",
          improved: "Check the switch's PoE power budget: each switch can only supply a fixed total wattage across all ports. Ten cameras may exceed it, causing the switch to cut power to some ports — hence the random reboots.",
        },
        {
          id: "hw-pow-5", topic: "Cooling", type: "definition", difficulty: "applied",
          question: "What is the 'hot aisle / cold aisle' layout in a data centre for?",
          accepted: ["separating equipment intake air from exhaust air so cooling works efficiently", "racks face each other so cold air is drawn in front and hot air exhausts behind, preventing mixing"],
          required: ["hot", "cold"], optional: ["airflow", "efficiency", "exhaust", "intake"],
          explanation: "Alternating aisles keep cool supply air (fronts) separate from hot exhaust (backs), so equipment never ingests pre-heated air and cooling stays efficient.",
          improved: "It separates airflow: rack fronts face cold aisles where chilled air is supplied, and backs face hot aisles where exhaust collects — preventing hot exhaust from mixing into equipment intakes and wasting cooling.",
        },
        {
          id: "hw-pow-6", topic: "Cooling", type: "troubleshooting", difficulty: "applied",
          question: "A switch in a closed cupboard keeps rebooting on hot afternoons. What's happening and what are two fixes?",
          accepted: ["it's overheating and thermal protection restarts it, add ventilation or move it somewhere cooler", "heat buildup, provide airflow, a vented cabinet or relocation"],
          required: ["overheat"], optional: ["ventilation", "airflow", "relocate", "thermal"],
          explanation: "Sealed spaces trap heat; the switch hits thermal limits and resets. Ventilation, a fan, or relocation to conditioned space fixes it.",
          improved: "The switch is overheating in the unventilated cupboard and its thermal protection is rebooting it. Fixes: add ventilation or a fan to the cupboard, or relocate the switch to a cooler, airflow-friendly space.",
        },
        {
          id: "hw-pow-7", topic: "UPS", type: "configuration_reasoning", difficulty: "scenario",
          question: "A small office can afford one UPS. Which equipment should it protect first, and why?",
          accepted: ["the core network gear, router, firewall, main switch and server, because everything depends on them", "protect shared infrastructure first since one ups keeps the whole network alive"],
          required: ["router"], optional: ["switch", "server", "firewall", "shared", "everything depends"],
          explanation: "Shared infrastructure first: keeping router/firewall/core switch/server up preserves service for everyone; individual desktops matter less.",
          improved: "Protect the shared core: router, firewall, main switch, and the server. One UPS there keeps the whole network and its services alive through an outage — protecting a single desktop helps only one person.",
        },
        {
          id: "hw-pow-8", topic: "Power Supplies", type: "troubleshooting", difficulty: "applied",
          question: "Name two early symptoms that a device's power supply may be failing.",
          accepted: ["random reboots and a loud or failing fan, sometimes a burning smell or brownouts under load", "unexpected restarts, fan noise, clicking, or the device not powering all components"],
          required: ["reboot"], optional: ["fan", "smell", "clicking", "brownout", "restart"],
          explanation: "Failing PSUs show as random restarts, whining/clicking fans, burning smells, or crashes under load as voltage sags.",
          improved: "Random reboots or crashes under load (voltage sagging), and abnormal PSU fan behaviour — grinding, whining, or stopping. A faint burning smell is a late and urgent sign.",
        },
        {
          id: "hw-pow-9", topic: "PoE", type: "comparison", difficulty: "applied",
          question: "An AP needs 25 W but the old switch offers only 15.4 W per port. What's the mismatch, and name two ways to fix it?",
          accepted: ["the switch is 802.3af but the ap needs 802.3at poe plus, upgrade the switch or use a poe injector", "insufficient poe standard, use a midspan injector, a poe+ switch, or a local power adapter"],
          required: ["poe"], optional: ["injector", "upgrade switch", "802.3at", "power adapter"],
          explanation: "15.4 W is the older 802.3af standard; the AP needs PoE+ (802.3at, 30 W). Fix with a PoE+ switch, an inline injector, or local power.",
          improved: "The switch supplies only the older 15.4 W PoE standard while the AP needs PoE+ (up to 30 W). Fix it with a PoE+ capable switch, an inline PoE+ injector for that run, or the AP's local power adapter.",
        },
        {
          id: "hw-pow-10", topic: "UPS", type: "device_identification", difficulty: "foundation",
          question: "Besides battery backup, what power problem does a good UPS smooth out during normal operation?",
          accepted: ["voltage fluctuations like surges, spikes and sags", "it conditions power, protecting against surges and brownouts"],
          required: ["surge"], optional: ["sag", "brownout", "conditioning", "spikes", "fluctuations"],
          explanation: "Line-interactive/online UPSes condition incoming power, absorbing surges, spikes, sags, and brownouts that damage or reboot equipment.",
          improved: "Power conditioning: a good UPS absorbs surges, spikes, sags, and brownouts, feeding equipment clean stable voltage even when mains power is fluctuating.",
        },
      ],
    },
    {
      id: "hw-environments",
      title: "Where Hardware Lives",
      description: "Data centres, branch offices, campus networks, cloud infrastructure, failure symptoms, and hardware selection.",
      topics: ["Data Centres", "Branch & Campus", "Cloud Infrastructure", "Hardware Selection"],
      questions: [
        {
          id: "hw-env-1", topic: "Data Centres", type: "definition", difficulty: "foundation",
          question: "What is a data centre?",
          accepted: ["a facility built to house servers, storage and network equipment with redundant power and cooling", "a dedicated building for it infrastructure with controlled power, cooling and security"],
          required: ["servers"], optional: ["redundant power", "cooling", "facility", "storage"],
          explanation: "Data centres concentrate compute, storage, and networking in a facility engineered for continuous operation: redundant power, cooling, connectivity, and physical security.",
          improved: "A data centre is a dedicated facility housing servers, storage, and network equipment, engineered with redundant power, cooling, connectivity, and physical security for continuous operation.",
        },
        {
          id: "hw-env-2", topic: "Branch & Campus", type: "comparison", difficulty: "applied",
          question: "What network equipment does a typical small branch office need versus a large campus?",
          accepted: ["a branch needs a router, a switch, an ap and a firewall, a campus adds layers of switches, many aps, controllers and redundant cores", "branch has one of each essential device, campus has hierarchical switching with distribution and core layers"],
          required: ["router", "switch"], optional: ["access point", "firewall", "core", "distribution", "hierarchical", "redundant"],
          explanation: "A branch runs on the essentials: edge router/firewall, a switch or two, APs. A campus scales into an access/distribution/core switch hierarchy with WLCs and redundancy everywhere.",
          improved: "A branch: one edge router/firewall, an access switch, and a couple of APs. A campus: a hierarchy of access, distribution, and core switches, dozens of APs with a controller, and redundancy at every layer.",
        },
        {
          id: "hw-env-3", topic: "Cloud Infrastructure", type: "definition", difficulty: "applied",
          question: "When a company 'moves a server to the cloud', where does the hardware actually go?",
          accepted: ["it runs as a virtual machine on the cloud provider's hardware in their data centres", "nowhere, the workload runs on provider owned servers, you rent capacity"],
          required: ["provider"], optional: ["virtual machine", "their data centre", "rent"],
          mistakes: ["Thinking the cloud is hardware-free — it's someone else's data centre."],
          explanation: "The workload becomes a VM on the provider's servers in their data centres. The hardware still exists — the provider owns and operates it; you rent slices.",
          improved: "The workload runs as a virtual machine on the cloud provider's physical servers in their data centres. The hardware doesn't disappear — the provider owns, powers, cools, and maintains it, and you rent capacity.",
        },
        {
          id: "hw-env-4", topic: "Hardware Selection", type: "comparison", difficulty: "scenario",
          question: "A 10-person startup asks whether to buy an enterprise chassis switch or a small business switch. What factors decide it?",
          accepted: ["port count, budget, growth plans and required features, a small managed switch fits ten people", "size the hardware to need, users, growth, features and budget point to the small switch"],
          required: ["need"], optional: ["port count", "budget", "growth", "features", "oversized"],
          explanation: "Match hardware to requirements: ports needed, features (VLANs, PoE), growth horizon, and budget. Ten users don't justify chassis-class cost and complexity.",
          improved: "Size to need: user/port count, required features (VLANs, PoE), realistic growth, and budget. For 10 people, a small managed switch does everything required — the chassis switch is wasted cost and complexity.",
        },
        {
          id: "hw-env-5", topic: "Hardware Selection", type: "troubleshooting", difficulty: "applied",
          question: "Name three general symptoms that suggest failing network hardware rather than a configuration problem.",
          accepted: ["random reboots, increasing error counts on ports, and intermittent faults that move with the device", "physical symptoms like heat, dead ports, flapping links and degrading performance over time"],
          required: [], optional: ["reboots", "port errors", "intermittent", "flapping", "heat", "dead ports", "degrading", "crc"],
          explanation: "Hardware failure signatures: spontaneous reboots, climbing interface error counters (CRC), link flapping, dead ports, overheating, and faults that follow the device when moved.",
          improved: "Random reboots or crashes, climbing port error counters (CRC/input errors) and link flapping, and intermittent faults that follow the device when you move it — plus physical signs like excessive heat or dead ports.",
        },
        {
          id: "hw-env-6", topic: "Data Centres", type: "device_identification", difficulty: "applied",
          question: "In a data centre, what is a 'top of rack' switch?",
          accepted: ["a switch mounted in each rack that connects that rack's servers to the network", "the access switch at the top of a server rack aggregating its servers"],
          required: ["rack", "servers"], optional: ["access", "aggregates", "uplinks"],
          explanation: "ToR switches live in each rack, connecting the rack's servers with short cables and uplinking to the data centre fabric.",
          improved: "A top-of-rack switch sits in each server rack and connects all that rack's servers with short patch cables, then uplinks (usually fibre) into the data centre's aggregation fabric.",
        },
        {
          id: "hw-env-7", topic: "Branch & Campus", type: "troubleshooting", difficulty: "scenario",
          question: "A retail chain's branch loses its single WAN router. The whole store goes offline — tills included. What design change prevents a repeat?",
          accepted: ["redundancy, a second router or backup wan link such as cellular failover", "dual routers or a backup internet connection with automatic failover"],
          required: ["backup"], optional: ["second router", "failover", "cellular", "redundant wan"],
          explanation: "Single points of failure at the WAN edge need redundancy: dual routers and/or a second WAN path (often LTE/5G) with automatic failover.",
          improved: "Add WAN redundancy: a second router and/or a backup link — commonly cellular failover — so if the primary router or circuit dies, the store's traffic automatically shifts to the backup path.",
        },
        {
          id: "hw-env-8", topic: "Cloud Infrastructure", type: "comparison", difficulty: "scenario",
          question: "What networking hardware does a company still need on-site after moving all its servers to the cloud?",
          accepted: ["everything for local connectivity, switches, aps, a router or firewall and the internet links, since users still need to reach the cloud", "lan infrastructure remains, plus stronger internet redundancy because everything depends on it"],
          required: ["switch"], optional: ["access points", "router", "firewall", "internet", "redundancy"],
          explanation: "Cloud moves servers, not the office LAN. Users still need switches, Wi-Fi, edge routing/firewalling — and the internet link becomes more critical than ever.",
          improved: "All the local access infrastructure: switches, access points, an edge router/firewall, and the internet circuits — which now deserve redundancy, because with everything in the cloud, the internet link is the business's lifeline.",
        },
        {
          id: "hw-env-9", topic: "Hardware Selection", type: "solution_recommendation", difficulty: "scenario",
          question: "A video-production team complains file transfers to their shared storage are slow on gigabit. What hardware upgrade path would you explore, and what would you check first?",
          accepted: ["check where the bottleneck actually is, then consider 10 gigabit networking for the team and storage", "verify the bottleneck is the network not the storage, then 10g switch, nics and cabling"],
          required: ["bottleneck", "10"], optional: ["verify first", "nics", "switch", "storage speed"],
          explanation: "Diagnose before buying: confirm the network (not disks) is the limit. If so, 10 GbE for storage and workstations — switch, NICs, and appropriate cabling/transceivers.",
          improved: "First verify the bottleneck really is the network rather than the storage's own disks. If it is, move the team to 10 GbE: a 10G switch, 10G NICs in the workstations and storage, and Cat6a or fibre links.",
        },
        {
          id: "hw-env-10", topic: "Data Centres", type: "definition", difficulty: "applied",
          question: "Why do data centres advertise 'N+1' power and cooling?",
          accepted: ["there is at least one spare unit beyond what's needed, so a failure doesn't reduce capacity", "n+1 means capacity for full load plus one redundant unit"],
          required: ["spare"], optional: ["redundant", "one extra", "failure"],
          explanation: "N+1 = enough units for full load (N) plus one spare, so any single unit can fail or be serviced without impact.",
          improved: "N+1 means the facility has the units required for full load plus one spare — any single UPS, generator, or cooling unit can fail or undergo maintenance without affecting operations.",
        },
      ],
    },
  ],
});
