import { defineCourse } from "./builder";

/** Reinforces concepts used in beginner Packet Tracer labs. All questions are
 *  answerable in-game — Packet Tracer itself is never required. */
export const packetTracerPractice = defineCourse({
  id: "packet-tracer-practice", // internal id kept stable for saved progress
  title: "Network Configuration and Simulation",
  provider: "Cisco Networking Academy",
  description:
    "Reinforce the device, cabling, addressing, and configuration knowledge used in beginner network-simulation exercises (Packet Tracer, GNS3, and similar tools).",
  icon: "🧪",
  disclaimer:
    "Original practice questions reinforcing concepts from beginner Packet Tracer labs. This is not an official Cisco assessment.",
  modules: [
    {
      id: "pt-devices-cables",
      title: "Devices & Cabling Choices",
      description: "Selecting the right devices and cables when building a topology.",
      topics: ["Device Selection", "Cable Types"],
      questions: [
        {
          id: "pt-dc-1", topic: "Cable Types", type: "configuration_reasoning", difficulty: "foundation",
          question: "In a topology tool, what cable type connects a PC to a switch?",
          accepted: ["a straight through copper cable", "straight through ethernet"],
          required: ["straight"],
          mistakes: ["Choosing crossover — that's for like-to-like device connections (on older gear)."],
          explanation: "Unlike devices (PC↔switch) use straight-through cable; the wire order is identical at both ends.",
          improved: "A copper straight-through cable — used between unlike devices such as PC-to-switch and switch-to-router.",
        },
        {
          id: "pt-dc-2", topic: "Cable Types", type: "configuration_reasoning", difficulty: "applied",
          question: "You connect two switches together in a lab and the link stays down (older devices, no auto-sensing). Which cable should you have used?",
          accepted: ["a crossover cable", "crossover, since they are like devices"],
          required: ["crossover"],
          explanation: "Like devices (switch↔switch, PC↔PC) traditionally need crossover cable, which swaps transmit and receive pairs. Modern auto-MDIX gear adapts, but labs often simulate classic behaviour.",
          improved: "A crossover cable — like devices transmit on the same pins, so the cable must swap the transmit and receive pairs. (Modern auto-MDIX ports fix this automatically, but classic lab devices don't.)",
        },
        {
          id: "pt-dc-3", topic: "Cable Types", type: "configuration_reasoning", difficulty: "foundation",
          question: "Which special cable do you use to configure a router from a PC's terminal when it has no network config yet?",
          accepted: ["a console cable", "the rollover console cable"],
          required: ["console"], optional: ["rollover"],
          explanation: "The console (rollover) cable links the PC to the device's console port for out-of-band CLI access.",
          improved: "A console (rollover) cable from the PC to the router's console port — giving direct CLI access that works before any network configuration exists.",
        },
        {
          id: "pt-dc-4", topic: "Device Selection", type: "device_identification", difficulty: "foundation",
          question: "You're building a small lab: 4 PCs must share files on one network, no internet. What single intermediary device do you drag in?",
          accepted: ["a switch", "one switch to connect all four pcs"],
          required: ["switch"],
          mistakes: ["Adding a router — with a single network there's nothing to route."],
          explanation: "One LAN, no external connectivity: a switch is all that's needed. Routers only matter when joining different networks.",
          improved: "Just a switch — all four PCs plug into it and share one network. A router would only be needed to connect this LAN to another network.",
        },
        {
          id: "pt-dc-5", topic: "Device Selection", type: "device_identification", difficulty: "applied",
          question: "Your lab has two separate networks, 192.168.1.0/24 and 192.168.2.0/24, each on its own switch. What device joins them so PCs can communicate across?",
          accepted: ["a router with an interface in each network", "a router connecting both switches"],
          required: ["router"], optional: ["interface in each"],
          explanation: "Crossing between IP networks requires routing: a router with one interface addressed in each subnet.",
          improved: "A router — connect one interface to each switch and address it in that network (e.g., 192.168.1.1 and 192.168.2.1). Each PC then uses its side's router address as default gateway.",
        },
        {
          id: "pt-dc-6", topic: "Cable Types", type: "troubleshooting", difficulty: "applied",
          question: "In a simulation, the link lights between two devices show red/down immediately after cabling. Name the two first things to check.",
          accepted: ["the cable type is correct and the interfaces are enabled", "right cable for the device pair, and ports not shut down"],
          required: ["cable"], optional: ["interface", "shutdown", "enabled", "no shut"],
          explanation: "Red links are physical/administrative: wrong cable type for the pair, or interfaces administratively down (router interfaces default to shutdown).",
          improved: "First, that the correct cable type was used for that device pair; second, that both interfaces are enabled — router interfaces are administratively shut down by default and need 'no shutdown'.",
        },
        {
          id: "pt-dc-7", topic: "Device Selection", type: "device_identification", difficulty: "applied",
          question: "You want lab laptops to join the network without cables. What device do you add to the switch, and what do you configure on it first?",
          accepted: ["a wireless access point with an ssid", "an access point connected to the switch, configure the ssid and security"],
          required: ["access point", "ssid"], optional: ["security", "wpa2"],
          explanation: "An AP wired to the switch broadcasts an SSID; configure the network name and WPA2 security before clients join.",
          improved: "Add a wireless access point cabled to the switch, then configure its SSID (network name) and WPA2 security — laptops select that SSID and authenticate to join.",
        },
        {
          id: "pt-dc-8", topic: "Device Selection", type: "comparison", difficulty: "applied",
          question: "In device menus you see both a 'hub' and a 'switch'. Why does replacing a hub with a switch improve a busy lab network?",
          accepted: ["a switch forwards frames only to the destination port, eliminating the collisions and wasted bandwidth of a hub", "hubs repeat everything everywhere, switches deliver only where needed"],
          required: ["destination"], optional: ["collisions", "bandwidth", "repeat to all"],
          explanation: "Hubs are shared-medium repeaters — every frame everywhere, constant collisions. Switches segment traffic per port.",
          improved: "A hub repeats every frame to every port, so all devices share one collision-prone channel. A switch learns MAC addresses and forwards each frame only to its destination port, giving each device its own full-bandwidth path.",
        },
        {
          id: "pt-dc-9", topic: "Cable Types", type: "configuration_reasoning", difficulty: "applied",
          question: "Connecting a lab router to a switch: which cable, and into which kind of port on each device?",
          accepted: ["a straight through cable from a router ethernet interface to a regular switch port", "straight through, router gigabitethernet to switch access port"],
          required: ["straight"], optional: ["ethernet interface", "switch port"],
          explanation: "Router↔switch are unlike devices: straight-through copper, from the router's Ethernet interface to any switch port.",
          improved: "A straight-through copper cable from one of the router's Ethernet (e.g., GigabitEthernet0/0) interfaces into a normal switch port — router and switch are unlike devices.",
        },
        {
          id: "pt-dc-10", topic: "Device Selection", type: "troubleshooting", difficulty: "scenario",
          question: "A student's topology has every PC connected directly to router ports. It works, but why is this poor design compared with using a switch?",
          accepted: ["router ports are few and expensive, switches are built to aggregate many end devices", "it wastes limited router interfaces, a switch should aggregate the pcs"],
          required: ["ports"], optional: ["expensive", "aggregate", "doesn't scale", "switch is for lan"],
          explanation: "Routers have few costly interfaces meant for network-to-network links; access aggregation is the switch's job. The design can't scale past a handful of PCs.",
          improved: "Routers have only a handful of expensive interfaces designed for connecting networks, not hosts. A switch aggregates the PCs on one network and uses a single router link — scalable, cheaper, and the standard design.",
        },
      ],
    },
    {
      id: "pt-addressing",
      title: "Addressing & Basic Configuration",
      description: "Assigning IP addresses and performing first-time switch and router setup.",
      topics: ["IP Assignment", "Switch Config", "Router Config"],
      questions: [
        {
          id: "pt-ad-1", topic: "IP Assignment", type: "configuration_reasoning", difficulty: "foundation",
          question: "You give a lab PC the address 192.168.1.10/24. What two more settings does it need to browse a web server on another network by name?",
          accepted: ["a default gateway and a dns server", "gateway for leaving the network and dns to resolve names"],
          required: ["gateway", "dns"],
          explanation: "Cross-network traffic needs the default gateway; browsing by name additionally needs a DNS server address.",
          improved: "A default gateway (the router's address, e.g. 192.168.1.1) to reach other networks, and a DNS server address so it can resolve the server's name.",
        },
        {
          id: "pt-ad-2", topic: "Router Config", type: "configuration_reasoning", difficulty: "applied",
          question: "List the essential steps to bring up a router interface with address 192.168.1.1/24 in IOS-style configuration.",
          accepted: ["enter the interface, set the ip address and mask, then no shutdown", "interface g0/0, ip address 192.168.1.1 255.255.255.0, no shutdown"],
          required: ["ip address", "no shutdown"], optional: ["interface", "255.255.255.0"],
          explanation: "Enter interface config mode, assign `ip address 192.168.1.1 255.255.255.0`, then `no shutdown` — interfaces are administratively down by default.",
          improved: "Enter config mode, select the interface (`interface g0/0`), assign `ip address 192.168.1.1 255.255.255.0`, then enable it with `no shutdown` — router interfaces are shut down by default.",
        },
        {
          id: "pt-ad-3", topic: "Switch Config", type: "configuration_reasoning", difficulty: "applied",
          question: "A Layer 2 switch forwards frames fine without any IP address. Why would you still give the switch a management IP?",
          accepted: ["so you can reach it remotely for management over telnet, ssh or web", "remote administration, without an ip you can only manage it via console"],
          required: ["manage"], optional: ["remote", "ssh", "telnet"],
          explanation: "Switching needs no IP; management does. An IP on the management VLAN interface enables SSH/monitoring instead of console-only access.",
          improved: "For remote management: an IP on its management interface (VLAN 1 or a management VLAN) lets admins SSH in, monitor it, and configure it over the network instead of standing at the console port.",
        },
        {
          id: "pt-ad-4", topic: "IP Assignment", type: "troubleshooting", difficulty: "applied",
          question: "In a lab, PC1 is 192.168.1.10/24 and PC2 is 192.168.2.10/24, both plugged into the SAME switch. Why can't they ping each other?",
          accepted: ["they are on different ip networks and there is no router to route between them", "different subnets on one switch still need a router"],
          required: ["different network"], optional: ["router", "no route"],
          explanation: "A shared switch is not a shared network: their IP networks differ, each looks for a gateway, and none exists.",
          improved: "Their addresses put them on different IP networks (192.168.1.0 vs 192.168.2.0). Traffic between different IP networks needs a router — the shared switch alone can't bridge the logical gap.",
        },
        {
          id: "pt-ad-5", topic: "Router Config", type: "configuration_reasoning", difficulty: "applied",
          question: "What is the purpose of the 'enable secret' command during basic router setup?",
          accepted: ["it sets an encrypted password protecting privileged exec mode", "protects access to privileged mode with a hashed password"],
          required: ["password"], optional: ["privileged", "encrypted", "secret"],
          explanation: "`enable secret` sets a hashed password gating privileged EXEC mode — the level where config changes happen.",
          improved: "It sets an encrypted (hashed) password required to enter privileged EXEC mode — protecting the configuration level of the device from unauthorized access.",
        },
        {
          id: "pt-ad-6", topic: "IP Assignment", type: "configuration_reasoning", difficulty: "scenario",
          question: "You must address a lab of 3 PCs and a router LAN interface from 192.168.5.0/24. Propose a sensible assignment scheme.",
          accepted: ["router gets 192.168.5.1 and the pcs get .10 .11 .12 with mask 255.255.255.0 and gateway .1", "gateway .1 for the router, sequential host addresses for the pcs, all /24"],
          required: ["192.168.5.1"], optional: ["gateway", "sequential", "255.255.255.0"],
          explanation: "Convention: the router takes the first usable address (.1) as everyone's gateway; hosts take documented sequential addresses within the /24.",
          improved: "Give the router 192.168.5.1/24 (it becomes every PC's default gateway) and the PCs 192.168.5.10–12/24 — low, sequential, documented host addresses with the gateway set to .1.",
        },
        {
          id: "pt-ad-7", topic: "Switch Config", type: "configuration_reasoning", difficulty: "applied",
          question: "Why do lab exercises always tell you to set a hostname on each switch and router first?",
          accepted: ["so each device's cli prompt identifies which device you're configuring", "identification, the prompt shows the hostname preventing configuring the wrong device"],
          required: ["identif"], optional: ["prompt", "which device", "wrong device"],
          explanation: "The hostname appears in the CLI prompt — with many open console sessions, it's the guard against configuring the wrong box.",
          improved: "The hostname appears in the CLI prompt (e.g., `Switch1#`), so you always know which device a session controls — preventing the classic mistake of configuring the wrong device.",
        },
        {
          id: "pt-ad-8", topic: "Router Config", type: "troubleshooting", difficulty: "scenario",
          question: "After configuring a lab router perfectly, you power-cycle it and all configuration is gone. What step was forgotten?",
          accepted: ["saving the running config to startup config with copy run start", "the config was never saved to nvram, write memory or copy running-config startup-config"],
          required: ["save"], optional: ["copy run start", "startup config", "nvram", "write memory"],
          explanation: "The running config lives in RAM and dies at reboot; `copy running-config startup-config` persists it to NVRAM.",
          improved: "Saving the configuration: the running config exists only in RAM. `copy running-config startup-config` (or `write memory`) stores it in NVRAM so it survives a reboot.",
        },
        {
          id: "pt-ad-9", topic: "IP Assignment", type: "troubleshooting", difficulty: "applied",
          question: "A lab PC was given IP 192.168.1.1 — the same address planned for the router interface. What problems will appear when the router comes online?",
          accepted: ["an ip address conflict causing intermittent failures for both and broken routing for the whole lan", "duplicate ip, arp confusion, and the lan's gateway becomes unreliable"],
          required: ["conflict"], optional: ["duplicate", "gateway", "arp", "intermittent"],
          explanation: "Duplicate IP — worse, it's the gateway address. ARP caches flip between the two MACs and every PC's off-network traffic becomes a coin toss.",
          improved: "An IP conflict on the most critical address in the subnet: devices' ARP tables will alternate between the PC and router MACs, making the default gateway — and therefore all external connectivity — intermittently fail for everyone.",
        },
        {
          id: "pt-ad-10", topic: "Switch Config", type: "configuration_reasoning", difficulty: "applied",
          question: "In a first-day lab you're told to configure 'line console 0' with a password. What access does this protect?",
          accepted: ["physical console port access to the device cli", "anyone plugging a console cable into the device"],
          required: ["console"], optional: ["physical", "cli access"],
          explanation: "`line console 0` settings govern the physical console port — the password stops anyone with a cable from walking up and logging in.",
          improved: "It password-protects the physical console port — without it, anyone who can plug a console cable into the device gets CLI access to it.",
        },
      ],
    },
    {
      id: "pt-connectivity",
      title: "Connectivity Testing & Topology Reading",
      description: "Testing with ping, reading topologies, and tracing why packets flow or don't.",
      topics: ["Ping Testing", "Topology Reading"],
      questions: [
        {
          id: "pt-con-1", topic: "Ping Testing", type: "troubleshooting", difficulty: "applied",
          question: "After building a two-network lab, what is a sensible ORDER of pings from PC1 to prove the whole path works?",
          accepted: ["ping its own gateway first, then the router's far interface, then the remote pc", "gateway, then the far side of the router, then the destination host"],
          required: ["gateway", "then"], optional: ["far interface", "remote pc", "order"],
          explanation: "Test outward in stages: local gateway (LAN + router near side), router's far interface (routing), remote PC (full path + far LAN). First failure marks the broken segment.",
          improved: "Ping the default gateway first (proves the local LAN and near router interface), then the router's far-side interface (proves routing through the device), then the remote PC (proves the full path). The first failing step localizes the fault.",
        },
        {
          id: "pt-con-2", topic: "Ping Testing", type: "troubleshooting", difficulty: "applied",
          question: "In simulation labs, the FIRST ping between two freshly-configured PCs often fails but the second succeeds. Why?",
          accepted: ["the first packet is dropped while arp resolves the mac address", "arp resolution delay, the initial ping times out while the arp request completes"],
          required: ["arp"], optional: ["resolve", "first packet", "timeout"],
          explanation: "The sender must ARP for the destination's MAC before delivering; the first echo request commonly times out during resolution — normal, not a fault.",
          improved: "The first ping triggers ARP resolution — the sender doesn't yet know the destination's MAC address, and the initial echo request times out while ARP completes. It's expected behaviour, not a network fault.",
        },
        {
          id: "pt-con-3", topic: "Topology Reading", type: "packet_journey", difficulty: "applied",
          question: "Topology: PC1 — Switch1 — Router — Switch2 — PC2. PC1 pings PC2. Which devices look at the packet's IP address, and which only look at MAC addresses?",
          accepted: ["only the router examines the ip, the switches forward by mac", "switches use macs, the router routes by ip"],
          required: ["router", "ip", "switch", "mac"],
          explanation: "Switches are Layer 2: MAC-based forwarding only. The router is the sole Layer 3 hop, examining the destination IP to route between the networks.",
          improved: "Switch1 and Switch2 forward frames purely by MAC address — they never inspect the IP header. Only the router examines the destination IP address to route the packet from PC1's network to PC2's.",
        },
        {
          id: "pt-con-4", topic: "Ping Testing", type: "troubleshooting", difficulty: "scenario",
          question: "PC1 can ping the router's near interface (192.168.1.1) but not its far interface (192.168.2.1). Both interfaces show 'up'. What configuration is PC1 probably missing?",
          accepted: ["its default gateway", "the pc has no gateway set so it can't reach any other network"],
          required: ["gateway"],
          explanation: "Reaching the near interface is local; the far interface is on another network and requires the PC to route via its gateway. No gateway ⇒ exactly this split.",
          improved: "The default gateway: 192.168.1.1 is on PC1's own network (direct delivery works), but 192.168.2.1 belongs to another network — without a gateway configured, PC1 has nowhere to send off-network traffic.",
        },
        {
          id: "pt-con-5", topic: "Topology Reading", type: "troubleshooting", difficulty: "scenario",
          question: "In a lab topology, the link between Switch1 and the Router shows green, but PCs on Switch1 can't reach anything past the router. The router's OTHER interface icon shows red. What do you conclude?",
          accepted: ["the far interface is down so packets have no exit, bring it up or fix its cabling", "the router's second interface is down, no shutdown or fix the link"],
          required: ["interface", "down"], optional: ["far side", "no shutdown", "cable"],
          explanation: "Routing needs both legs alive: a red far-side interface (shutdown or cabling) blackholes everything crossing the router.",
          improved: "The router's far-side interface is down — likely still administratively shut down or mis-cabled. Traffic enters the router but has no live exit. Fix the interface (`no shutdown`) or its cabling.",
        },
        {
          id: "pt-con-6", topic: "Ping Testing", type: "configuration_reasoning", difficulty: "applied",
          question: "Besides ping, simulation tools offer a 'simulation mode' that animates packets hop by hop. When is that mode more useful than ping?",
          accepted: ["when you need to see where a packet is dropped and which device discards it", "for watching the path and finding the exact device or step that fails"],
          required: ["where"], optional: ["dropped", "which device", "step by step", "visualize"],
          explanation: "Ping says pass/fail; simulation mode shows the journey — which device drops the packet and at what step — turning guesswork into observation.",
          improved: "When ping merely tells you 'it fails' — simulation mode shows the packet's journey hop by hop, revealing exactly which device discards it and why (no route, ARP failure, blocked port), which turns diagnosis into direct observation.",
        },
        {
          id: "pt-con-7", topic: "Topology Reading", type: "packet_journey", difficulty: "scenario",
          question: "PC1 (192.168.1.10) sends a packet to PC2 (192.168.2.10) through Router R1. What are the destination MAC and destination IP of the frame as it LEAVES PC1?",
          accepted: ["destination mac is the router's near interface, destination ip is pc2", "mac of the gateway, ip of 192.168.2.10"],
          required: ["router", "mac", "pc2"], optional: ["gateway mac", "192.168.2.10"],
          explanation: "Off-network traffic is framed to the gateway's MAC while the IP header targets the true destination — the router re-frames per hop.",
          improved: "Destination MAC: R1's near-side interface (the gateway) — PC1 frames off-network traffic to its router. Destination IP: 192.168.2.10 (PC2) — the IP header carries the true end destination the whole way.",
        },
        {
          id: "pt-con-8", topic: "Ping Testing", type: "troubleshooting", difficulty: "applied",
          question: "A lab asks you to verify a PC's own TCP/IP stack before testing the network. What single ping does that?",
          accepted: ["ping 127.0.0.1", "ping the loopback address"],
          required: ["127.0.0.1"], optional: ["loopback"],
          explanation: "Pinging loopback exercises the local stack only — success means the OS networking is fine regardless of cables or config.",
          improved: "`ping 127.0.0.1` — the loopback address. A reply proves the PC's own TCP/IP stack works, without involving the NIC, cable, or any network device.",
        },
        {
          id: "pt-con-9", topic: "Topology Reading", type: "troubleshooting", difficulty: "scenario",
          question: "Two PCs on the same switch and same subnet can't communicate. Link lights are green and IPs/masks are correct. In a lab, what switch-level configuration would you inspect next?",
          accepted: ["whether the two ports are in the same vlan", "vlan membership of the ports, they may be in different vlans"],
          required: ["vlan"], optional: ["same vlan", "port membership"],
          explanation: "Green links + right IPs but no contact on one switch = VLAN separation. Ports in different VLANs are logically different networks.",
          improved: "The VLAN assignment of the two ports: if one port was placed in a different VLAN, the PCs are on logically separate networks even though they share the switch — frames simply never cross between them.",
        },
        {
          id: "pt-con-10", topic: "Ping Testing", type: "troubleshooting", difficulty: "applied",
          question: "You ping a lab server by IP: success. You ping it by its configured name: 'unknown host'. Which lab service is missing or misconfigured?",
          accepted: ["dns", "the dns server or the pc's dns setting"],
          required: ["dns"],
          explanation: "IP works, name fails: pure name-resolution issue — the lab DNS server or the client's DNS configuration.",
          improved: "DNS — the network path is proven by the IP ping, so the failure is name resolution: the lab's DNS server isn't running, lacks the record, or the PC's DNS server setting is wrong.",
        },
      ],
    },
    {
      id: "pt-errors-vlans",
      title: "Config Errors, VLANs & Wireless",
      description: "Spotting misconfigurations, basic VLAN concepts, and simple wireless setups.",
      topics: ["Config Errors", "VLAN Basics", "Wireless Setup"],
      questions: [
        {
          id: "pt-err-1", topic: "Config Errors", type: "troubleshooting", difficulty: "scenario",
          question: "A lab PC is set to 192.168.1.20, mask 255.255.255.0, gateway 192.168.1.254 — but the router interface is actually 192.168.1.1. What exactly breaks, and what still works?",
          accepted: ["local lan traffic still works but anything off network fails because the gateway points at a nonexistent address", "same subnet communication is fine, external fails, wrong gateway"],
          required: ["gateway", "local"], optional: ["off network fails", "wrong address"],
          explanation: "Local switching ignores the gateway, so LAN peers work. All off-network traffic is sent to .254 — which doesn't exist — and dies.",
          improved: "Communication within 192.168.1.0/24 works fine (the gateway isn't involved). Everything off-network fails: the PC forwards it to 192.168.1.254, an address nothing owns. Fix the gateway to 192.168.1.1.",
        },
        {
          id: "pt-err-2", topic: "Config Errors", type: "troubleshooting", difficulty: "scenario",
          question: "Router interfaces: G0/0 = 192.168.1.1/24 toward Switch1, G0/1 = 192.168.1.254/24 toward Switch2. The router complains. Why is this configuration invalid?",
          accepted: ["both interfaces are in the same subnet, each router interface must be in a different network", "overlapping networks on two interfaces, the router can't route between identical subnets"],
          required: ["same subnet"], optional: ["overlap", "different network per interface"],
          explanation: "Routers route BETWEEN networks; two interfaces in one subnet create an ambiguous, overlapping route. Each interface needs its own network.",
          improved: "Both interfaces claim the same network (192.168.1.0/24) — a router can't route between two interfaces on one subnet. Each interface must own a distinct network, e.g. 192.168.1.1/24 and 192.168.2.1/24.",
        },
        {
          id: "pt-err-3", topic: "VLAN Basics", type: "definition", difficulty: "applied",
          question: "In one sentence, what does creating VLAN 10 and VLAN 20 on a single lab switch achieve?",
          accepted: ["it splits the switch into two isolated logical networks", "two separate broadcast domains on one physical switch"],
          required: ["separate"], optional: ["logical networks", "broadcast domains", "isolated"],
          explanation: "VLANs partition one physical switch into independent logical switches — ports in different VLANs can't talk without a router.",
          improved: "It logically splits the one physical switch into two isolated networks (broadcast domains) — ports in VLAN 10 and ports in VLAN 20 cannot communicate without a Layer 3 device.",
        },
        {
          id: "pt-err-4", topic: "VLAN Basics", type: "configuration_reasoning", difficulty: "applied",
          question: "Two switches each carry VLAN 10 and VLAN 20. What kind of link between the switches lets BOTH VLANs cross, and what does it add to each frame?",
          accepted: ["a trunk link, which tags frames with their vlan id", "trunk port using 802.1q tagging"],
          required: ["trunk"], optional: ["tag", "802.1q", "vlan id"],
          explanation: "Trunk links multiplex VLANs by inserting an 802.1Q tag carrying the VLAN ID into each frame; the far switch reads and strips it.",
          improved: "A trunk link: it carries multiple VLANs by inserting an 802.1Q tag with the frame's VLAN ID, so the receiving switch knows which VLAN each frame belongs to.",
        },
        {
          id: "pt-err-5", topic: "Config Errors", type: "troubleshooting", difficulty: "scenario",
          question: "A student configured a switch port as 'access VLAN 30' but VLAN 30 was never created on the switch. What typically happens to devices on that port?",
          accepted: ["the port is assigned to a nonexistent vlan so traffic goes nowhere until vlan 30 is created", "connectivity fails or the port stays inactive because the vlan doesn't exist"],
          required: ["vlan"], optional: ["doesn't exist", "create", "inactive", "no traffic"],
          explanation: "A port in an undefined VLAN forwards nothing useful — on real IOS the port shows 'inactive'. Creating VLAN 30 fixes it instantly.",
          improved: "The port belongs to a VLAN that doesn't exist, so it goes inactive — the connected device gets link but its frames go nowhere. Creating VLAN 30 on the switch (vlan 30) immediately restores traffic.",
        },
        {
          id: "pt-err-6", topic: "Wireless Setup", type: "configuration_reasoning", difficulty: "applied",
          question: "Setting up a lab wireless router: name the three settings you change before connecting any client.",
          accepted: ["the ssid, the wireless security mode with a passphrase, and the admin password", "network name, wpa2 password, and the management login"],
          required: ["ssid", "password"], optional: ["wpa2", "security mode", "admin password"],
          explanation: "A sane wireless baseline: unique SSID, WPA2/WPA3 with a strong passphrase, and a changed admin login (never leave defaults).",
          improved: "Set a unique SSID, enable WPA2/WPA3 security with a strong passphrase, and change the router's default admin password — the three-step baseline before any client connects.",
        },
        {
          id: "pt-err-7", topic: "Wireless Setup", type: "troubleshooting", difficulty: "applied",
          question: "A lab laptop sees the new wireless network but fails to connect with 'authentication failed'. What are the two most likely mismatches?",
          accepted: ["wrong passphrase or mismatched security mode between laptop and ap", "the key is wrong, or the security type doesn't match"],
          required: ["pass"], optional: ["security mode", "mismatch", "wpa"],
          explanation: "Auth failures at join are almost always the passphrase or a security-mode mismatch (e.g., client trying WPA2 against WPA3-only).",
          improved: "A wrong passphrase, or a security-mode mismatch — e.g., the AP set to WPA3-only while the laptop attempts WPA2. Verify the key and align the security mode on both ends.",
        },
        {
          id: "pt-err-8", topic: "Config Errors", type: "troubleshooting", difficulty: "scenario",
          question: "Everything in a lab pings EXCEPT one PC, which shows 'link down'. List the order of physical things you'd check in the simulator.",
          accepted: ["the cable type and connection points, then whether the switch port or nic is shut down or faulty", "cable first, then port state on the switch, then the pc's interface"],
          required: ["cable"], optional: ["port", "shutdown", "nic", "order"],
          explanation: "Link-down is Layer 1: cable type/seating first, then switch-port state (shutdown? faulty?), then the PC's NIC state.",
          improved: "Cable first — right type, plugged into the intended ports; then the switch port — not shut down or errored; then the PC's NIC — enabled and functional. Work up from the wire.",
        },
        {
          id: "pt-err-9", topic: "VLAN Basics", type: "troubleshooting", difficulty: "scenario",
          question: "After VLANs were added, PCs in VLAN 10 can no longer reach the server that was moved to VLAN 20. Both VLANs work internally. What device/function must be added so they can communicate under control?",
          accepted: ["a router or layer 3 switch doing inter vlan routing", "inter vlan routing via a router on a stick or an l3 switch"],
          required: ["rout"], optional: ["inter vlan", "layer 3", "router on a stick"],
          explanation: "VLANs are separate networks; crossing them requires Layer 3 — a router (router-on-a-stick) or L3 switch, where ACLs can also control the traffic.",
          improved: "Inter-VLAN routing: a router (e.g., router-on-a-stick with subinterfaces) or a Layer 3 switch routes between VLAN 10 and VLAN 20 — and is also where access rules controlling that traffic belong.",
        },
        {
          id: "pt-err-10", topic: "Wireless Setup", type: "troubleshooting", difficulty: "applied",
          question: "A lab wireless client connects to the AP and gets an IP, but can't reach the wired server. The wired PCs can. What connection should you inspect on the topology?",
          accepted: ["the link between the access point and the switch", "the ap's wired uplink to the lan"],
          required: ["uplink"], optional: ["ap to switch", "wired link", "bridge"],
          explanation: "Wireless association and DHCP prove the radio side; failure to cross into the wired LAN implicates the AP's uplink (cable, port, or VLAN).",
          improved: "The AP's wired uplink to the switch — association and DHCP show the wireless side works, so the break is where wireless traffic bridges onto the wired LAN: that cable, its switch port, or the port's VLAN.",
        },
      ],
    },
  ],
});
