import { defineCourse } from "./builder";

export const securityFundamentals = defineCourse({
  id: "security-fundamentals",
  title: "Network Security Fundamentals",
  description:
    "Firewalls, VPNs, authentication, segmentation, threats, encryption, and the habits that keep networks safe.",
  icon: "🛡️",
  modules: [
    {
      id: "sec-perimeter",
      title: "Firewalls, IDS & IPS",
      description: "Perimeter defences: filtering, detection, and prevention.",
      topics: ["Firewalls", "IDS & IPS"],
      questions: [
        {
          id: "sec-per-1", topic: "Firewalls", type: "definition", difficulty: "foundation",
          question: "What does a 'default deny' firewall policy mean, and why is it safer than 'default allow'?",
          accepted: ["everything is blocked unless explicitly permitted, so forgotten rules fail safe", "block all traffic by default and allow only what's needed"],
          required: ["block", "unless"], optional: ["explicitly allowed", "fail safe"],
          explanation: "Default deny blocks all traffic except explicitly permitted flows. Mistakes fail closed (something legitimate breaks) rather than open (something malicious passes).",
          improved: "Default deny blocks everything unless a rule explicitly allows it. It's safer because omissions fail closed — a forgotten rule blocks a legitimate service rather than silently admitting an attacker.",
        },
        {
          id: "sec-per-2", topic: "IDS & IPS", type: "comparison", difficulty: "applied",
          question: "What is the key difference between an IDS and an IPS?",
          accepted: ["an ids detects and alerts, an ips sits inline and actively blocks", "detection versus prevention, ips can stop traffic, ids only warns"],
          required: ["detect", "block"], optional: ["inline", "alert", "prevent"],
          explanation: "IDS monitors and raises alerts; IPS sits inline in the traffic path and can drop malicious packets in real time.",
          improved: "An IDS monitors traffic and alerts on suspected attacks — a smoke detector. An IPS sits inline in the traffic path and actively blocks malicious traffic as it happens — a sprinkler system.",
        },
        {
          id: "sec-per-3", topic: "Firewalls", type: "explain_simply", difficulty: "scenario",
          question: "Explain the purpose of a firewall to a non-technical business manager.",
          accepted: ["it's like a security guard at the entrance checking everything entering or leaving against your rules", "a gatekeeper for your network that only lets approved traffic through"],
          required: ["checks"], optional: ["guard", "gatekeeper", "rules", "entrance", "blocks"],
          mistakes: ["Drowning the manager in ports and protocols — the goal is a clear analogy."],
          explanation: "Good non-technical explanations use an analogy (guard, gatekeeper, door policy) and connect to what the listener cares about: protecting the business.",
          improved: "A firewall is like a security guard at your building's entrance: it checks everything entering or leaving the network against your rules, lets legitimate business traffic pass, and turns away anything suspicious — protecting your systems and data.",
        },
        {
          id: "sec-per-4", topic: "Firewalls", type: "troubleshooting", difficulty: "applied",
          question: "A next-generation firewall claims 'application awareness'. What can it do that a traditional port-based firewall cannot?",
          accepted: ["identify and control the actual application regardless of port, not just allow or deny port numbers", "it recognizes applications inside the traffic even on standard ports"],
          required: ["application"], optional: ["regardless of port", "identify", "inspect"],
          explanation: "Port-based rules assume port = app. NGFWs inspect traffic to identify actual applications (and users), controlling them even when everything rides port 443.",
          improved: "It identifies the actual application inside the traffic — so it can allow web browsing but block file-sharing apps even when both use port 443, something a port-based firewall can't distinguish.",
        },
        {
          id: "sec-per-5", topic: "IDS & IPS", type: "configuration_reasoning", difficulty: "scenario",
          question: "Why might a cautious team deploy a new IPS in 'detect-only' mode for the first few weeks?",
          accepted: ["to tune out false positives before letting it block real traffic", "so misidentified legitimate traffic isn't blocked while the system is tuned"],
          required: ["false positives"], optional: ["tune", "before blocking", "baseline"],
          explanation: "Untuned IPS signatures generate false positives; in blocking mode those become outages. Detect-first lets teams baseline and tune safely.",
          improved: "To tune it safely: fresh IPS deployments produce false positives, and in blocking mode each one is a self-inflicted outage. Detect-only mode reveals what it would have blocked, letting the team tune signatures before enabling enforcement.",
        },
        {
          id: "sec-per-6", topic: "Firewalls", type: "definition", difficulty: "applied",
          question: "What is a DMZ in network design, and what belongs in it?",
          accepted: ["a buffer network between the internet and the internal network hosting public facing servers", "a screened zone for services like web and mail servers that outsiders must reach"],
          required: ["public"], optional: ["buffer", "between internet and internal", "web servers"],
          explanation: "The DMZ hosts internet-facing services (web, mail) in an isolated zone so their compromise doesn't expose the internal network.",
          improved: "A DMZ is a buffer network between the internet and the internal LAN, hosting public-facing servers (web, mail). If one is compromised, the attacker is contained in the DMZ instead of inside the internal network.",
        },
        {
          id: "sec-per-7", topic: "IDS & IPS", type: "troubleshooting", difficulty: "scenario",
          question: "Overnight, the IPS blocked what turned out to be the payroll system's legitimate batch transfer. What two-part response balances security and business?",
          accepted: ["restore the service with a tuned exception and investigate why the signature fired", "add a specific allowance for that flow after verifying it's legitimate, then tune the rule"],
          required: ["exception"], optional: ["verify legitimate", "tune", "investigate", "specific"],
          explanation: "Verify the flow is truly legitimate, restore it via the narrowest possible exception, and tune the signature — don't disable the IPS wholesale.",
          improved: "First verify the transfer really is legitimate, then restore it with the narrowest exception possible (that source, destination, and port — not a broad disable), and tune or report the false-positive signature so it doesn't recur.",
        },
        {
          id: "sec-per-8", topic: "Firewalls", type: "configuration_reasoning", difficulty: "applied",
          question: "Why should firewall rules be reviewed periodically rather than only added to?",
          accepted: ["stale rules accumulate and widen the attack surface, old exceptions may no longer be needed", "unused and forgotten rules create risk and complexity over time"],
          required: ["stale"], optional: ["accumulate", "attack surface", "unused", "audit"],
          explanation: "Rulebases only grow; forgotten exceptions for retired systems become open doors. Regular review prunes risk and keeps the policy understandable.",
          improved: "Rules accumulate: temporary exceptions outlive their purpose and rules for retired systems stay open. Periodic review removes stale entries, shrinking the attack surface and keeping the policy auditable.",
        },
      ],
    },
    {
      id: "sec-access",
      title: "Identity & Access",
      description: "Authentication, MFA, access control, least privilege, and Zero Trust.",
      topics: ["Authentication", "MFA", "Access Control", "Least Privilege", "Zero Trust"],
      questions: [
        {
          id: "sec-acc-1", topic: "MFA", type: "definition", difficulty: "foundation",
          question: "What is multi-factor authentication, and why does it stop most password-theft attacks?",
          accepted: ["it requires a second proof beyond the password, so a stolen password alone is useless", "combining something you know with something you have or are"],
          required: ["second"], optional: ["something you have", "stolen password", "factor"],
          explanation: "MFA combines factors (know/have/are). A phished password fails without the second factor, defeating the most common attack outright.",
          improved: "MFA requires a second, independent proof of identity — typically something you have (phone, key) alongside the password. A stolen password alone then grants nothing, which neutralizes most credential-theft attacks.",
        },
        {
          id: "sec-acc-2", topic: "Least Privilege", type: "definition", difficulty: "applied",
          question: "State the principle of least privilege and give a workplace example.",
          accepted: ["everyone gets only the access their job requires, like accountants not having admin rights on servers", "grant the minimum permissions needed, for example marketing can't open hr records"],
          required: ["minimum"], optional: ["job requires", "only what's needed", "example"],
          explanation: "Least privilege caps every account at what its role needs — limiting both accident damage and what an attacker gains from any single compromise.",
          improved: "Least privilege means each user, account, and system gets only the access its role requires — e.g., a marketing employee can edit the website but cannot open HR records or server settings. Any compromise is then contained to that small slice.",
        },
        {
          id: "sec-acc-3", topic: "Zero Trust", type: "definition", difficulty: "applied",
          question: "Summarise the core idea of Zero Trust in one sentence.",
          accepted: ["never trust by default, verify every user and device for every access regardless of location", "being inside the network grants nothing, everything is authenticated and authorized continuously"],
          required: ["verify"], optional: ["never trust", "regardless of location", "every access"],
          explanation: "Zero Trust drops the castle-and-moat model: network location grants no trust; every access is authenticated, authorized, and continuously evaluated.",
          improved: "Zero Trust means no user or device is trusted by default — even inside the office network — and every access request must be verified based on identity, device health, and context.",
        },
        {
          id: "sec-acc-4", topic: "Authentication", type: "comparison", difficulty: "applied",
          question: "Authentication and authorization are often confused. What question does each answer?",
          accepted: ["authentication asks who are you, authorization asks what are you allowed to do", "authn verifies identity, authz decides permissions"],
          required: ["who", "allowed"], optional: ["identity", "permissions"],
          explanation: "Authentication verifies identity ('who are you?'); authorization decides rights ('what may you do?'). One follows the other.",
          improved: "Authentication answers 'who are you?' — verifying identity through credentials. Authorization answers 'what are you allowed to do?' — the permissions granted after identity is confirmed.",
        },
        {
          id: "sec-acc-5", topic: "MFA", type: "objection_handling", difficulty: "scenario",
          question: "Staff complain MFA prompts slow them down, and a manager suggests disabling it. How would you respond constructively?",
          accepted: ["acknowledge the friction, quantify the risk of disabling, and propose reducing friction with better methods instead of removing protection", "keep the protection but improve the experience with sso, push approvals, remembered devices or passkeys"],
          required: ["friction", "risk"], optional: ["sso", "passkeys", "remembered devices", "acknowledge"],
          explanation: "Don't dismiss the complaint or cave: acknowledge friction, explain the exposure disabling creates, and offer lower-friction MFA (SSO, push, passkeys, trusted devices).",
          improved: "Acknowledge the friction is real, then reframe: disabling MFA reopens the door to the most common attack. Propose reducing friction instead — single sign-on, push-based approvals, remembered trusted devices, or passkeys — keeping the protection while fixing the experience.",
        },
        {
          id: "sec-acc-6", topic: "Access Control", type: "configuration_reasoning", difficulty: "applied",
          question: "Why is role-based access control (RBAC) easier to manage than assigning permissions to individuals one by one?",
          accepted: ["permissions attach to roles so joiners, movers and leavers are handled by changing role membership", "you manage a few roles instead of thousands of individual grants"],
          required: ["role"], optional: ["membership", "joiners", "scale", "consistent"],
          explanation: "RBAC groups permissions into roles; people inherit by role membership. Onboarding/offboarding becomes one membership change, and rights stay consistent and auditable.",
          improved: "With RBAC, permissions attach to roles (e.g., 'Finance', 'Support') and people inherit them by membership. New hires, role changes, and departures become a single membership update instead of dozens of individual grants — consistent and auditable.",
        },
        {
          id: "sec-acc-7", topic: "Least Privilege", type: "troubleshooting", difficulty: "scenario",
          question: "An intern's compromised account was used to delete a production database. What access-control failure does the damage reveal?",
          accepted: ["the intern had far more privilege than the role required, violating least privilege", "excessive permissions, an intern account should never touch production databases"],
          required: ["privilege"], optional: ["excessive", "least privilege", "should not have access"],
          explanation: "The breach is bad; the blast radius is the real finding. An intern account with production-delete rights means least privilege was never applied.",
          improved: "A least-privilege failure: regardless of how the account was compromised, an intern should never have held delete rights on a production database. Access reviews should catch such excessive grants before an attacker does.",
        },
        {
          id: "sec-acc-8", topic: "Authentication", type: "definition", difficulty: "foundation",
          question: "Name the three classic categories of authentication factors.",
          accepted: ["something you know, something you have, something you are", "knowledge, possession, and inherence factors"],
          required: ["know", "have", "are"],
          explanation: "Know (password/PIN), have (phone, token), are (fingerprint, face). True MFA combines different categories.",
          improved: "Something you know (password, PIN), something you have (phone, hardware token), and something you are (fingerprint, face) — strong MFA combines factors from different categories.",
        },
        {
          id: "sec-acc-9", topic: "Zero Trust", type: "architecture_reasoning", difficulty: "scenario",
          question: "A company's VPN grants full network access to anyone who connects. How would a Zero Trust approach change this?",
          accepted: ["replace broad network access with per application access verified by identity and device posture", "each user reaches only the specific apps they're authorized for, with continuous verification"],
          required: ["per application"], optional: ["identity", "device posture", "instead of full network", "least privilege"],
          explanation: "Zero Trust replaces flat VPN access with identity- and posture-checked access to specific applications — a compromised laptop no longer roams the whole LAN.",
          improved: "Instead of the VPN granting the whole network, each user gets access only to the specific applications their role permits, verified per request against identity and device health. A stolen credential then exposes a few apps, not the entire internal network.",
        },
        {
          id: "sec-acc-10", topic: "Access Control", type: "troubleshooting", difficulty: "applied",
          question: "Why is promptly disabling accounts of departed employees a critical security control?",
          accepted: ["orphaned accounts are a favorite attack path since nobody notices their use", "ex employees or attackers can use still active credentials undetected"],
          required: ["account"], optional: ["orphaned", "still active", "undetected", "offboarding"],
          explanation: "Live accounts of departed staff = valid credentials nobody monitors. Attackers (and disgruntled ex-employees) exploit exactly these.",
          improved: "A departed employee's live account is a set of valid credentials that no one is watching — a perfect path for the ex-employee or any attacker who obtains them. Disabling on departure day closes it; access reviews catch stragglers.",
        },
        {
          id: "sec-acc-11", topic: "MFA", type: "comparison", difficulty: "applied",
          question: "Why are authenticator apps or hardware keys considered stronger MFA than SMS codes?",
          accepted: ["sms can be intercepted or stolen via sim swapping, app and key based factors resist that", "sim swap attacks defeat sms, keys and apps bind the factor to the device"],
          required: ["sms"], optional: ["sim swap", "intercept", "phishing resistant", "hardware key"],
          explanation: "SMS is vulnerable to SIM-swap and interception. App-based TOTP/push is better; hardware keys (FIDO2) are phishing-resistant — the gold standard.",
          improved: "SMS codes can be stolen via SIM-swapping or interception. Authenticator apps bind the factor to a device, and hardware keys go further — they're phishing-resistant because they cryptographically verify the real site before answering.",
        },
        {
          id: "sec-acc-12", topic: "Zero Trust", type: "explain_simply", difficulty: "scenario",
          question: "Explain Zero Trust to a sceptical office manager using a physical-world analogy.",
          accepted: ["like a building where your badge is checked at every door, not just the front entrance", "instead of trusting anyone inside the lobby, each room checks identity again"],
          required: ["every door"], optional: ["badge", "not just the entrance", "each room"],
          explanation: "The badge-at-every-door analogy lands: getting into the lobby (network) no longer opens every room (system); each door re-checks who you are.",
          improved: "Traditional security is a building where passing the front desk lets you wander everywhere. Zero Trust checks your badge at every single door — being inside the lobby proves nothing, so an intruder who sneaks past reception still can't open any room.",
        },
      ],
    },
    {
      id: "sec-network",
      title: "Network Protection",
      description: "Segmentation, VLANs, VPNs, secure remote access, and public Wi-Fi risks.",
      topics: ["Segmentation", "VLANs", "VPNs", "Remote Access", "Public Wi-Fi"],
      questions: [
        {
          id: "sec-net-1", topic: "Segmentation", type: "definition", difficulty: "applied",
          question: "How does network segmentation limit the damage of a breach?",
          accepted: ["an attacker who compromises one segment can't move laterally into others", "it contains the compromise to one zone instead of the whole network"],
          required: ["contain"], optional: ["lateral movement", "one segment", "isolat"],
          explanation: "Segmentation builds internal walls: compromising a laptop in one zone doesn't open servers in another; lateral movement hits controlled boundaries.",
          improved: "Segmentation divides the network into isolated zones with controlled crossings, so an attacker who compromises one device is contained in that zone — lateral movement toward servers or payment systems hits a wall instead of an open network.",
        },
        {
          id: "sec-net-2", topic: "VPNs", type: "definition", difficulty: "foundation",
          question: "What protection does a VPN give an employee working from a hotel?",
          accepted: ["an encrypted tunnel to the company so the hotel network can't read or tamper with the traffic", "it encrypts everything between the laptop and the office"],
          required: ["encrypt"], optional: ["tunnel", "hotel can't read", "company network"],
          explanation: "The VPN wraps all traffic in an encrypted tunnel to the company — the untrusted hotel network sees only ciphertext.",
          improved: "The VPN builds an encrypted tunnel from the laptop to the company network, so the untrusted hotel Wi-Fi (and anyone snooping on it) sees only unreadable ciphertext instead of emails, passwords, and files.",
        },
        {
          id: "sec-net-3", topic: "VLANs", type: "architecture_reasoning", difficulty: "scenario",
          question: "An office puts staff, guests, IP phones, and security cameras all on one flat network. Give two concrete risks and the standard fix.",
          accepted: ["guests can reach internal systems and one compromised camera exposes everything, separate them with vlans", "no isolation means lateral movement and iot compromise spreading, use vlans per device class"],
          required: ["vlan"], optional: ["guests reach internal", "camera", "lateral", "separate"],
          explanation: "Flat networks let guests probe internal systems and turn a hacked camera into a beachhead. VLAN-per-class (staff/guest/voice/IoT) with firewall rules between is the standard cure.",
          improved: "Risks: guest devices can reach internal file shares and printers, and one compromised camera (IoT is rarely patched) becomes a launchpad against everything else. Fix: separate VLANs for staff, guests, voice, and cameras with firewall rules controlling traffic between them.",
        },
        {
          id: "sec-net-4", topic: "Public Wi-Fi", type: "explain_simply", difficulty: "applied",
          question: "Why is open café Wi-Fi risky, explained to a non-technical friend?",
          accepted: ["anyone nearby can watch unprotected traffic, like having a conversation in a crowded room", "the network is shared with strangers who may snoop or impersonate it"],
          required: ["anyone"], optional: ["snoop", "eavesdrop", "fake hotspot", "strangers"],
          explanation: "Open Wi-Fi = shouting in a crowded room: nearby strangers can capture unencrypted traffic or stand up a fake hotspot with the same name.",
          improved: "On open Wi-Fi you're sharing the airwaves with strangers — anyone nearby can capture what your device sends unencrypted, and attackers can even set up a fake hotspot with the café's name. HTTPS and a VPN are your seatbelt there.",
        },
        {
          id: "sec-net-5", topic: "Remote Access", type: "troubleshooting", difficulty: "scenario",
          question: "An admin exposed a server's remote desktop (RDP) directly to the internet 'for convenience'. Why is this dangerous, and what is the safer pattern?",
          accepted: ["internet facing rdp is constantly brute forced and exploited, put it behind a vpn or gateway with mfa", "exposed rdp is a top ransomware entry point, require vpn plus mfa instead"],
          required: ["vpn"], optional: ["brute force", "ransomware", "mfa", "gateway", "exposed"],
          explanation: "Internet-facing RDP is among the most attacked services on earth — brute-forced and exploited into ransomware constantly. Access belongs behind VPN/ZTNA with MFA.",
          improved: "Exposed RDP is one of the most attacked services on the internet — scanned, brute-forced, and a leading ransomware entry point. The safe pattern: no direct exposure; reach it through a VPN or zero-trust gateway with MFA enforced.",
        },
        {
          id: "sec-net-6", topic: "Segmentation", type: "architecture_reasoning", difficulty: "scenario",
          question: "A retailer must protect its card-payment systems. Why do payment-security standards effectively require network segmentation?",
          accepted: ["isolating the payment zone shrinks what can touch card data and what must be audited", "segmentation reduces the scope of compliance and blocks the rest of the network from reaching payment systems"],
          required: ["isolat"], optional: ["scope", "card data", "pci", "reduce"],
          explanation: "Segmenting the cardholder zone means fewer systems can touch card data — shrinking both attack paths and the audited compliance scope.",
          improved: "Because isolating payment systems in their own tightly-controlled segment means only that small zone can touch card data — the attack surface shrinks, and so does the compliance scope: auditors examine the payment segment, not the entire corporate network.",
        },
        {
          id: "sec-net-7", topic: "VPNs", type: "comparison", difficulty: "applied",
          question: "What's the difference between a remote-access VPN and a site-to-site VPN?",
          accepted: ["remote access connects an individual device to the network, site to site permanently links whole office networks", "one is per user, the other joins two networks over the internet"],
          required: ["individual", "site"], optional: ["whole networks", "permanent", "per user"],
          explanation: "Remote-access: one user's device tunnels in. Site-to-site: routers/firewalls maintain a standing tunnel joining entire office networks.",
          improved: "A remote-access VPN connects an individual user's device into the company network. A site-to-site VPN is a standing encrypted tunnel between two locations' routers, joining entire office networks so every device can communicate.",
        },
        {
          id: "sec-net-8", topic: "Public Wi-Fi", type: "troubleshooting", difficulty: "applied",
          question: "At an airport you see two networks: 'Airport_Free_WiFi' and 'Airport Free WiFi Official'. What attack could one of these be, and how does it work?",
          accepted: ["an evil twin fake hotspot that mimics the real network to intercept traffic", "a rogue access point impersonating the legitimate wifi"],
          required: ["fake"], optional: ["evil twin", "rogue", "intercept", "impersonat"],
          explanation: "Evil-twin hotspots mimic legitimate SSIDs; connecting routes your traffic through the attacker's device for capture and manipulation.",
          improved: "One may be an 'evil twin' — an attacker's hotspot broadcasting a look-alike name. Devices that join it route all traffic through the attacker, who can capture credentials and inject fake pages. Verify SSIDs with staff and keep a VPN on.",
        },
        {
          id: "sec-net-9", topic: "Remote Access", type: "configuration_reasoning", difficulty: "applied",
          question: "Beyond a password, name two conditions a well-configured remote-access system checks before letting a laptop connect.",
          accepted: ["a second authentication factor and the device's security posture like patches and antivirus", "mfa plus device compliance checks"],
          required: ["mfa"], optional: ["device posture", "compliance", "patched", "certificate", "antivirus"],
          explanation: "Modern remote access verifies the user (MFA) and the device (posture: patched OS, disk encryption, EDR present, company-issued certificate).",
          improved: "Multi-factor authentication for the user, and device posture for the laptop — is it company-managed, patched, encrypted, running endpoint protection? Identity plus device health, not just a password.",
        },
        {
          id: "sec-net-10", topic: "VLANs", type: "troubleshooting", difficulty: "applied",
          question: "Guests on the guest VLAN can suddenly print to internal office printers. What boundary control has failed or been misconfigured?",
          accepted: ["the firewall or acl rules between the guest vlan and internal vlan", "inter vlan filtering, the rules separating guest from internal traffic"],
          required: ["between"], optional: ["acl", "firewall rule", "inter vlan", "misconfigured"],
          explanation: "VLANs separate; rules at the L3 boundary enforce. Guests reaching internal printers means the inter-VLAN ACL/firewall policy broke or was bypassed.",
          improved: "The inter-VLAN filtering — the ACL or firewall policy that governs traffic crossing from the guest VLAN into internal networks. Segmentation only works if the Layer 3 boundary between segments enforces the rules.",
        },
      ],
    },
    {
      id: "sec-threats",
      title: "Threats: Phishing, Malware & Ransomware",
      description: "Recognising and responding to the most common attacks.",
      topics: ["Phishing", "Malware", "Ransomware"],
      questions: [
        {
          id: "sec-thr-1", topic: "Phishing", type: "definition", difficulty: "foundation",
          question: "Name three tell-tale signs that an email is a phishing attempt.",
          accepted: ["urgency, mismatched sender addresses, and suspicious links or attachments", "pressure to act fast, odd sender domain, links that don't match the text, requests for credentials"],
          required: [], optional: ["urgency", "sender", "links", "attachments", "credentials", "spelling", "mismatch", "pressure"],
          explanation: "Classic markers: manufactured urgency, sender domains that almost match real ones, hover-revealed mismatched links, unexpected attachments, credential requests.",
          improved: "Manufactured urgency ('act in 24 hours!'), a sender address that almost-but-not-quite matches the real organisation, and links whose true destination (revealed on hover) doesn't match the displayed text — plus any unexpected request for credentials.",
        },
        {
          id: "sec-thr-2", topic: "Ransomware", type: "definition", difficulty: "applied",
          question: "What does ransomware do, and what single preparation most limits its damage?",
          accepted: ["it encrypts your data and demands payment, offline tested backups are the best protection", "locks files for ransom, recoverable if you keep isolated backups"],
          required: ["encrypt", "backup"], optional: ["ransom", "offline", "tested", "payment"],
          explanation: "Ransomware encrypts data (often exfiltrating first) and extorts payment. Offline, tested backups turn catastrophe into restoration.",
          improved: "Ransomware encrypts your files and demands payment for the key — modern gangs also steal data first. The single best preparation: offline (or immutable), regularly tested backups, so you can restore without paying.",
        },
        {
          id: "sec-thr-3", topic: "Phishing", type: "troubleshooting", difficulty: "scenario",
          question: "An employee clicked a phishing link and entered their password before realising. As the responder, what are your first three actions?",
          accepted: ["reset the password, revoke active sessions, and check for suspicious activity while looking for other recipients", "change credentials immediately, invalidate sessions and mfa tokens, investigate account activity and scope"],
          required: ["password", "sessions"], optional: ["reset", "revoke", "activity", "scope", "other recipients"],
          explanation: "Speed matters: reset credentials, kill active sessions/tokens, then hunt — account activity, mail rules, and who else got the email.",
          improved: "Reset the password immediately, revoke all active sessions and tokens (the attacker may already be logged in), then investigate: account activity, new mail-forwarding rules, and which other employees received the same phish. Praise the report — it enables the fast response.",
        },
        {
          id: "sec-thr-4", topic: "Malware", type: "definition", difficulty: "foundation",
          question: "What is malware, and name two common ways it gets onto business machines.",
          accepted: ["malicious software, arriving via email attachments and malicious downloads", "software designed to harm, spread through phishing attachments, infected downloads, or usb drives"],
          required: ["malicious"], optional: ["attachments", "downloads", "usb", "email", "exploits"],
          explanation: "Malware = software built to harm (steal, spy, encrypt, hijack). Top entry paths: email attachments/links, trojaned downloads, USB media, unpatched exploits.",
          improved: "Malware is software designed to cause harm — stealing data, spying, or encrypting files. It most commonly arrives through email attachments and links, malicious or trojaned downloads, and infected USB drives.",
        },
        {
          id: "sec-thr-5", topic: "Ransomware", type: "business_value", difficulty: "scenario",
          question: "A CFO asks why they should fund ransomware defences when the company has 'nothing hackers would want'. What's the flaw in that reasoning?",
          accepted: ["ransomware doesn't steal interesting data, it sells your own access back to you, any business that needs its systems is a target", "the value isn't your data to others, it's your operations to you, downtime is the leverage"],
          required: ["your own"], optional: ["downtime", "operations", "any business", "automated attacks"],
          explanation: "Ransomware monetizes the victim's own dependency: it doesn't need interesting data, just data YOU need. Attacks are automated and untargeted — every business qualifies.",
          improved: "Ransomware doesn't care whether outsiders want your data — it sells your own systems back to you. If downtime costs money (payroll, orders, production), you're a target. And attacks are automated at scale: they find you, not the other way round.",
        },
        {
          id: "sec-thr-6", topic: "Phishing", type: "configuration_reasoning", difficulty: "applied",
          question: "Beyond user training, name two technical controls that reduce phishing success.",
          accepted: ["email filtering and mfa, plus phishing resistant authentication and link protection", "spam and impersonation filters, multifactor auth so stolen passwords fail, dns filtering"],
          required: [], optional: ["email filtering", "mfa", "link protection", "dns filtering", "passkeys", "dmarc", "banner"],
          explanation: "Layered controls: filtering (spam/impersonation/DMARC), URL rewriting, external-sender banners, DNS filtering — and MFA/passkeys so stolen credentials fail anyway.",
          improved: "Email security filtering (spam, impersonation detection, DMARC enforcement, link scanning) to stop most phish arriving, and MFA — ideally phishing-resistant passkeys — so that even a successfully stolen password doesn't grant access.",
        },
        {
          id: "sec-thr-7", topic: "Malware", type: "troubleshooting", difficulty: "scenario",
          question: "A PC shows signs of infection: strange pop-ups and unknown processes. Why should you isolate it from the network BEFORE deep investigation?",
          accepted: ["to stop the malware spreading laterally or communicating with its controller while you investigate", "containment first, disconnect it so it can't infect others or exfiltrate data"],
          required: ["spread"], optional: ["containment", "lateral", "exfiltrate", "command and control"],
          explanation: "Containment precedes forensics: while you investigate, live malware may be spreading to shares/peers and exfiltrating data to its C2 server.",
          improved: "Containment comes first: while you investigate, active malware could be spreading to file shares and other machines, or exfiltrating data to its command-and-control server. Disconnecting the machine freezes the blast radius; analysis can proceed safely afterwards.",
        },
        {
          id: "sec-thr-8", topic: "Ransomware", type: "architecture_reasoning", difficulty: "scenario",
          question: "Why do ransomware crews specifically hunt for and destroy backups before triggering encryption?",
          accepted: ["backups let victims recover without paying, destroying them maximizes the pressure to pay", "the ransom only works if restoration is impossible"],
          required: ["pay"], optional: ["recover", "pressure", "leverage", "offline"],
          explanation: "Backups are the victim's exit — destroying them removes the alternative to paying. Hence offline/immutable backups: unreachable from the compromised network.",
          improved: "Because backups are the victim's escape route — a company that can restore won't pay. That's exactly why backups must be offline or immutable: stored where a compromised network account can't reach and delete them.",
        },
        {
          id: "sec-thr-9", topic: "Phishing", type: "definition", difficulty: "applied",
          question: "What makes 'spear phishing' more dangerous than ordinary mass phishing?",
          accepted: ["it is personalized to a specific target using researched details, so it's far more convincing", "targeted phishing crafted for one person or company with real context"],
          required: ["target"], optional: ["personalized", "researched", "specific", "convincing"],
          explanation: "Spear phishing is researched and personal — real names, projects, suppliers — so trained users still fall for it at much higher rates than generic spam.",
          improved: "Spear phishing is targeted: the attacker researches the victim and weaves in real details — their boss's name, a live project, an actual supplier — making the message convincing enough to fool even security-aware staff.",
        },
        {
          id: "sec-thr-10", topic: "Malware", type: "comparison", difficulty: "applied",
          question: "What distinguishes a worm from other malware, and why are worms especially dangerous on flat networks?",
          accepted: ["a worm spreads itself automatically without user action, so on an unsegmented network it can infect everything in minutes", "self propagating malware, no clicks needed, flat networks let it reach every machine"],
          required: ["spread"], optional: ["self propagating", "no user action", "automatic", "flat network"],
          explanation: "Worms self-propagate by exploiting reachable services — no clicks required. On a flat, unsegmented network every machine is reachable, so infection is near-instant and total.",
          improved: "A worm spreads by itself, exploiting vulnerable services across the network without anyone clicking anything. On a flat network every machine is directly reachable, so one infection can become hundreds in minutes — segmentation is what breaks that chain.",
        },
      ],
    },
    {
      id: "sec-data-cloud",
      title: "Encryption, Cloud & Endpoint Security",
      description: "Encryption basics, security policies, cloud security, and endpoint protection.",
      topics: ["Encryption", "Security Policies", "Cloud Security", "Endpoint Security"],
      questions: [
        {
          id: "sec-dat-1", topic: "Encryption", type: "definition", difficulty: "foundation",
          question: "In plain terms, what does encryption do to data, and who can undo it?",
          accepted: ["it scrambles data so only someone with the right key can read it", "converts readable data into ciphertext reversible only with the key"],
          required: ["key"], optional: ["scramble", "unreadable", "ciphertext"],
          explanation: "Encryption transforms readable data into ciphertext; only holders of the correct key can reverse it. Intercepted ciphertext is useless.",
          improved: "Encryption scrambles data into unreadable ciphertext using a key; only someone holding the right key can turn it back into the original. Anyone who intercepts it without the key gets meaningless noise.",
        },
        {
          id: "sec-dat-2", topic: "Encryption", type: "comparison", difficulty: "applied",
          question: "What's the difference between encryption 'in transit' and 'at rest', with one example of each?",
          accepted: ["in transit protects data moving over networks like https, at rest protects stored data like disk encryption", "moving versus stored, tls for connections, bitlocker for drives"],
          required: ["transit", "rest"], optional: ["https", "tls", "disk encryption", "stored", "moving"],
          explanation: "In transit: protecting data on the wire (HTTPS/TLS, VPN). At rest: protecting stored data (BitLocker/FileVault, encrypted databases). Full protection needs both.",
          improved: "In transit protects data as it moves across networks — HTTPS/TLS securing a web session. At rest protects stored data — full-disk encryption on a laptop, so a stolen device yields nothing. Complete protection requires both.",
        },
        {
          id: "sec-dat-3", topic: "Cloud Security", type: "definition", difficulty: "applied",
          question: "What does the cloud 'shared responsibility model' mean for a company using AWS or Azure?",
          accepted: ["the provider secures the infrastructure, the customer secures their own data, configuration, and access", "cloud vendors protect the platform, you're responsible for what you build and configure on it"],
          required: ["provider", "customer"], optional: ["configuration", "data", "access", "infrastructure"],
          explanation: "Provider secures OF the cloud (facilities, hardware, platform); customer secures IN the cloud (data, identity, configuration). Most breaches are customer-side misconfiguration.",
          improved: "The provider secures the underlying infrastructure — data centres, hardware, the platform itself. The customer remains responsible for what they do in it: their data, user access, and configuration. Most cloud breaches come from the customer side — misconfigured storage and weak access controls.",
        },
        {
          id: "sec-dat-4", topic: "Endpoint Security", type: "definition", difficulty: "applied",
          question: "Modern 'EDR' tools go beyond classic antivirus. What's the key difference?",
          accepted: ["edr continuously monitors behavior and enables detection and response, antivirus just matches known signatures", "behavioral detection, investigation and response versus signature scanning"],
          required: ["behavio"], optional: ["signatures", "response", "monitor", "investigate"],
          explanation: "AV matches known-bad signatures; EDR watches behaviour (processes, connections, changes), catches novel attacks, and supports investigation/response (isolate host, kill process).",
          improved: "Classic antivirus matches files against known-malware signatures. EDR continuously monitors behaviour — processes, connections, changes — so it catches novel attacks, and it adds response: analysts can investigate the timeline, isolate the host, and kill malicious processes remotely.",
        },
        {
          id: "sec-dat-5", topic: "Security Policies", type: "business_value", difficulty: "scenario",
          question: "A growing startup says written security policies are 'bureaucracy'. Give two practical reasons they matter.",
          accepted: ["they set consistent expectations for staff and are required by customers, insurers and regulators", "people can't follow rules that don't exist, and enterprise deals and cyber insurance demand documented policies"],
          required: [], optional: ["consistent", "expectations", "customers", "insurance", "compliance", "incident response", "documented"],
          explanation: "Policies make expectations explicit (what staff may do, how incidents run) and unlock business: enterprise customers, insurers, and regulators all demand documented security.",
          improved: "First, staff can't follow expectations that were never written — policies define how data is handled and what happens in an incident before the crisis. Second, they're commercially required: enterprise customers' vendor reviews, cyber-insurance applications, and regulators all ask for documented policies.",
        },
        {
          id: "sec-dat-6", topic: "Cloud Security", type: "troubleshooting", difficulty: "scenario",
          question: "A company's cloud storage bucket containing customer files was found publicly accessible. What class of failure is this, and what practice prevents it?",
          accepted: ["a misconfiguration, prevented by secure defaults, configuration audits and posture management tools", "cloud misconfiguration, fix with private by default settings and automated compliance scanning"],
          required: ["misconfigur"], optional: ["audit", "posture management", "private by default", "scanning"],
          explanation: "Not a sophisticated hack — a misconfiguration, the top cloud breach cause. Prevention: private-by-default, IaC review, and continuous posture scanning (CSPM).",
          improved: "A cloud misconfiguration — the most common cause of cloud data exposure, requiring no 'hacking' at all. Prevention: private-by-default settings, peer-reviewed infrastructure-as-code, and automated posture scanning that continuously flags publicly exposed resources.",
        },
        {
          id: "sec-dat-7", topic: "Encryption", type: "explain_simply", difficulty: "scenario",
          question: "Explain to a non-technical customer what the padlock icon in their browser actually guarantees — and one thing it does NOT guarantee.",
          accepted: ["it means the connection is encrypted so others can't read it, but it doesn't mean the site itself is trustworthy", "the traffic is private in transit, yet a scam site can also have a padlock"],
          required: ["encrypt", "not"], optional: ["trustworthy", "scam sites", "in transit", "private"],
          explanation: "The padlock = encrypted connection to that site. It says nothing about the site's honesty — phishing sites use HTTPS too.",
          improved: "The padlock means your connection to the site is encrypted — nobody in between can read what you send. It does NOT mean the site itself is legitimate: scam and phishing sites use padlocks too, so the lock protects the pipe, not the destination.",
        },
        {
          id: "sec-dat-8", topic: "Endpoint Security", type: "configuration_reasoning", difficulty: "applied",
          question: "Why is prompt operating-system patching considered one of the highest-value security habits?",
          accepted: ["most attacks exploit known vulnerabilities that patches have already fixed", "patching closes published holes attackers actively scan for"],
          required: ["known"], optional: ["vulnerabilities", "patch", "exploit", "already fixed"],
          explanation: "Attackers overwhelmingly exploit KNOWN, already-patched vulnerabilities — reverse-engineering fixes to hit the unpatched. Patching promptly removes the easy wins.",
          improved: "Because most successful attacks exploit known vulnerabilities for which patches already exist — attackers reverse-engineer each fix and scan for machines that haven't applied it. Prompt patching removes the easiest, most-used attack path.",
        },
        {
          id: "sec-dat-9", topic: "Security Policies", type: "configuration_reasoning", difficulty: "applied",
          question: "What is an incident response plan, and why must it be written BEFORE an incident?",
          accepted: ["a predefined playbook for handling security incidents, because during a crisis is the worst time to improvise", "documented steps, roles and contacts for breaches, prepared calmly in advance"],
          required: ["plan"], optional: ["roles", "before", "improvise", "playbook", "contacts"],
          explanation: "An IR plan pre-decides roles, steps, and contacts. Mid-breach — systems down, pressure high — is the worst possible moment to invent a process.",
          improved: "An incident response plan is the pre-written playbook: who leads, how to contain, whom to notify (legal, insurer, customers), how to recover. It must exist beforehand because a live breach — with systems down and executives panicking — is the worst moment to improvise decisions.",
        },
        {
          id: "sec-dat-10", topic: "Cloud Security", type: "troubleshooting", difficulty: "scenario",
          question: "An attacker logged into a company's cloud admin console from abroad using a stolen password. Which two missing controls does this incident expose?",
          accepted: ["no mfa on admin accounts and no conditional access or anomaly detection on logins", "multifactor authentication and login monitoring or geo restrictions were absent"],
          required: ["mfa"], optional: ["conditional access", "monitoring", "anomal", "geo", "alerting"],
          explanation: "A password alone opening admin access = no MFA (inexcusable for admin) and no conditional-access/impossible-travel detection to flag the anomalous login.",
          improved: "First, MFA on admin accounts — a stolen password should never suffice for the most privileged console. Second, login monitoring/conditional access — an admin sign-in from an unusual country should have been challenged or at least alerted on, not silently accepted.",
        },
      ],
    },
  ],
});
