import { defineCourse } from "./builder";

/** Customer-facing Solution Engineer practice: discovery, diagnosis,
 *  recommendation, communication, objections, architecture, and demos. */
export const solutionEngineerScenarios = defineCourse({
  id: "solution-engineer-scenarios",
  title: "Solution Engineer Customer Scenarios",
  description:
    "Think like a Solution Engineer: ask before answering, diagnose from symptoms, translate technology into business value, and handle objections honestly.",
  icon: "🤝",
  modules: [
    {
      id: "se-discovery",
      title: "Discovery Questions",
      description: "Clarify before recommending: scope, impact, history, and success criteria.",
      topics: ["Discovery"],
      questions: [
        {
          id: "se-dis-1", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "A customer says, 'Our network is very slow.' What would you ask first?",
          accepted: ["who is affected and which applications, and when did it start", "i'd clarify the scope, which users, apps, locations, and whether it's constant or intermittent"],
          required: ["ask"], optional: ["who is affected", "which applications", "when did it start", "intermittent", "locations", "scope"],
          mistakes: ["Jumping straight to recommending faster hardware before understanding the problem."],
          explanation: "Great SEs clarify before diagnosing: 'slow' could be Wi-Fi, one app, one site, or the ISP. Scope questions (who/what/when/where) shrink the space fast.",
          improved: "I'd ask clarifying questions before proposing anything: Who is affected — everyone or one team? Which applications feel slow? When did it start, and is it constant or intermittent? Wired, wireless, or both? One location or all?",
        },
        {
          id: "se-dis-2", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "A customer opens with: 'We need new switches.' What should you understand before discussing any product?",
          accepted: ["why they believe they need them, what problem or trigger is behind the request", "the underlying problem, current environment, and what outcome they expect"],
          required: ["why"], optional: ["problem", "trigger", "outcome", "current environment"],
          mistakes: ["Taking the self-diagnosis at face value and quoting switches immediately."],
          explanation: "Customers often prescribe solutions rather than describe problems. The trigger behind 'new switches' — outage? slowness? audit? growth? — may point somewhere else entirely.",
          improved: "I'd explore the 'why' behind the request: What's prompting this — performance issues, an outage, growth, end-of-life gear? What would success look like afterwards? The real problem might need something other than switches.",
        },
        {
          id: "se-dis-3", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "During discovery, a customer mentions 'the Wi-Fi is unusable in the mornings'. Which follow-up questions extract the most diagnostic value?",
          accepted: ["what happens in the mornings, where exactly, how many people, and what changed", "is it all areas or specific ones, does it correlate with everyone arriving, which times exactly"],
          required: ["morning"], optional: ["where", "how many", "arriv", "specific areas", "what changed"],
          explanation: "A time-correlated symptom begs time-correlated questions: what coincides with mornings? (Everyone arriving = capacity; backups running = utilization; specific rooms = coverage.)",
          improved: "I'd dig into the time pattern: What exactly happens each morning — is it when everyone arrives and connects at once? Is it building-wide or in specific areas? How many people share those areas? Any scheduled jobs like backups running then?",
        },
        {
          id: "se-dis-4", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "Why should 'What have you already tried?' be part of almost every discovery conversation?",
          accepted: ["it avoids repeating failed steps, reveals clues from what didn't work, and respects their effort", "previous attempts narrow the cause and show their expectations and expertise"],
          required: ["tried"], optional: ["avoid repeating", "clues", "narrow", "respect"],
          explanation: "Prior attempts eliminate hypotheses ('rebooting didn't help'), surface clues, calibrate the customer's expertise, and prevent insulting them with obvious suggestions.",
          improved: "It prevents me suggesting things they've already done, and every failed attempt is diagnostic data — if replacing the AP didn't help, coverage probably isn't the issue. It also shows respect for their effort and calibrates how technical the conversation can be.",
        },
        {
          id: "se-dis-5", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "A customer wants a quote 'for a firewall' by Friday. Beyond the deadline, name four things you'd need to learn to quote responsibly.",
          accepted: ["their internet bandwidth, user count, required features like vpn or filtering, and what it must protect", "sizing inputs, throughput, users, sites, features, compliance requirements, and existing infrastructure"],
          required: ["users"], optional: ["bandwidth", "throughput", "features", "vpn", "sites", "compliance", "existing"],
          explanation: "Firewalls are sized and featured to fit: throughput, user/site count, feature needs (VPN, IPS, filtering), compliance drivers, and what's already deployed.",
          improved: "Internet bandwidth and expected throughput (sizing), number of users and sites (scale), required features — VPN, intrusion prevention, content filtering (model selection), and any compliance requirements or existing infrastructure it must integrate with.",
        },
        {
          id: "se-dis-6", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "What is the value of asking a customer 'What does success look like?' before designing anything?",
          accepted: ["it defines measurable acceptance criteria and aligns the solution to their actual goal", "you learn the outcome they're buying, which guides scope and proves value later"],
          required: ["success"], optional: ["criteria", "outcome", "measure", "goal", "align"],
          explanation: "Success criteria turn vague desires into testable outcomes, prevent scope drift, and give you the yardstick for proving value at the end.",
          improved: "It converts a vague request into concrete acceptance criteria — 'video calls stop dropping' or 'store opens by March'. That shapes the design, prevents scope creep, and gives us both an agreed measure to demonstrate success against later.",
        },
        {
          id: "se-dis-7", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "'Everything breaks at random times,' says a frustrated IT manager. How do you turn 'random' into useful data?",
          accepted: ["ask for specific examples with times and symptoms, and start a log correlating incidents with circumstances", "get concrete incidents, what, when, who, and look for patterns across them"],
          required: ["specific"], optional: ["examples", "times", "log", "pattern", "correlate"],
          explanation: "'Random' usually means 'pattern not yet found'. Concrete incidents (when, what, who, where) almost always reveal correlations — time of day, location, load, weather.",
          improved: "I'd ask for three or four concrete recent examples — exact time, what broke, for whom — and suggest logging incidents going forward. 'Random' failures almost always show a pattern once written down: same time of day, same area, same activity.",
        },
        {
          id: "se-dis-8", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "Why ask about business impact ('what does this cost you?') and not just technical symptoms?",
          accepted: ["impact sets priority and budget context and connects the fix to business value", "it quantifies urgency and justifies investment, and shows which problems matter most"],
          required: ["impact"], optional: ["priority", "budget", "urgency", "justif", "value"],
          explanation: "Impact converts symptoms into priorities and budgets: an annoyance and a production-stopper get very different responses — and the fix's value becomes quantifiable.",
          improved: "Business impact tells me how urgent and valuable the fix is: 'the warehouse stops shipping for an hour a day' justifies a very different investment than a minor annoyance. It also lets me express the eventual solution in terms the business cares about.",
        },
        {
          id: "se-dis-9", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "A customer reports intermittent connection drops. Why is 'Were any changes made recently?' such a high-yield question?",
          accepted: ["most sudden problems trace to a recent change, finding it can identify the cause immediately", "new equipment, updates or config changes are the most common trigger of new symptoms"],
          required: ["change"], optional: ["recent", "update", "new equipment", "trigger"],
          explanation: "Networks rarely degrade spontaneously — new firmware, rules, devices, or construction usually precede new symptoms. The change is often the answer.",
          improved: "Because a working network rarely breaks by itself: a firmware update, new firewall rule, added equipment, or even office construction usually precedes new symptoms. Identifying the change often is the diagnosis.",
        },
        {
          id: "se-dis-10", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "You're asked to help a customer 'modernise the network'. Which stakeholders beyond IT should discovery include, and why?",
          accepted: ["business leaders, finance, operations and end users, since they define goals, budget, constraints and pain", "the people affected and paying, executives for direction, users for real pain points, facilities for constraints"],
          required: ["business"], optional: ["finance", "users", "executives", "operations", "facilities"],
          explanation: "IT owns machinery; the business owns purpose. Executives (direction/budget), department heads (workflows), end users (real pain), facilities (physical constraints) all shape the right design.",
          improved: "Business leadership (what is the modernisation FOR — growth, new premises, cost?), finance (budget and cost model), department heads and end users (actual daily pain points), and facilities (physical and building constraints). IT alone can't define the goal.",
        },
        {
          id: "se-dis-11", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "'Does the problem affect wired users, wireless users, or both?' — what makes this single question so powerful in network discovery?",
          accepted: ["it immediately splits the problem domain, both points at shared infrastructure, wireless only points at wifi", "one answer eliminates half the network, isolating wifi versus core versus internet"],
          required: ["wireless"], optional: ["split", "isolate", "shared infrastructure", "narrow"],
          explanation: "One answer halves the search space: wireless-only → RF/AP domain; both → shared core/internet; wired-only → switching/cabling. Cheap question, huge information.",
          improved: "The answer instantly halves the problem space: wireless-only implicates the Wi-Fi layer (APs, coverage, channels); both implicates shared infrastructure (core switch, firewall, ISP); wired-only points at switching or cabling. One question, half the diagnosis.",
        },
        {
          id: "se-dis-12", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "A prospect says 'we want what our competitor has'. What discovery must happen before mirroring a competitor's setup?",
          accepted: ["their own requirements, environment and goals, since the competitor's context may not match theirs", "what outcome they admire and whether their size, apps, budget and constraints actually match"],
          required: ["their own"], optional: ["requirements", "context", "differ", "outcome they admire", "goals"],
          explanation: "Copying artifacts without context copies costs without fit. Find what outcome they envy, then design for THEIR size, apps, sites, budget, and constraints.",
          improved: "I'd ask what specifically they admire about the competitor's setup — the outcome, not the equipment — then map their own environment: user count, applications, locations, budget, growth. The right design serves their context, which may differ completely from the competitor's.",
        },
        {
          id: "se-dis-13", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "When a customer describes a problem, why should you confirm your understanding back to them before moving to solutions?",
          accepted: ["restating verifies you understood correctly, surfaces missing details, and builds trust", "playback catches misunderstandings early and shows you listened"],
          required: ["understand"], optional: ["restate", "playback", "confirm", "trust", "misunderstanding"],
          explanation: "Playback ('so what I'm hearing is…') catches misinterpretations while they're cheap, invites corrections and additions, and demonstrates genuine listening.",
          improved: "Restating — 'So if I've understood: the morning slowdowns hit the sales floor's wireless devices only, starting about a month ago' — catches misunderstandings before they shape a wrong solution, often prompts crucial corrections, and shows the customer they've truly been heard.",
        },
        {
          id: "se-dis-14", topic: "Discovery", type: "customer_discovery", difficulty: "scenario",
          question: "A customer answers every question with 'I don't know'. How does a good SE make discovery productive anyway?",
          accepted: ["ask who would know, request data like reports or configs, and offer to observe or measure directly", "simplify the questions, involve the right people, and gather evidence from the environment"],
          required: ["who"], optional: ["data", "measure", "observe", "simplify", "right people"],
          explanation: "Route around the gap: identify who WOULD know, ask for artifacts (bills, topology, error screenshots), simplify to what they experience daily, or propose an assessment to gather facts directly.",
          improved: "I'd ask 'who in your organisation would know?' and involve them, request whatever exists — ISP bills, error screenshots, previous reports — and simplify to lived experience: 'what do people complain about most?'. If needed, propose a short assessment to measure the environment directly.",
        },
      ],
    },
    {
      id: "se-diagnosis",
      title: "Technical Diagnosis from Customer Symptoms",
      description: "Mapping what customers describe to the most likely technical area.",
      topics: ["Diagnosis"],
      questions: [
        {
          id: "se-dia-1", topic: "Diagnosis", type: "troubleshooting", difficulty: "scenario",
          question: "Employees can access resources using an IP address, but not by using a domain name. What is the most likely area to investigate?",
          accepted: ["dns", "name resolution, the dns service"],
          required: ["dns"],
          explanation: "IP-works/name-fails is the cleanest DNS signature in networking — connectivity is proven, only resolution is broken.",
          improved: "DNS — reaching resources by IP proves connectivity is fine, so the failure is name resolution: the DNS server, its records, or the clients' DNS settings.",
        },
        {
          id: "se-dia-2", topic: "Diagnosis", type: "troubleshooting", difficulty: "scenario",
          question: "'Our video calls are choppy, but downloads are fast.' What network qualities — rather than bandwidth — should you investigate?",
          accepted: ["latency, jitter and packet loss, since real time traffic needs consistency not throughput", "call quality depends on jitter and loss, bandwidth is clearly sufficient"],
          required: ["jitter"], optional: ["latency", "packet loss", "real time", "consistency"],
          explanation: "Fast downloads prove bandwidth. Real-time media needs low latency, low jitter, low loss — measure those, and check QoS prioritisation for voice/video.",
          improved: "Latency, jitter, and packet loss — fast downloads prove bandwidth is sufficient, but real-time calls need consistent packet delivery. I'd measure those metrics and check whether QoS is prioritising voice/video traffic.",
        },
        {
          id: "se-dia-3", topic: "Diagnosis", type: "troubleshooting", difficulty: "scenario",
          question: "'Every day around 2pm the branch office loses connection for a few minutes.' What does the regular timing suggest, and what would you correlate it with?",
          accepted: ["a scheduled event, correlate with backups, updates, isp maintenance or recurring load", "something on a schedule like a cron job, backup or provider event at that time"],
          required: ["schedul"], optional: ["backup", "correlate", "recurring", "same time"],
          explanation: "Clockwork failures have clockwork causes: scheduled backups saturating the WAN, auto-updates, ISP maintenance, even environmental cycles. Correlate timing with logs.",
          improved: "Precisely-timed failures point to something scheduled: a backup job saturating the WAN link, automatic updates, an ISP maintenance window, or a recurring process. I'd pull logs and correlate 2pm against every scheduled task and traffic graphs.",
        },
        {
          id: "se-dia-4", topic: "Diagnosis", type: "troubleshooting", difficulty: "scenario",
          question: "'New employees can never get online on their first day, but existing staff are fine.' Which service does this implicate?",
          accepted: ["dhcp, new devices aren't getting leases, possibly an exhausted pool or onboarding process gap", "address assignment for new devices, dhcp scope or registration"],
          required: ["dhcp"], optional: ["exhausted", "pool", "lease", "onboarding", "nac"],
          explanation: "Existing devices hold leases/registrations; new ones need fresh DHCP (or NAC onboarding). Exhausted scope or a broken onboarding step fits the 'only new' pattern.",
          improved: "DHCP (or the onboarding process around it): existing staff already hold leases and registrations, while new devices need fresh ones. An exhausted DHCP pool or a device-registration step failing would produce exactly this new-users-only pattern.",
        },
        {
          id: "se-dia-5", topic: "Diagnosis", type: "troubleshooting", difficulty: "scenario",
          question: "'Wi-Fi is great near reception but terrible in the far meeting rooms.' What is the probable cause category, and what evidence would confirm it?",
          accepted: ["coverage, weak signal far from the aps, confirmed by a site survey showing low signal in those rooms", "ap placement and signal reach, verify with signal measurements in the affected rooms"],
          required: ["coverage"], optional: ["signal strength", "site survey", "ap placement", "distance"],
          explanation: "Location-correlated quality = coverage. A quick survey (signal readings per room) confirms weak RSSI in far rooms; fix with AP placement or additional APs.",
          improved: "A coverage problem: signal weakening with distance and walls from the AP near reception. A site survey measuring signal strength room by room would confirm it — and show exactly where an additional AP or repositioning is needed.",
        },
        {
          id: "se-dia-6", topic: "Diagnosis", type: "troubleshooting", difficulty: "scenario",
          question: "A customer added 40 IP cameras and now 'the whole network crawls'. What two resource exhaustions should you check first?",
          accepted: ["bandwidth saturation from camera streams and switch capacity or poe budget", "uplink and network bandwidth consumed by video, plus the switches' limits"],
          required: ["bandwidth"], optional: ["saturat", "uplink", "poe budget", "switch capacity", "vlan"],
          explanation: "40 continuous video streams can flood uplinks and recorder links, and strain PoE budgets. Check utilisation graphs; the fix is often a camera VLAN + capacity.",
          improved: "Bandwidth first — 40 constant video streams can saturate access-switch uplinks and the path to the recorder; then the switches themselves — PoE budget and backplane. Utilisation graphs will show it. Cameras usually belong on their own VLAN with sized uplinks.",
        },
        {
          id: "se-dia-7", topic: "Diagnosis", type: "troubleshooting", difficulty: "scenario",
          question: "'Sometimes the internet dies for everyone for exactly a minute or two, then recovers by itself.' What kinds of causes produce brief, self-healing, site-wide outages?",
          accepted: ["a flapping wan link or failover event, spanning tree reconvergence, or an overloaded device recovering", "isp link drops and recovery, router failover, loops being blocked, dhcp or arp storms subsiding"],
          required: ["flap"], optional: ["failover", "reconverge", "isp", "spanning tree", "loop"],
          explanation: "Short site-wide self-healing outages smell of state transitions: WAN flaps, primary/backup failover cycles, STP reconvergence after a loop event, or momentary overload.",
          improved: "Self-recovering site-wide blips point to state transitions: a flapping ISP link (drop and re-establish), a failover cycling between WAN links, or spanning-tree reconvergence when a loop appears. Router and switch logs with timestamps will identify which.",
        },
        {
          id: "se-dia-8", topic: "Diagnosis", type: "troubleshooting", difficulty: "scenario",
          question: "'Only our oldest building has problems; the new wing is flawless.' The same equipment serves both. Where does suspicion shift?",
          accepted: ["the physical layer in the old building, aging cabling, interference or environmental factors", "old infrastructure, degraded cables, patch panels, or building construction affecting wifi"],
          required: ["cabling"], optional: ["physical", "old building", "interference", "environment", "construction"],
          explanation: "Same gear, different buildings → the difference IS the building: aged/degraded cabling, old patch panels, thick walls, electrical interference.",
          improved: "To the physical layer of the old building: aging or substandard cabling and patch panels, thick construction attenuating Wi-Fi, or electrical interference. With identical equipment in both, the building's infrastructure is the variable.",
        },
        {
          id: "se-dia-9", topic: "Diagnosis", type: "troubleshooting", difficulty: "scenario",
          question: "A customer complains cloud apps are slow at the office but fine from home. What does this comparison tell you, and where would you look?",
          accepted: ["the cloud apps are fine, the office path is the problem, check the office internet link, firewall and proxy", "office side bottleneck, isp bandwidth saturation or security appliances adding latency"],
          required: ["office"], optional: ["internet link", "firewall", "saturat", "proxy", "not the app"],
          explanation: "Home-fast proves the apps and internet at large are fine; the office path is the suspect — saturated circuit, overloaded firewall/proxy, DNS, or Wi-Fi.",
          improved: "Working-from-home performance clears the cloud apps themselves — the office path is the bottleneck. I'd check the office internet circuit's utilisation, the firewall/proxy the traffic traverses (inspection overload adds latency), and office DNS.",
        },
        {
          id: "se-dia-10", topic: "Diagnosis", type: "troubleshooting", difficulty: "scenario",
          question: "'After we moved desks around, two people's computers stopped working entirely on the network.' Everyone else is fine. Most likely explanations?",
          accepted: ["their new wall ports aren't patched or are on the wrong vlan, or cables were damaged in the move", "unpatched or misconfigured outlets at the new desks, or broken patch leads"],
          required: ["port"], optional: ["patched", "vlan", "outlet", "cable", "moved"],
          explanation: "Desk moves expose dormant infrastructure: new outlets never patched to the switch, ports in wrong VLANs, or cables damaged in transit.",
          improved: "The new desks' wall outlets: they may never have been patched through to the switch, or their switch ports sit in a different/disabled VLAN — plus the possibility of patch leads damaged during the move. The desk move changed only their physical connection points.",
        },
        {
          id: "se-dia-11", topic: "Diagnosis", type: "troubleshooting", difficulty: "scenario",
          question: "'Our website visitors say the site is sometimes unreachable, but it's always fine when WE check.' What diagnostic blind spot might the customer have?",
          accepted: ["they test from inside their network, external paths like dns, cdn or isp routing may fail for outsiders", "internal checks bypass what visitors traverse, monitor from outside"],
          required: ["inside"], optional: ["external", "dns", "outside monitoring", "visitors' path", "routing"],
          explanation: "Testing from inside bypasses external DNS, routing, and CDN paths visitors use. External synthetic monitoring from multiple regions reveals what visitors actually experience.",
          improved: "They're testing from inside their own network — a path visitors never use. External factors (public DNS issues, ISP routing, CDN regions, certificate errors) can fail for outsiders while internal checks pass. External monitoring from several regions would show the truth.",
        },
        {
          id: "se-dia-12", topic: "Diagnosis", type: "troubleshooting", difficulty: "scenario",
          question: "A customer swears 'the new firewall broke everything' — but only one legacy application actually fails. How do you investigate without dismissing them?",
          accepted: ["validate the correlation, check the firewall logs for that app's traffic being blocked and identify its ports and protocols", "take it seriously, find what the legacy app needs and whether the new rules or inspection block it"],
          required: ["logs"], optional: ["blocked", "ports", "legacy", "correlate", "validate"],
          explanation: "They're probably partially right — timing correlates. Legacy apps use odd ports/protocols that new default policies block. Firewall logs for that app's flows settle it respectfully.",
          improved: "Acknowledge the timing is meaningful and test the claim precisely: identify the ports and protocols the legacy app uses, then check the new firewall's logs for those flows being denied. Old apps often use non-standard traffic that a modern firewall's defaults block — they're likely partly right.",
        },
      ],
    },
    {
      id: "se-solutioning",
      title: "Recommendations & Requirements Mapping",
      description: "Proposing directions responsibly and mapping requirements to capabilities.",
      topics: ["Solution Recommendation", "Requirements Mapping"],
      questions: [
        {
          id: "se-sol-1", topic: "Solution Recommendation", type: "solution_recommendation", difficulty: "scenario",
          question: "A company has five branch offices and wants secure, centrally managed connectivity between them. What type of solution would you investigate, and what more would you need to know?",
          accepted: ["a site to site vpn or sd-wan solution, after learning bandwidth needs, applications, budget and existing equipment", "sd-wan or vpn mesh, but first discover traffic patterns, sites, cloud usage and management preferences"],
          required: ["vpn", "need to know"], optional: ["sd-wan", "bandwidth", "applications", "budget", "existing", "discovery"],
          explanation: "Direction: site-to-site VPN or SD-WAN with central management. But sizing needs discovery — inter-site traffic, apps (voice? cloud?), circuits, existing gear, IT capacity.",
          improved: "I'd investigate site-to-site VPN or SD-WAN with centralized management. Before recommending specifics I'd need: traffic and application profile between sites (voice? file sync? cloud-bound?), each site's circuits and bandwidth, existing equipment, budget, and how much management the IT team can take on.",
        },
        {
          id: "se-sol-2", topic: "Requirements Mapping", type: "solution_recommendation", difficulty: "scenario",
          question: "The customer requires secure remote access, multi-factor authentication, and visibility into application performance. Identify the main technical capability needed for each requirement.",
          accepted: ["a vpn or ztna for remote access, an mfa identity solution, and application performance monitoring", "remote access gateway, identity platform with mfa, and network or app monitoring"],
          required: ["vpn", "mfa", "monitoring"], optional: ["ztna", "identity", "application performance"],
          explanation: "Map requirement→capability: remote access → VPN/ZTNA gateway; MFA → identity platform with second factors; performance visibility → application/network monitoring.",
          improved: "Secure remote access → a VPN or zero-trust access gateway. Multi-factor authentication → an identity platform enforcing a second factor at login. Application performance visibility → a monitoring solution tracking latency, loss, and per-application experience.",
        },
        {
          id: "se-sol-3", topic: "Solution Recommendation", type: "solution_recommendation", difficulty: "scenario",
          question: "A 20-person accounting firm asks for 'enterprise-grade everything'. How should an SE respond to over-scoped requests?",
          accepted: ["understand the concern behind the request and right-size, matching real risks and needs rather than upselling", "explore why they want enterprise grade, then recommend appropriate scale, wasting budget hurts trust"],
          required: ["right"], optional: ["why", "concern behind", "appropriate", "oversized", "trust"],
          explanation: "Over-scoping wastes budget and complexity; find the fear behind the phrase (a breach story? an audit?), then right-size — earning long-term trust over short-term revenue.",
          improved: "First understand what's driving it — often a security scare or client requirement. Then right-size honestly: a 20-person firm needs solid fundamentals (business firewall, MFA, backups, managed Wi-Fi), not enterprise data-centre gear. Selling what fits builds the relationship that outlasts any single deal.",
        },
        {
          id: "se-sol-4", topic: "Solution Recommendation", type: "solution_recommendation", difficulty: "scenario",
          question: "A customer's requirements genuinely conflict: they want everything cloud-managed, but their site has unreliable internet. How do you proceed?",
          accepted: ["surface the conflict honestly and explore options, better connectivity, hybrid management, or solutions with offline resilience", "name the trade-off, ask which matters more, and propose paths like redundant links or local fallback"],
          required: ["conflict"], optional: ["trade-off", "redundant", "offline", "hybrid", "which matters more"],
          explanation: "Don't paper over conflicts — name them. Then explore: fix connectivity (redundant links), choose gear that tolerates cloud-management outages, or hybrid management.",
          improved: "I'd name the tension openly: cloud management assumes dependable connectivity. Then explore resolutions together — adding a redundant internet link (often needed anyway), choosing equipment that keeps functioning when the management cloud is unreachable, or a hybrid approach. The customer decides with full information.",
        },
        {
          id: "se-sol-5", topic: "Requirements Mapping", type: "solution_recommendation", difficulty: "scenario",
          question: "'We need guest Wi-Fi, but legal says guests must never touch our internal network, and marketing wants a branded login page.' Map each requirement to a capability.",
          accepted: ["guest ssid, network isolation or a separate vlan, and a captive portal for branding", "a guest network with vlan isolation and firewall rules plus a customizable captive portal"],
          required: ["vlan", "portal"], optional: ["isolation", "guest ssid", "captive", "firewall rules"],
          explanation: "Guest access → dedicated SSID; legal isolation → guest VLAN + firewall deny-to-internal; branding → captive portal with custom page.",
          improved: "Guest Wi-Fi → a dedicated guest SSID. Legal isolation → that SSID mapped to its own VLAN with firewall rules blocking all internal access (internet-only). Branded login → a captive portal presenting marketing's customized page before granting access.",
        },
        {
          id: "se-sol-6", topic: "Solution Recommendation", type: "solution_recommendation", difficulty: "scenario",
          question: "Why is 'recommending a direction plus naming the open questions' stronger than delivering a complete solution at the first meeting?",
          accepted: ["it shows expertise while respecting unknowns, premature precision risks being wrong and erodes trust", "direction plus questions is honest, engages the customer, and avoids committing to wrong specifics"],
          required: ["premature"], optional: ["unknowns", "honest", "direction", "trust", "wrong"],
          explanation: "First-meeting 'complete' solutions are guesses wearing suits. Direction + open questions demonstrates competence AND honesty, and invites the collaboration that produces the right design.",
          improved: "Because a complete first-meeting solution is built on assumptions — when one proves wrong, credibility goes with it. A clear direction plus explicitly-named open questions shows expertise and honesty simultaneously, and turns the customer into a collaborator in getting the details right.",
        },
        {
          id: "se-sol-7", topic: "Requirements Mapping", type: "solution_recommendation", difficulty: "scenario",
          question: "A clinic must comply with patient-data privacy rules, let doctors roam with tablets, and keep guest patients off clinical systems. Sketch the capability map.",
          accepted: ["encryption and access controls for compliance, seamless wifi roaming for tablets, and segmented guest and clinical networks", "segmentation separating clinical from guest, strong auth and encryption for phi, and campus wifi with roaming"],
          required: ["segment", "roam"], optional: ["encryption", "access control", "compliance", "guest network", "wifi"],
          explanation: "Privacy → encryption + access control + audit on the clinical segment; roaming tablets → well-designed Wi-Fi with seamless AP handoff; guest separation → isolated guest VLAN/SSID.",
          improved: "Patient-data privacy → encrypted traffic, strong authentication, and access controls on an isolated clinical network segment. Roaming tablets → campus-grade Wi-Fi with seamless handoff between APs. Guest access → a separate guest SSID/VLAN that reaches the internet only, never clinical systems.",
        },
        {
          id: "se-sol-8", topic: "Solution Recommendation", type: "solution_recommendation", difficulty: "scenario",
          question: "The customer's budget covers only half of what their requirements truly need. What are the responsible ways forward?",
          accepted: ["prioritize by risk and value with a phased roadmap, or revisit scope honestly, never silently under deliver", "phase the work starting with highest impact, adjust requirements openly, or find the budget case, don't cut corners quietly"],
          required: ["phase"], optional: ["prioritize", "roadmap", "honest", "scope", "risk"],
          explanation: "Options: phase by risk/value (foundation now, rest on a roadmap), openly renegotiate scope, or build the business case for more budget. Never quietly deliver a solution that won't work.",
          improved: "Be transparent: either phase the solution — highest-risk/highest-value items now, a costed roadmap for the rest — or openly adjust requirements to match the budget. What's never acceptable is silently delivering something that won't meet the stated needs and letting them discover it in production.",
        },
        {
          id: "se-sol-9", topic: "Requirements Mapping", type: "solution_recommendation", difficulty: "scenario",
          question: "'We need the network to never go down.' How do you translate this into engineering requirements and honest expectations?",
          accepted: ["quantify acceptable downtime and cost, then design redundancy accordingly, explaining that each nine costs more", "turn it into an availability target with redundant components, being honest that 100 percent doesn't exist"],
          required: ["redundan"], optional: ["availability", "quantify", "cost", "nines", "honest"],
          explanation: "'Never' isn't purchasable. Quantify: what does an hour of downtime cost? Which systems matter most? Then design tiered redundancy and state the honest availability expectation.",
          improved: "Translate 'never' into numbers: what does an hour of downtime cost, and which systems are critical? Then design redundancy proportionate to that — dual WAN links, redundant core, UPS. And be honest: 100% doesn't exist; each additional 'nine' of availability multiplies cost, so we target what the business case justifies.",
        },
        {
          id: "se-sol-10", topic: "Solution Recommendation", type: "solution_recommendation", difficulty: "scenario",
          question: "When is the right answer to a customer request 'you don't need to buy anything'?",
          accepted: ["when configuration changes or existing equipment solve the problem, honesty here builds long term trust", "if the fix is config, a firmware update or better use of what they own, say so"],
          required: ["existing"], optional: ["configuration", "no purchase", "trust", "already own"],
          explanation: "Often the fix is config, placement, firmware, or using owned-but-unused features. Saying so costs a sale and buys a customer for life.",
          improved: "Whenever it's true — a misconfiguration fixed, an AP repositioned, a firmware update, or a feature they already own but never enabled. Telling a customer 'don't buy anything, do this instead' loses one transaction and wins the trust that brings every future one.",
        },
        {
          id: "se-sol-11", topic: "Requirements Mapping", type: "solution_recommendation", difficulty: "scenario",
          question: "A logistics customer needs: warehouse handheld scanners that never drop connection, office VoIP quality, and cameras at the loading dock. Which distinct network capabilities does each demand?",
          accepted: ["industrial grade wifi with seamless roaming for scanners, qos for voice, and poe with adequate bandwidth for cameras", "warehouse wireless coverage and roaming, voice prioritization, and powered camera ports with a video vlan"],
          required: ["roaming", "qos", "poe"], optional: ["coverage", "voice priority", "vlan", "bandwidth"],
          explanation: "Scanners → dense Wi-Fi with fast roaming across the warehouse; VoIP → QoS prioritising voice end-to-end; cameras → PoE ports, adequate uplinks, a video VLAN.",
          improved: "Scanners → warehouse-grade Wi-Fi: dense coverage plus fast roaming so sessions survive movement between APs. VoIP → QoS prioritising voice traffic across the network. Cameras → PoE switch ports for power, a dedicated video VLAN, and uplinks sized for the streams.",
        },
        {
          id: "se-sol-12", topic: "Solution Recommendation", type: "solution_recommendation", difficulty: "scenario",
          question: "Your proposed solution requires skills the customer's one-person IT team doesn't have. What must the recommendation include beyond the technology?",
          accepted: ["an operability plan, training, managed services or simpler alternatives so they can actually run it", "who operates it day two, training, support contracts, or a managed offering"],
          required: ["train"], optional: ["managed service", "operate", "support", "simpler", "day two"],
          explanation: "Day-2 operations decide success: include training, support contracts, managed-service options, or choose a simpler-to-operate design. Un-runnable brilliance fails.",
          improved: "A day-two operations plan: training for their IT person, a support contract for what's beyond them, a managed-service option, or — often best — a simpler design they can genuinely run. A solution the customer can't operate is a failure delivered in advance.",
        },
        {
          id: "se-sol-13", topic: "Requirements Mapping", type: "solution_recommendation", difficulty: "scenario",
          question: "'Our auditors require that we can show who accessed what, and when.' What capability class answers this, and what design details follow?",
          accepted: ["logging and audit trails, centralized authentication with per user accounts, log retention and time sync", "aaa with individual identities, centralized log collection, retention policies and accurate timestamps"],
          required: ["logg"], optional: ["audit", "per user", "centralized", "retention", "time sync", "identity"],
          explanation: "Audit trails need: individual (not shared) accounts, centralized authentication, log aggregation with retention, and NTP-synced timestamps so 'when' is trustworthy.",
          improved: "Centralized logging and audit trails: individual user accounts (no shared logins) authenticated centrally, all access events collected to a central log store with a defined retention period, and time-synchronized devices so the 'when' in every record is reliable.",
        },
        {
          id: "se-sol-14", topic: "Solution Recommendation", type: "solution_recommendation", difficulty: "scenario",
          question: "Why should an SE present options (e.g., good/better/best) rather than a single take-it-or-leave-it design?",
          accepted: ["options respect the customer's ownership of trade-offs and reveal their true priorities", "choices let the customer weigh cost against capability and increases buy-in"],
          required: ["trade"], optional: ["priorities", "cost", "buy-in", "choice", "ownership"],
          explanation: "Options make trade-offs explicit and put the value decision where it belongs — with the customer. Their choice also reveals priorities that sharpen everything after.",
          improved: "Because the cost/capability trade-off belongs to the customer, not the engineer. Good/better/best makes the trade-offs explicit, lets them choose with eyes open, increases their ownership of the outcome — and their choice teaches you what they truly value.",
        },
      ],
    },
    {
      id: "se-communication",
      title: "Explaining Technology & Business Value",
      description: "Making concepts clear to non-technical audiences and connecting features to outcomes.",
      topics: ["Explain Simply", "Business Value"],
      questions: [
        {
          id: "se-com-1", topic: "Explain Simply", type: "explain_simply", difficulty: "scenario",
          question: "Explain what a VPN does to a non-technical business owner in two sentences.",
          accepted: ["it creates a private protected tunnel over the internet so remote staff reach office systems as if they were there, and nobody in between can read the traffic", "like a sealed courier route through public roads, your data travels the internet but stays private"],
          required: ["private"], optional: ["tunnel", "encrypted", "remote", "as if in the office", "protected"],
          explanation: "Aim for one analogy plus one benefit: a protected private tunnel through the public internet; staff work remotely as if at their desks, with eavesdroppers shut out.",
          improved: "A VPN creates a private, protected tunnel across the public internet between your employees and your office. Staff working anywhere can use company systems as if they were at their desks — and nobody along the way can read what passes through.",
        },
        {
          id: "se-com-2", topic: "Business Value", type: "business_value", difficulty: "scenario",
          question: "A network monitoring platform can identify packet loss and application latency. How would you explain its business value to a customer?",
          accepted: ["it reduces downtime and speeds troubleshooting, protecting productivity and customer experience and lowering operational cost", "problems get found before users complain, outages shrink, staff stay productive, and it costs less to run the network"],
          required: ["downtime"], optional: ["productivity", "faster troubleshooting", "customer experience", "cost", "visibility", "before users notice"],
          explanation: "Translate metrics to outcomes: loss/latency detection → problems found before users feel them → less downtime, faster fixes, productive staff, happier customers, lower operational cost.",
          improved: "Instead of hearing about problems from frustrated staff, you see them forming and fix them early. That means less downtime, faster troubleshooting when issues do occur, employees who stay productive, a better experience for your customers — and lower cost of running the network overall.",
        },
        {
          id: "se-com-3", topic: "Explain Simply", type: "explain_simply", difficulty: "scenario",
          question: "A retail director asks what network segmentation is and why she should pay for it. Answer in her language.",
          accepted: ["it's like having separate locked rooms instead of one open hall, a break in at the guest area can't reach your tills or stock systems", "walls inside your network so a problem in one area stays there, protecting payments and operations"],
          required: ["separate"], optional: ["rooms", "contain", "tills", "payment", "walls", "break in"],
          explanation: "Analogy: locked rooms vs one open hall. Value: a compromise in one area (guest Wi-Fi, a hacked camera) can't reach payments — protecting revenue and compliance.",
          improved: "Right now your network is like one open hall — anyone who gets in can walk anywhere. Segmentation builds locked rooms: guest Wi-Fi, cameras, tills, and office systems each in their own space. If something bad gets into one room, your payment systems stay locked away from it.",
        },
        {
          id: "se-com-4", topic: "Business Value", type: "business_value", difficulty: "scenario",
          question: "How do you express the business value of redundant internet links to a company that sells exclusively online?",
          accepted: ["their revenue stops when the internet stops, a second link is insurance costing a fraction of one outage", "quantify downtime cost per hour against the modest cost of a backup circuit"],
          required: ["revenue"], optional: ["downtime cost", "insurance", "per hour", "second link", "fraction"],
          explanation: "For online-only businesses, the internet IS the shop. Frame as insurance: hourly-revenue-at-risk vs modest monthly circuit cost — the arithmetic sells itself.",
          improved: "For you, an internet outage isn't an IT problem — the shop door is locked. If you take £10k/hour online, a four-hour outage is £40k gone. A second, independent link that takes over automatically costs a small fraction of one such incident. It's insurance for your revenue stream.",
        },
        {
          id: "se-com-5", topic: "Explain Simply", type: "explain_simply", difficulty: "scenario",
          question: "Explain DNS to a marketing manager using an everyday analogy.",
          accepted: ["it's the internet's phone book, turning names people remember into numeric addresses computers use", "like contacts in your phone, you tap a name and it dials the number for you"],
          required: ["name"], optional: ["phone book", "contacts", "address", "number"],
          explanation: "Phone book/contacts analogy: humans use names, machines use numbers; DNS does the lookup invisibly every time.",
          improved: "DNS is the internet's contact list. You remember names — yourcompany.com — while computers need numeric addresses. Every time someone types your website's name, DNS instantly looks up the number and connects them, like your phone dialling a saved contact.",
        },
        {
          id: "se-com-6", topic: "Business Value", type: "business_value", difficulty: "scenario",
          question: "A CFO sees Wi-Fi upgrades as 'nice to have'. The warehouse team loses ~20 minutes per shift to scanner dropouts. Build the value case.",
          accepted: ["quantify the lost time across workers and shifts into money, the upgrade pays for itself in months", "20 minutes per worker per shift is real payroll waste, multiply it out and compare with the upgrade cost"],
          required: ["quantif"], optional: ["payroll", "multiply", "pays for itself", "productivity", "per shift"],
          explanation: "Turn dropouts into money: minutes × workers × shifts × wage = annual waste. Compare to upgrade cost; the payback period usually closes the conversation.",
          improved: "Do the arithmetic with them: 20 minutes × 30 warehouse staff × 2 shifts × 250 days ≈ 2,500 lost hours a year — call it £35k of paid unproductive time, plus slower shipping. Against a £15k Wi-Fi upgrade, that's a five-month payback. It's not 'nice to have'; it's one of the best ROIs available.",
        },
        {
          id: "se-com-7", topic: "Explain Simply", type: "explain_simply", difficulty: "scenario",
          question: "The customer's CEO asks, 'What actually happens when I click a website link?' Give a 30-second, jargon-free answer.",
          accepted: ["your computer looks up the site's address, sends a request across the internet through many relay points, and the site sends the page back in small pieces reassembled on your screen", "a name lookup, then a request travels hop by hop to the server, which returns the page in pieces"],
          required: ["request"], optional: ["look up", "address", "pieces", "server", "relay"],
          explanation: "Compress to: lookup (find the address) → journey (request relayed across networks) → response (page returns in pieces, reassembled). No ports, no protocols.",
          improved: "Your computer first looks up the website's address — like checking a contact. It then sends a request that hops across the internet through a chain of relay points to the site's computers, which send the page back to you in small pieces that your browser reassembles — all in a fraction of a second.",
        },
        {
          id: "se-com-8", topic: "Business Value", type: "business_value", difficulty: "scenario",
          question: "Translate 'centralized cloud management of network equipment' into three concrete business benefits for a 12-site retailer.",
          accepted: ["fewer site visits, faster consistent rollouts across all stores, and visibility of every site from one screen", "lower operational cost, changes deployed everywhere at once, and problems spotted remotely before store staff notice"],
          required: ["one"], optional: ["site visits", "rollout", "consistent", "visibility", "remote", "cost"],
          explanation: "Cloud management → truck-roll reduction (cost), one-click consistent changes across 12 stores (speed/consistency), single-pane visibility (proactive fixes).",
          improved: "First, fewer expensive site visits — most fixes and changes happen remotely. Second, speed and consistency: a new policy or Wi-Fi setup deploys to all 12 stores in one action, identically. Third, visibility: your team sees every store's health on one screen and fixes issues before staff even call.",
        },
        {
          id: "se-com-9", topic: "Explain Simply", type: "explain_simply", difficulty: "scenario",
          question: "What communication mistake do technical presenters most often make with executive audiences, and what's the fix?",
          accepted: ["leading with technical detail instead of business outcomes, fix by starting with what it means for the business", "too much jargon and features, executives want risk, cost and outcome first, details on request"],
          required: ["outcome"], optional: ["jargon", "lead with", "business", "detail on request", "risk"],
          explanation: "Engineers lead with how; executives need what/why: outcome, risk, cost first — mechanism only if asked. Invert the pyramid.",
          improved: "Leading with the technology instead of the outcome — features, specs, and acronyms first. The fix: invert it. Open with what it means for the business ('this halves your outage risk'), keep mechanism to one plain sentence, and hold the technical depth for whoever asks.",
        },
        {
          id: "se-com-10", topic: "Business Value", type: "business_value", difficulty: "scenario",
          question: "A customer asks why they should pay annually for security subscriptions on a firewall they already bought. Explain the value honestly.",
          accepted: ["the subscriptions keep threat intelligence current, a firewall with stale protections misses new attacks", "the hardware inspects, the subscription supplies the up to date knowledge of what to block"],
          required: ["threat"], optional: ["updates", "current", "new attacks", "intelligence", "stale"],
          explanation: "Hardware is the engine; subscriptions are the fresh threat intelligence it burns. New malware and phishing sites appear daily — year-old protections quietly miss them.",
          improved: "The firewall box is the engine; the subscription is its up-to-date knowledge of what to block. New malware, phishing sites, and attack techniques appear daily, and the subscription feeds those to your firewall continuously. Without it the hardware still runs — but against last year's threats.",
        },
        {
          id: "se-com-11", topic: "Explain Simply", type: "explain_simply", difficulty: "scenario",
          question: "Explain 'the cloud' to a sceptical family-business owner who asks where their data actually is.",
          accepted: ["your data lives in professionally run data centres you rent space in, reachable from anywhere, like a bank vault versus cash under the mattress", "it's real computers in secure facilities operated by specialists, you rent capacity instead of owning servers"],
          required: ["data centre"], optional: ["rent", "professional", "secure facilities", "bank", "real computers"],
          explanation: "Demystify: real computers in real (professionally guarded, redundant) buildings; you rent instead of own. The bank-vault analogy addresses the trust question directly.",
          improved: "The cloud is real computers in heavily secured, professionally staffed data centres — your data sits there instead of on a server in your back office. Think bank vault versus cash under the mattress: specialists guard it, back it up, and keep it available, and you rent exactly the space you need.",
        },
        {
          id: "se-com-12", topic: "Business Value", type: "business_value", difficulty: "scenario",
          question: "The operations director asks what QoS does, in business terms, and whether it means buying more bandwidth.",
          accepted: ["qos prioritizes critical traffic like calls over bulk traffic, often improving quality without buying bandwidth", "it's traffic triage, the important traffic goes first, so calls stay clear even when the line is busy"],
          required: ["priorit"], optional: ["calls", "without more bandwidth", "triage", "critical first"],
          explanation: "QoS = triage lane: voice/critical apps jump the queue; downloads wait milliseconds longer. Frequently fixes call quality with zero new bandwidth.",
          improved: "QoS is a priority lane on the bandwidth you already own: phone calls and critical apps go first, bulk downloads wait a few milliseconds. It usually means clear calls without buying more bandwidth — you'd only buy more if the line is genuinely full of important traffic.",
        },
        {
          id: "se-com-13", topic: "Business Value", type: "business_value", difficulty: "scenario",
          question: "How do you present the value of proactive network maintenance to a customer who only pays for fixes when things break?",
          accepted: ["compare the cost of planned maintenance with unplanned outages, prevention is cheaper than emergency downtime", "break fix looks cheap until an outage, proactive care trades small predictable costs for avoiding big surprise ones"],
          required: ["outage"], optional: ["prevention", "planned", "predictable", "emergency", "cheaper"],
          explanation: "Frame as planned-vs-unplanned cost: maintenance is scheduled and cheap; failures are surprise downtime at the worst moment, at emergency rates. Like servicing vs breakdowns.",
          improved: "Break-fix means every failure is a surprise outage at the worst possible time, paid at emergency rates and costed in downtime too. Proactive maintenance trades that for small, scheduled, predictable costs — like servicing a delivery van instead of waiting for it to die on the motorway with a full load.",
        },
        {
          id: "se-com-14", topic: "Explain Simply", type: "explain_simply", difficulty: "scenario",
          question: "When a customer asks a question mid-explanation that shows they misunderstood something basic, how should an SE handle it?",
          accepted: ["treat it respectfully, back up and rebuild the explanation from their actual understanding without condescension", "never embarrass them, revisit the foundation with a better analogy and check understanding as you go"],
          required: ["respect"], optional: ["back up", "analogy", "no condescension", "check understanding", "foundation"],
          explanation: "The misunderstanding is the explainer's feedback, not the listener's failure. Back up graciously ('let me explain that better'), rebuild with a different analogy, verify along the way.",
          improved: "Treat it as feedback on my explanation, not their intelligence: 'Good question — let me explain that part better.' Then rebuild from where their understanding actually is, using a different analogy, and check in as I go. Customers who feel embarrassed stop asking questions — and stop listening.",
        },
      ],
    },
    {
      id: "se-objections",
      title: "Objections, Trade-offs & Unknowns",
      description: "Handling pushback honestly, balancing competing demands, and admitting what you don't know.",
      topics: ["Objection Handling", "Trade-offs", "Handling Unknowns"],
      questions: [
        {
          id: "se-obj-1", topic: "Objection Handling", type: "objection_handling", difficulty: "scenario",
          question: "The customer says, 'Your solution is more expensive than the competitor's.' How should a Solution Engineer respond?",
          accepted: ["understand what's being compared, clarify requirements, and discuss total cost of ownership and business outcomes rather than arguing price", "ask what the competitor quoted covers, compare like for like, and connect the difference to value and risk"],
          required: ["compar"], optional: ["total cost of ownership", "requirements", "outcomes", "like for like", "understand"],
          mistakes: ["Attacking the competitor or discounting reflexively before understanding the comparison."],
          explanation: "First understand the comparison (same scope? support? lifespan?), then move from price to TCO and outcomes. No competitor-bashing, no unsupported claims, no panic discounts.",
          improved: "First I'd ask to understand the comparison: does the competitor's quote cover the same scope, support, and lifespan? Often it doesn't — then it's a like-for-like conversation. If it truly does, I'd focus on total cost of ownership and the specific outcomes and risks that differ, not argue the sticker price.",
        },
        {
          id: "se-obj-2", topic: "Handling Unknowns", type: "objection_handling", difficulty: "scenario",
          question: "A customer asks a detailed technical question and you are not certain of the answer. What should you do?",
          accepted: ["be honest that i need to confirm, clarify the question, record it, consult the specialist or documentation, and follow up by an agreed time", "say i don't want to guess, capture it precisely, and come back with a verified answer"],
          required: ["honest"], optional: ["follow up", "consult", "record", "clarify", "specialist", "not guess"],
          mistakes: ["Inventing a plausible-sounding answer — one wrong technical claim can undo months of credibility."],
          explanation: "Never fabricate. Clarify exactly what's asked, note it, name your source path (specialist/docs), and commit to a follow-up time. Honesty is a feature customers buy.",
          improved: "I'd say plainly: 'I want to give you an accurate answer rather than a guess — let me confirm.' Then clarify exactly what they need, write it down, consult the right specialist or documentation, and follow up by an agreed time. A verified answer tomorrow beats a wrong one today.",
        },
        {
          id: "se-obj-3", topic: "Trade-offs", type: "objection_handling", difficulty: "scenario",
          question: "A customer wants maximum security but also wants users to sign in with no additional steps. How would you handle these competing requirements?",
          accepted: ["acknowledge the trade-off openly and explore what each requirement really means, then propose approaches like sso and passkeys that improve both", "name the tension, ask about their risk tolerance and workflows, and look for modern methods that reduce friction while keeping security"],
          required: ["trade"], optional: ["acknowledge", "sso", "passkeys", "risk", "friction", "ask"],
          explanation: "Acknowledge the tension honestly, then dig: which users, which systems, what risk? Modern auth (SSO, passkeys, risk-based prompts) often improves security AND experience.",
          improved: "I'd name the trade-off honestly and then explore it: what's driving each requirement, and where is friction actually hurting? Modern approaches — single sign-on, passkeys, risk-based authentication that only challenges unusual logins — often deliver more security with fewer steps, dissolving much of the apparent conflict.",
        },
        {
          id: "se-obj-4", topic: "Objection Handling", type: "objection_handling", difficulty: "scenario",
          question: "'We tried something like this before and it failed.' How do you respond to this objection?",
          accepted: ["take it seriously, ask what happened and why it failed, and show specifically how this attempt differs", "explore the failure's causes, validate the concern, and address each root cause explicitly"],
          required: ["what happened"], optional: ["why it failed", "differs", "validate", "root cause", "learn"],
          explanation: "That history is gold: mine it. What failed — product, implementation, adoption, support? Then map each root cause to what's different now. Dismissing it loses the room.",
          improved: "I'd treat that history as essential input: 'Tell me what happened — what went wrong and why?' Whether it was the product, the rollout, or adoption, each root cause becomes a specific point to address: here's what's different this time, and here's how we prevent a repeat.",
        },
        {
          id: "se-obj-5", topic: "Trade-offs", type: "objection_handling", difficulty: "scenario",
          question: "The customer wants the cheapest option today, but you know it won't scale past next year's planned growth. What do you owe them?",
          accepted: ["a clear statement of the limitation and the cost of upgrading later, then respect their informed choice", "honesty about when it breaks and what migration costs, letting them decide with full information"],
          required: ["honest"], optional: ["limitation", "informed", "upgrade later", "their choice", "cost of migration"],
          explanation: "You owe informed consent: name where the cheap option hits its ceiling and what the later migration costs. Then their choice is genuinely theirs.",
          improved: "Full transparency: 'This option covers today comfortably but hits its ceiling at roughly your planned headcount; replacing it then costs X plus disruption. The scalable option costs Y more now.' If they choose cheap with open eyes, that's a legitimate business decision — my job is making sure the eyes are open.",
        },
        {
          id: "se-obj-6", topic: "Objection Handling", type: "objection_handling", difficulty: "scenario",
          question: "'We don't have time for a rollout — our team is stretched thin already.' What is this objection really about, and how do you address it?",
          accepted: ["it's about implementation burden not the product, address with phasing, professional services or managed deployment", "fear of disruption and workload, respond with a low effort deployment plan and support options"],
          required: ["burden"], optional: ["phasing", "services", "managed", "disruption", "deployment plan"],
          explanation: "The objection targets implementation pain, not value. Answer with the deployment plan: phasing, off-hours work, professional services, managed options — shrink THEIR effort.",
          improved: "It's an implementation-burden objection, not a value objection — so answer with the plan, not the product: a phased rollout that touches their team lightly, professional services carrying the heavy lifting, off-hours cutover, and clear rollback points. Shrink their effort until the objection dissolves.",
        },
        {
          id: "se-obj-7", topic: "Handling Unknowns", type: "objection_handling", difficulty: "scenario",
          question: "Mid-demo, the customer asks whether your solution integrates with an obscure system you've never heard of. Ideal response?",
          accepted: ["ask what the system is and how they use it, be honest i'll verify integration options, and follow up with a checked answer", "learn what it does and what integration they need, then commit to confirming rather than guessing"],
          required: ["verify"], optional: ["ask about it", "honest", "follow up", "what integration", "not guess"],
          explanation: "Turn it into discovery: what is it, what role, what would 'integrated' mean to them? Then honestly commit to verification. Guessed 'yes' is a landmine in the contract.",
          improved: "First, discovery: 'Tell me about that system — what does it handle, and what would integration need to do?' Then honesty: 'I haven't worked with it, so rather than guess I'll verify exactly what's possible and come back by Thursday.' A guessed yes here becomes a broken promise later.",
        },
        {
          id: "se-obj-8", topic: "Trade-offs", type: "objection_handling", difficulty: "scenario",
          question: "Operations wants zero downtime for the migration; finance won't pay for the parallel-running equipment that makes zero downtime possible. How do you broker this?",
          accepted: ["make the trade-off explicit to both sides and quantify options, cheaper with a planned outage window or costlier with none, let the business choose", "put numbers on each path and facilitate an informed decision between cost and downtime"],
          required: ["trade"], optional: ["quantify", "outage window", "both sides", "informed", "options"],
          explanation: "SE as honest broker: price both paths (planned weekend outage vs parallel-run cost), surface the real business impact of each, and let the business own the choice.",
          improved: "Make the trade-off explicit and quantified for both stakeholders together: option A — a planned weekend cutover with a 4-hour outage, at base cost; option B — parallel running with zero downtime, plus £X. Then the business weighs the outage's true cost against the premium and owns the decision.",
        },
        {
          id: "se-obj-9", topic: "Objection Handling", type: "objection_handling", difficulty: "scenario",
          question: "'Can't we just keep running what we have? It still works.' The gear is end-of-life with no security updates. Frame your response.",
          accepted: ["acknowledge it works today, then explain the risk, no patches means growing exposure, plus failure without support", "respect the sunk cost feeling but quantify the risk of unpatched equipment and unsupported failure"],
          required: ["risk"], optional: ["unpatched", "end of life", "acknowledge", "support", "exposure"],
          explanation: "Validate ('it has served well'), then reframe 'works' vs 'is safe': no security patches = accumulating exposure; no support = failures become crises. Offer a transition path, not a scare.",
          improved: "Acknowledge the truth in it: 'It has served you well and still functions.' Then reframe: functioning isn't the risk — every new vulnerability found from now on stays unpatched forever, and when it fails there's no support behind it. Propose a planned, budgeted transition now versus a forced, rushed one after an incident.",
        },
        {
          id: "se-obj-10", topic: "Trade-offs", type: "objection_handling", difficulty: "scenario",
          question: "A customer demands a feature that would genuinely harm their stated goal (e.g., disabling security scanning 'for performance'). Where's the line between serving and enabling?",
          accepted: ["explain the conflict with their own goals and document the risk, offer alternatives, comply only with informed acknowledgment if at all", "push back constructively with the impact, propose ways to get the performance safely, and record the decision"],
          required: ["risk"], optional: ["their own goals", "document", "alternatives", "informed", "push back"],
          explanation: "Serving ≠ obeying. Surface the self-conflict, quantify the risk, offer safer routes to the underlying need, and if they insist, get informed acknowledgment in writing.",
          improved: "My duty is to their goals, not just their requests: I'd show how the request undermines their own stated objective, quantify the exposure, and offer alternatives that achieve the performance safely. If they still insist, it proceeds only with the risk documented and explicitly acknowledged — in writing.",
        },
        {
          id: "se-obj-11", topic: "Handling Unknowns", type: "objection_handling", difficulty: "scenario",
          question: "You discover after the meeting that something you told a customer was wrong. What now?",
          accepted: ["correct it proactively and promptly with the right information, and explain the impact if any", "reach out first, own the mistake, provide the correction and adjust anything that depended on it"],
          required: ["correct"], optional: ["proactive", "own", "promptly", "before they find out", "impact"],
          explanation: "Proactive correction converts an error into a credibility deposit. Waiting until they discover it converts it into a withdrawal. Speed and ownership matter.",
          improved: "Correct it proactively and fast: contact them, own it plainly — 'I told you X; the accurate answer is Y' — and walk through any impact on what we discussed. A prompt self-correction builds more trust than never erring at all; a discovered error destroys it.",
        },
        {
          id: "se-obj-12", topic: "Objection Handling", type: "objection_handling", difficulty: "scenario",
          question: "The customer's in-house engineer is hostile in meetings, picking at every detail of your proposal. What's likely going on, and what's the professional play?",
          accepted: ["they may feel threatened or own the current design, engage them as the expert, involve them early and let them shape the solution", "treat them as an ally to win, respect their knowledge, address concerns technically and give them ownership"],
          required: ["respect"], optional: ["threatened", "involve", "ownership", "ally", "their expertise"],
          explanation: "Hostility often masks threat (their design being replaced, their role questioned). Convert critic to co-author: consult them, credit them, let the final design carry their fingerprints.",
          improved: "Often that engineer built what you're proposing to replace — the hostility is ownership and self-preservation. The play: make them the local expert, not the obstacle. Consult them early, take their objections seriously on technical merits, incorporate their knowledge visibly, and let the final design carry their fingerprints.",
        },
        {
          id: "se-obj-13", topic: "Trade-offs", type: "objection_handling", difficulty: "scenario",
          question: "'Why does adding redundancy double the price? Can't we have 99.99% for the 99% budget?' Explain the economics honestly.",
          accepted: ["redundancy means buying and running duplicate components, availability rises in steps that each cost real hardware", "each extra nine needs eliminating another single point of failure, which means duplicated equipment and links"],
          required: ["duplicate"], optional: ["single point of failure", "each nine", "hardware", "steps"],
          explanation: "Availability is bought in duplicated hardware: each 'nine' removes another single point of failure — second PSU, second switch, second circuit. Honest answer: match the availability level to the business need.",
          improved: "Because availability is bought with duplication: 99.99% means no single failure can stop you, so critical components exist twice — switches, links, power. Each extra 'nine' eliminates another single point of failure with real hardware. The honest conversation is which systems justify that and which can live with less.",
        },
        {
          id: "se-obj-14", topic: "Handling Unknowns", type: "objection_handling", difficulty: "scenario",
          question: "A customer asks you to commit on the spot to a delivery date you can't verify. Pressure is high. What do you do?",
          accepted: ["don't commit blind, give what i can confirm now and a firm time for the verified answer", "resist the pressured guess, offer a provisional range with the conditions, and confirm quickly after checking"],
          required: ["confirm"], optional: ["not commit blind", "provisional", "verify", "by when", "conditions"],
          explanation: "A pressured false promise costs more than a short wait. Offer what IS known, a provisional range with stated conditions, and a same-day/next-day verified commitment.",
          improved: "I'd hold the line kindly: 'I won't guess on something this important. Here's what I can say now — likely range of X to Y — and I'll have a firm, verified date for you by tomorrow morning.' A broken on-the-spot promise damages far more than a 24-hour wait ever could.",
        },
      ],
    },
    {
      id: "se-architecture-demo",
      title: "Architecture Reasoning & Demo Planning",
      description: "Recommending structural improvements and preparing demos that land.",
      topics: ["Architecture", "Demo Planning"],
      questions: [
        {
          id: "se-arc-1", topic: "Architecture", type: "architecture_reasoning", difficulty: "scenario",
          question: "A business has employees, guest users, IoT devices, and payment systems all on the same network. What architectural improvement would you recommend first, and why?",
          accepted: ["segmentation, separating those classes into isolated zones, because it contains breaches and protects the payment systems", "network segmentation with vlans and firewall policy, reducing risk to the most sensitive systems first"],
          required: ["segment"], optional: ["vlan", "contain", "payment", "risk", "isolate"],
          explanation: "Segmentation first: it's the structural fix that contains any single compromise (guest device, hacked IoT) away from payment systems — the highest-risk asset. Everything else builds on it.",
          improved: "Segmentation, before anything else: separate VLANs/zones for staff, guests, IoT, and payment systems with firewall policy between them. One compromised guest laptop or unpatched IoT device can currently reach the payment systems — segmentation contains that blast radius and also shrinks compliance scope.",
        },
        {
          id: "se-arc-2", topic: "Demo Planning", type: "demo_planning", difficulty: "scenario",
          question: "You are preparing a demo of a network monitoring solution. What should you learn about the customer before building the demo?",
          accepted: ["their use cases, current environment, pain points, stakeholders, success criteria and available time", "what problems they need solved, who attends, what their network looks like, and what would convince them"],
          required: ["pain"], optional: ["use cases", "environment", "stakeholders", "success criteria", "time", "workflows"],
          explanation: "Great demos are mirrors: their environment, their pain, their workflows. Learn use cases, current tooling, attendees (technical? executive?), success criteria, and slot length.",
          improved: "Their actual use cases and pain points (what outage or blind spot hurt recently?), their environment (vendors, topology, scale), who's attending and what convinces each role, their success criteria, relevant daily workflows, and how much time I truly have. The demo should feel like their network, not a product tour.",
        },
        {
          id: "se-arc-3", topic: "Architecture", type: "architecture_reasoning", difficulty: "scenario",
          question: "A fast-growing company keeps adding switches wherever ports run out — daisy-chained randomly. What architectural problem is building, and what structure would you steer toward?",
          accepted: ["an unplanned topology with fragile chains and bottlenecks, move to a hierarchical design with core and access layers", "daisy chains create single points of failure and unpredictable paths, introduce a structured two tier design"],
          required: ["hierarch"], optional: ["daisy chain", "single points of failure", "core", "access", "bottleneck", "structured"],
          explanation: "Organic daisy-chaining breeds bottlenecks, loops, unmappable failures. Steer to hierarchy: access switches uplinked to a redundant core/distribution — predictable paths, contained failures, room to grow.",
          improved: "They're growing an accidental topology: daisy chains where one mid-chain switch failure cuts off everything behind it, and traffic paths nobody can predict. The fix is a hierarchical design — access switches for endpoints, each uplinked (redundantly) to a core/distribution layer — giving predictable performance, contained failures, and a pattern that scales.",
        },
        {
          id: "se-arc-4", topic: "Demo Planning", type: "demo_planning", difficulty: "scenario",
          question: "Why is a generic 'full feature tour' usually a weak demo strategy?",
          accepted: ["it buries what the customer cares about under features they don't, demos should center their specific problems", "audiences disengage from irrelevant features, show their pain being solved instead"],
          required: ["their"], optional: ["irrelevant", "specific problems", "disengage", "pain", "features they don't need"],
          explanation: "Feature tours optimise for the product; demos should optimise for the audience's problem. Three features solving THEIR pain beat thirty features solving nobody's.",
          improved: "Because it optimises for the product instead of the audience: their real problems drown under features they'll never use, and attention dies. A strong demo picks the two or three capabilities that visibly solve THEIR stated pain — ideally on data resembling their environment — and cuts everything else.",
        },
        {
          id: "se-arc-5", topic: "Architecture", type: "architecture_reasoning", difficulty: "scenario",
          question: "A customer with one office is opening a second site and assumes they'll just 'copy the network'. What architectural questions does a second site actually raise?",
          accepted: ["how sites connect, where shared services live, addressing that doesn't clash, and how both are managed and made resilient", "inter site connectivity, centralized versus duplicated services, ip planning, unified management and failover"],
          required: ["connect"], optional: ["services", "addressing", "overlap", "management", "vpn", "resilience"],
          explanation: "Site #2 isn't a copy; it's a WAN: inter-site connectivity (VPN/SD-WAN), service placement (duplicate or centralize?), non-overlapping IP plan, unified management, and cross-site failure behaviour.",
          improved: "A second site turns a LAN into a WAN: How do sites connect securely (VPN/SD-WAN)? Which services stay central and which duplicate (files, DHCP, internet breakout)? The IP plan must not overlap. How is everything managed as one network? And what still works at site B when the link to site A dies?",
        },
        {
          id: "se-arc-6", topic: "Demo Planning", type: "demo_planning", difficulty: "scenario",
          question: "What should you do in the final ten minutes of demo preparation to protect against live-demo disasters?",
          accepted: ["test the exact flow end to end and prepare fallbacks like screenshots or a recording", "dry run the demo path, verify connectivity and logins, and have a backup plan ready"],
          required: ["test"], optional: ["fallback", "screenshots", "recording", "dry run", "backup", "logins"],
          explanation: "Run the exact click-path once, verify accounts/network/data, and stage fallbacks (screenshots, recording) so a Wi-Fi hiccup doesn't become the meeting's memory.",
          improved: "Dry-run the exact demo path once — same machine, same logins, same clicks — verify network and accounts work in that room, and stage fallbacks: screenshots of every key screen and a short recording. If something breaks live, you switch seamlessly instead of debugging in front of the audience.",
        },
        {
          id: "se-arc-7", topic: "Architecture", type: "architecture_reasoning", difficulty: "scenario",
          question: "An organisation runs everything through one central firewall — now a performance bottleneck. Before recommending a bigger box, what architectural alternatives deserve consideration?",
          accepted: ["examine what traffic actually needs inspection, offload east west or internet bound flows differently, consider distributed enforcement", "traffic analysis first, then options like local internet breakout, segmentation policies at the switch layer, or scaling out"],
          required: ["traffic"], optional: ["offload", "distributed", "breakout", "east west", "analyse", "scale out"],
          explanation: "Bigger-box is one answer; architecture offers others: analyse flows first — maybe east-west traffic can be enforced at the switch layer, branch internet can break out locally, or inspection can be distributed/scaled out.",
          improved: "First analyse what's actually flowing through it — often much traffic doesn't need that firewall's inspection. Then weigh alternatives: enforcing internal (east-west) policy at the switch layer, local internet breakout for branches instead of hairpinning, or scaling firewalls out rather than up. The bigger box is sometimes right — but it's the last conclusion, not the first.",
        },
        {
          id: "se-arc-8", topic: "Demo Planning", type: "demo_planning", difficulty: "scenario",
          question: "Your demo audience is a mix: a hands-on network engineer and a budget-holding director. How do you structure one demo for both?",
          accepted: ["open with business outcomes for the director, then a focused technical segment for the engineer, giving each role a dedicated chapter", "layer it, outcome story first, depth second, and invite the engineer to drive or probe"],
          required: ["both"], optional: ["outcomes first", "technical depth", "layer", "each role", "engineer drive"],
          explanation: "Chapter the demo by audience: outcome/value narrative first (director), then a hands-on technical dive (engineer — let them drive or probe). Signpost so each knows their part is coming.",
          improved: "Structure it in labelled chapters: open with the business story — problem, outcome, cost — for the director, then a deeper technical segment where the engineer can probe or even drive. Signpost at the start so each knows their chapter is coming, and close by connecting the technical proof back to the business outcome.",
        },
        {
          id: "se-arc-9", topic: "Architecture", type: "architecture_reasoning", difficulty: "scenario",
          question: "'We'll add security later, once the network is running.' What's the architectural counter-argument?",
          accepted: ["security retrofitted later costs more and works worse, foundational choices like segmentation are cheapest at design time", "the network's structure is the security foundation, bolting it on later means redesign not addition"],
          required: ["later"], optional: ["retrofit", "design time", "foundation", "segmentation", "cheaper now"],
          explanation: "Security isn't a layer of paint; it's load-bearing structure. Segmentation, identity, policy points cost little at design time and force redesigns when retrofitted.",
          improved: "Security added later isn't addition — it's redesign. Choices like segmentation, where policy is enforced, and how identity works are structural: nearly free to include at design time, disruptive and expensive to retrofit onto a live flat network. Build the skeleton right; the features can come later, the architecture can't.",
        },
        {
          id: "se-arc-10", topic: "Demo Planning", type: "demo_planning", difficulty: "scenario",
          question: "After a demo, what follow-up habits separate excellent SEs from average ones?",
          accepted: ["prompt summary of what was shown and agreed, answers to open questions by the promised dates, and clear next steps", "same day recap with commitments captured, unanswered questions tracked to closure, and a proposed path forward"],
          required: ["follow"], optional: ["summary", "open questions", "next steps", "commitments", "same day"],
          explanation: "The demo's value is realised in the follow-up: same-day recap, every open question tracked to a dated answer, and concrete proposed next steps. Reliability compounds.",
          improved: "A same-day written recap: what was shown, what was agreed, every open question with a date I'll answer it by, and a proposed next step. Then actually closing each question on time. The demo creates interest; the follow-through converts it — and demonstrates exactly the reliability they're buying.",
        },
        {
          id: "se-arc-11", topic: "Architecture", type: "architecture_reasoning", difficulty: "scenario",
          question: "A nonprofit asks you to review their architecture pro bono expectations aside — you find it's actually fine. What do you report?",
          accepted: ["that it's sound, with minor observations if any, resisting the urge to invent problems to seem valuable", "an honest clean bill of health, maybe small improvements and risks to watch as it grows"],
          required: ["fine"], optional: ["honest", "sound", "no invented problems", "minor", "watch as it grows"],
          explanation: "The honest 'it's good' is a credibility investment. Add genuine minor observations and growth-triggers to watch — but manufacturing problems to justify the review poisons trust.",
          improved: "Exactly that: 'Your architecture is sound.' I'd add whatever genuine minor observations exist and the growth thresholds where it will need revisiting — but inventing problems to justify the engagement would be the real failure. An honest clean bill of health earns the call when something real breaks.",
        },
        {
          id: "se-arc-12", topic: "Architecture", type: "architecture_reasoning", difficulty: "scenario",
          question: "What is a 'single point of failure' analysis, and why should it precede any resilience spending?",
          accepted: ["mapping every component whose lone failure stops the business, so redundancy budget targets the worst gaps first", "finding the spofs and ranking them by impact directs spending where it actually reduces risk"],
          required: ["single point"], optional: ["map", "impact", "prioritize", "redundancy", "worst first"],
          explanation: "SPOF analysis walks the paths business-critical services depend on, finding components with no backup. It converts vague 'resilience' spending into a ranked list of actual risk reductions.",
          improved: "It's a systematic walk through every path critical services depend on — internet, power, core switch, firewall, that one server — flagging components whose lone failure stops the business. Done first, it turns resilience budget from guesswork into a ranked list: fix the highest-impact gaps first, skip redundancy where failure barely matters.",
        },
      ],
    },
  ],
});
